module

public import RequestProject.BlockFamilyChainModel

@[expose] public section

/-!
# The relative vanishing of the family, reduced to one block

`RequestProject/BlockFamilyChainModel.lean` reduces property (B2) for the article's
simultaneous substitution to two geometric inputs: the `π₁`-injectivity of the substitution
and the vanishing `H₂(W̃, U) = 0` for the constructed relative complex of the pair.

This file computes the second one.  The relative chain complex of the pair is the quotient of
the two-chains of the cover by the chains of the preimage of `X`, and in the coordinates built
in the previous file that quotient is *block-local*: the retained two-cells and the old
polygons are killed by the quotient, and the only surviving coordinates are those of the cells
of the blocks, modulo the filling chains.  Accordingly:

* `FiniteChains.BlockFamily.mem_subTwo_iff` — a two-chain of the cover lies in the chains of
  the preimage of `X` exactly when it has no polygon component and its block components are
  multiples of the filling chains;
* `FiniteChains.BlockFamily.foxBdry_inr` — the Fox boundary of the substituted presentation,
  read at an internal generator of the block at `s`, only sees the cells of that one block;
* `FiniteChains.BlockFamily.relBdry₂_mk_eq_zero_iff` — hence a relative two-cycle is exactly a
  family of chains on the cells of the blocks which are cycles for the internal generators of
  their own block;
* `FiniteChains.BlockFamily.relative_vanishing_iff_blockGenerates` — **`H₂(W̃, U) = 0` holds
  for the whole family if and only if it holds for one block at a time**, in the form

    `BlockSurfaceGenerates`: for every entry `s`, a chain on the cells of the block at `s`
    whose Fox boundary vanishes at every internal generator of that block is a multiple of
    the filling chain `c s` of the surface.

  This is the article's statement that the second homotopy of the block, relative to the
  glued surface, is generated by the surface: no interaction between distinct blocks, and no
  dependence on `X`, is left in the geometric input, however large the replaced family is.

The final statement of the file,
`FiniteChains.BlockFamily.generates_familySubst_of_blockGenerates`, is property (B2) —
equation (3.3) — for the article's simultaneous substitution, from the `π₁`-injectivity of
the substitution and this one-block input.
-/

namespace FiniteChains

namespace BlockFamily

open MonoidAlgebra

universe u

variable {α Jr Sx : Type u} {Zt Mt : Sx → Type u}
  [Fintype α] [DecidableEq α] [Fintype Jr] [DecidableEq Jr]
  [Fintype Sx] [DecidableEq Sx]
  [∀ s, Fintype (Zt s)] [∀ s, DecidableEq (Zt s)] [∀ s, Fintype (Mt s)]
  {ρ : Jr ⊕ Sx → FreeGroup α} {bsub : ∀ s : Sx, Mt s → FreeGroup (α ⊕ Zt s)}
  {hfill : FilledF ρ bsub}
  {c : ∀ s : Sx, Mt s → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub))}

variable (hc : IsFillingF ρ bsub hfill c)

omit [Fintype α] [∀ s, Fintype (Zt s)] in
/-- **The two-chains of the preimage of `X`.**  A two-chain of the cover of the double mapping
cylinder comes from the preimage of `X` exactly when it has no component on the replaced
polygons and its components on the cells of each block are a multiple of that block's filling
chain: the copies of `X̃` carry the retained two-cells and the fillings of the replaced
relators. -/
theorem mem_subTwo_iff
    (x : ((Jr ⊕ (Σ s : Sx, Mt s)) → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))
      × (Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))) :
    x ∈ BlockFox.subTwo (Q := Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))
        (substMorF ρ bsub hfill c hc)
      ↔ x.2 = 0 ∧ ∃ w : Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)),
          ∀ (s : Sx) (m : Mt s), x.1 (Sum.inr ⟨s, m⟩) = w s * c s m := by
  constructor
  · rintro ⟨a, ha⟩
    have hfst := congrFun (congrArg Prod.fst ha)
    refine ⟨(congrArg Prod.snd ha).symm, fun s => a (Sum.inr s), fun s m => ?_⟩
    have h := hfst (Sum.inr (⟨s, m⟩ : Σ s : Sx, Mt s))
    rw [← h]
    exact cellsBase_inr hc a ⟨s, m⟩
  · rintro ⟨h2, w, hw⟩
    refine ⟨Sum.elim (fun j => x.1 (Sum.inl j)) w, ?_⟩
    refine Prod.ext ?_ ?_
    · funext k
      cases k with
      | inl j => rw [BlockFox.inclModel_apply]; exact cellsBase_inl hc _ j
      | inr p =>
          rw [BlockFox.inclModel_apply]
          show (substMorF ρ bsub hfill c hc).cellsBase _ (Sum.inr p) = _
          rw [cellsBase_inr hc _ p]
          exact (hw p.1 p.2).symm
    · rw [BlockFox.inclModel_apply]
      exact h2.symm

omit [Fintype α] [DecidableEq Jr] [∀ s, Fintype (Zt s)] in
/-- **At an internal generator only its own block is visible.**  The Fox boundary of the
substituted presentation, evaluated at an internal generator of the block at `s`, is the sum
over the cells of that block alone. -/
theorem foxBdry_inr
    (γ : (Jr ⊕ (Σ s : Sx, Mt s)) → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))
    (s : Sx) (z : Zt s) :
    foxBdry (substPresF ρ bsub) γ (Sum.inr ⟨s, z⟩)
      = ∑ m : Mt s, γ (Sum.inr ⟨s, m⟩)
          * foxMatrixPres (substPresF ρ bsub) (Sum.inr ⟨s, z⟩) (Sum.inr ⟨s, m⟩) := by
  show (∑ k : Jr ⊕ (Σ s : Sx, Mt s), γ k
      * foxMatrixPres (substPresF ρ bsub) (Sum.inr ⟨s, z⟩) k) = _
  rw [Fintype.sum_sum_type]
  have hl : ∑ j : Jr, γ (Sum.inl j)
      * foxMatrixPres (substPresF ρ bsub) (Sum.inr ⟨s, z⟩) (Sum.inl j) = 0 := by
    refine Finset.sum_eq_zero fun j _ => ?_
    rw [foxMatrix_inr_inl ρ bsub, mul_zero]
  rw [hl, zero_add, Fintype.sum_sigma]
  rw [Finset.sum_eq_single s]
  · intro s' _ hs'
    refine Finset.sum_eq_zero fun m _ => ?_
    rw [foxMatrix_inr_inr_of_ne ρ bsub hs' z m, mul_zero]
  · intro hs
    exact absurd (Finset.mem_univ s) hs

omit [Fintype α] [DecidableEq α] [Fintype Jr] [DecidableEq Jr] [Fintype Sx] [DecidableEq Sx]
  [∀ s, Fintype (Zt s)] [∀ s, DecidableEq (Zt s)] [∀ s, Fintype (Mt s)] in
/-- **The one-chains of the preimage of `X`** are exactly the chains supported on the old
generators. -/
theorem mem_subOne_iff
    (v : (α ⊕ (Σ s : Sx, Zt s)) → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub))) :
    v ∈ BlockFox.subOne (α := α) (oneChainIncl ρ bsub)
      ↔ ∀ w : Σ s : Sx, Zt s, v (Sum.inr w) = 0 := by
  constructor
  · rintro ⟨u, rfl⟩ w
    rfl
  · intro h
    refine ⟨fun i => v (Sum.inl i), ?_⟩
    funext k
    cases k with
    | inl i => rfl
    | inr w => exact (h w).symm

omit [Fintype α] [∀ s, Fintype (Zt s)] in
/-- **A relative two-cycle is a family of block cycles.**  In the coordinates of the model the
relative boundary of the class of a two-chain vanishes exactly when, for every replaced entry
`s`, the components of the chain on the cells of the block at `s` form a cycle for the
internal generators of that block. -/
theorem relBdry₂_mk_eq_zero_iff
    (x : ((Jr ⊕ (Σ s : Sx, Mt s)) → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))
      × (Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))) :
    BlockFox.relBdry₂ (bq := polyBdry ρ bsub hfill) (chainMap_incl hc)
        (Submodule.Quotient.mk x) = 0
      ↔ ∀ (s : Sx) (z : Zt s), ∑ m : Mt s, x.1 (Sum.inr ⟨s, m⟩)
          * foxMatrixPres (substPresF ρ bsub) (Sum.inr ⟨s, z⟩) (Sum.inr ⟨s, m⟩) = 0 := by
  rw [BlockFox.relBdry₂, Submodule.mapQ_apply, Submodule.Quotient.mk_eq_zero,
    mem_subOne_iff]
  constructor
  · intro h s z
    have hz := h ⟨s, z⟩
    rw [← foxBdry_inr x.1 s z]
    have : BlockFox.bdry₂model (Q := Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))
        (polyBdry ρ bsub hfill) x (Sum.inr ⟨s, z⟩)
        = foxBdry (substPresF ρ bsub) x.1 (Sum.inr ⟨s, z⟩) := by
      show foxBdry (substPresF ρ bsub) x.1 (Sum.inr ⟨s, z⟩)
        + polyBdry ρ bsub hfill x.2 (Sum.inr ⟨s, z⟩) = _
      rw [polyBdry_inr, add_zero]
    rw [this] at hz
    exact hz
  · intro h w
    obtain ⟨s, z⟩ := w
    show foxBdry (substPresF ρ bsub) x.1 (Sum.inr ⟨s, z⟩)
      + polyBdry ρ bsub hfill x.2 (Sum.inr ⟨s, z⟩) = 0
    rw [polyBdry_inr, add_zero, foxBdry_inr x.1 s z]
    exact h s z

/-- **The geometric input of (B2), localised at one block.**  For every replaced entry `s`, a
chain on the two-cells of the block substituted at `s` whose Fox boundary vanishes at every
internal generator of that block is a multiple of the filling chain of the surface.  This is
the relative asphericity of the block: `π₂` of the block relative to the glued surface is
generated by the surface. -/
def BlockSurfaceGenerates (ρ : Jr ⊕ Sx → FreeGroup α)
    (bsub : ∀ s : Sx, Mt s → FreeGroup (α ⊕ Zt s))
    (c : ∀ s : Sx, Mt s → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub))) : Prop :=
  ∀ (s : Sx) (β : Mt s → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub))),
    (∀ z : Zt s, ∑ m : Mt s, β m
        * foxMatrixPres (substPresF ρ bsub) (Sum.inr ⟨s, z⟩) (Sum.inr ⟨s, m⟩) = 0) →
      ∃ w : MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)), ∀ m : Mt s, β m = w * c s m

omit [Fintype α] [∀ s, Fintype (Zt s)] in
/-- **`H₂(W̃, U) = 0` for the whole family is equivalent to the one-block statement.**  The
relative complex of the pair is block-local, so the relative vanishing for an arbitrary family
of simultaneously replaced entries says neither more nor less than the relative asphericity of
a single block. -/
theorem relative_vanishing_iff_blockGenerates :
    (∀ q : BlockFox.RelTwo
        (Q := Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))
        (substMorF ρ bsub hfill c hc),
      BlockFox.relBdry₂ (bq := polyBdry ρ bsub hfill) (chainMap_incl hc) q = 0 →
        ∃ y : Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)),
          BlockFox.relBdry₃ (Q := Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))
            (f := substMorF ρ bsub hfill c hc) (cylChain ρ bsub c) (cylCancel ρ bsub) y = q)
      ↔ BlockSurfaceGenerates ρ bsub c := by
  classical
  constructor
  · intro hrel s β hβ
    -- the two-chain supported on the cells of the block at `s`, with coefficients `β`
    set γ : (Jr ⊕ (Σ s : Sx, Mt s)) → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)) :=
      Sum.elim 0 (fun p => if h : p.1 = s then β (h ▸ p.2) else 0) with hγdef
    have hγs : ∀ m : Mt s, γ (Sum.inr ⟨s, m⟩) = β m := by
      intro m
      show (if h : s = s then β (h ▸ m) else 0) = β m
      rw [dif_pos rfl]
    have hγne : ∀ (s' : Sx) (m : Mt s'), s' ≠ s → γ (Sum.inr ⟨s', m⟩) = 0 := by
      intro s' m hs'
      show (if h : s' = s then β (h ▸ m) else 0) = 0
      rw [dif_neg hs']
    have hcyc : BlockFox.relBdry₂ (bq := polyBdry ρ bsub hfill) (chainMap_incl hc)
        (Submodule.Quotient.mk (γ, 0)) = 0 := by
      rw [relBdry₂_mk_eq_zero_iff hc]
      intro s' z
      by_cases hs' : s' = s
      · subst hs'
        rw [← hβ z]
        refine Finset.sum_congr rfl fun m _ => ?_
        change γ (Sum.inr ⟨s', m⟩) * _ = _
        rw [hγs m]
      · refine Finset.sum_eq_zero fun m _ => ?_
        change γ (Sum.inr ⟨s', m⟩) * _ = _
        rw [hγne s' m hs', zero_mul]
    obtain ⟨y, hy⟩ := hrel _ hcyc
    have hmem : (Cancel.bdry₃ (cylChain ρ bsub c) (cylCancel ρ bsub) y) - (γ, 0)
        ∈ BlockFox.subTwo (Q := Sx → MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub)))
          (substMorF ρ bsub hfill c hc) :=
      (Submodule.Quotient.eq _).1 hy
    rw [mem_subTwo_iff hc] at hmem
    obtain ⟨h2, w, hw⟩ := hmem
    have hy0 : y = 0 := by
      have h : (cylCancel ρ bsub) y - (0 : Sx → MonoidAlgebra ℤ (PresGroup
        (substPresF ρ bsub))) = 0 := h2
      rw [cylCancel_apply, sub_zero, neg_eq_zero] at h
      exact h
    refine ⟨-w s, fun m => ?_⟩
    have h := hw s m
    rw [hy0] at h
    have hz : cylChain ρ bsub c (0 : Sx → MonoidAlgebra ℤ
      (PresGroup (substPresF ρ bsub))) = 0 := map_zero _
    have h' : -γ (Sum.inr (⟨s, m⟩ : Σ s : Sx, Mt s)) = w s * c s m := by
      have : (Cancel.bdry₃ (cylChain ρ bsub c) (cylCancel ρ bsub) 0 - (γ, 0)).1
          (Sum.inr (⟨s, m⟩ : Σ s : Sx, Mt s))
          = cylChain ρ bsub c 0 (Sum.inr ⟨s, m⟩) - γ (Sum.inr ⟨s, m⟩) := rfl
      rw [this, hz] at h
      simpa using h
    rw [hγs m] at h'
    rw [← neg_neg (β m), h', neg_mul]
  · intro hblock q hq
    obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ q
    rw [relBdry₂_mk_eq_zero_iff hc] at hq
    choose w hw using fun s => hblock s (fun m => x.1 (Sum.inr ⟨s, m⟩)) (hq s)
    refine ⟨-x.2, ?_⟩
    show Submodule.Quotient.mk (Cancel.bdry₃ (cylChain ρ bsub c) (cylCancel ρ bsub) (-x.2))
      = Submodule.Quotient.mk x
    rw [Submodule.Quotient.eq, mem_subTwo_iff hc]
    constructor
    · show (cylCancel ρ bsub) (-x.2) - x.2 = 0
      rw [cylCancel_apply, neg_neg, sub_self]
    · refine ⟨fun s => -x.2 s - w s, fun s m => ?_⟩
      show cylChain ρ bsub c (-x.2) (Sum.inr (⟨s, m⟩ : Σ s : Sx, Mt s))
        - x.1 (Sum.inr ⟨s, m⟩) = _
      rw [cylChain_inr, hw s m]
      simp [sub_mul]

omit [Fintype α] [∀ s, Fintype (Zt s)] in
/-- **Property (B2) for the article's simultaneous substitution, from the one-block input.**
Equation (3.3) for the structural map of the substitution of a whole family of blocks: the
remaining hypotheses are the `π₁`-injectivity of the substitution (Step 1 of the article's
proof) and the relative asphericity of a single block (`BlockSurfaceGenerates`), which is what
Steps 2 and 3 establish from the cube structure of the collapsed space. -/
theorem generates_familySubst_of_blockGenerates
    (hinj : Function.Injective (substHomF ρ bsub hfill))
    (hblock : BlockSurfaceGenerates ρ bsub c) :
    Generates (substMorF ρ bsub hfill c hc) :=
  generates_familySubst_of_relative_vanishing hc hinj
    ((relative_vanishing_iff_blockGenerates hc).2 hblock)

end BlockFamily

end FiniteChains
