import RequestProject.BlockFamilyBlockwiseFinsupp
import RequestProject.BaseChangeExactFinsupp

/-!
The actual B1 chain identity for simultaneous block substitution, with finite
support in every cell index. Its base-change boundary uses the existing
`coeffF`, and its target boundary is `coverSecondBoundary`.

Together with the block-local B2 assembly, injectivity of the substituted
group map yields generation by original-group Fox cycles. The proof uses
the existing finite-support coset-slice theorem, not an assumed global
generation statement. Geometric B1 and block-local B2 remain the stated
inputs. This source has not been compiled under the current workflow.
-/

noncomputable section

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains

section RingMap

variable {R S : Type*} [Ring R] [Ring S] {J I : Type*}

/-- Extend every finite matrix column along a coefficient ring homomorphism. -/
def fsRingMapBoundary (φ : R →+* S) (A : J → I →₀ R) :
    (J →₀ S) →ₗ[S] (I →₀ S) :=
  Finsupp.linearCombination S (fun j => (A j).mapRange φ (map_zero _))

/-- The base-changed boundary commutes with the actual coefficient map. -/
theorem fsRingMapBoundary_mapRange (φ : R →+* S) (A : J → I →₀ R)
    (y : J →₀ R) :
    fsRingMapBoundary φ A (y.mapRange φ (map_zero _)) =
      (Finsupp.linearCombination R A y).mapRange φ (map_zero _) := by
  induction y using Finsupp.induction_linear with
  | zero => simp [fsRingMapBoundary]
  | add y z hy hz =>
      rw [Finsupp.mapRange_add, map_add, map_add, Finsupp.mapRange_add, hy, hz] <;>
        exact fun a b => map_add φ a b
  | single j a =>
      simp only [Finsupp.mapRange_single, fsRingMapBoundary,
        Finsupp.linearCombination_single]
      ext i
      exact (map_mul φ a (A j i)).symm

end RingMap

section GroupMap

variable {G G' : Type*} [Group G] [Group G'] {J I : Type*}

/-- For an injective group map, the cycles of the base-changed finite-support
matrix are generated by coefficient images of original-group cycles. -/
theorem fs_cycle_mem_span_groupMap_cycles (f : G →* G') (hf : Function.Injective f)
    (A : J → I →₀ MonoidAlgebra ℤ G) (x : J →₀ MonoidAlgebra ℤ G')
    (hx : fsRingMapBoundary (MonoidAlgebra.mapDomainRingHom ℤ f) A x = 0) :
    x ∈ Submodule.span (MonoidAlgebra ℤ G')
      {v : J →₀ MonoidAlgebra ℤ G' | ∃ y : J →₀ MonoidAlgebra ℤ G,
        Finsupp.linearCombination (MonoidAlgebra ℤ G) A y = 0 ∧
        v = y.mapRange (MonoidAlgebra.mapDomainRingHom ℤ f) (map_zero _)} := by
  classical
  let H := f.range
  let e : G ≃* H := MonoidHom.ofInjective hf
  let φ : MonoidAlgebra ℤ G →+* MonoidAlgebra ℤ H :=
    MonoidAlgebra.mapDomainRingHom ℤ e.toMonoidHom
  let ψ : MonoidAlgebra ℤ H →+* MonoidAlgebra ℤ G :=
    MonoidAlgebra.mapDomainRingHom ℤ e.symm.toMonoidHom
  let θ : MonoidAlgebra ℤ G →+* MonoidAlgebra ℤ G' :=
    MonoidAlgebra.mapDomainRingHom ℤ f
  have hφ : ∀ a, subRingHom H (φ a) = θ a := by
    intro a
    change MonoidAlgebra.mapDomain _ (MonoidAlgebra.mapDomain _ a) = MonoidAlgebra.mapDomain _ a
    rw [← MonoidAlgebra.mapDomain_comp]
    rfl
  have hφψ : ∀ a, φ (ψ a) = a := by
    intro a
    change MonoidAlgebra.mapDomain _ (MonoidAlgebra.mapDomain _ a) = a
    rw [← MonoidAlgebra.mapDomain_comp]
    have he : (e.toMonoidHom : G → H) ∘ (e.symm.toMonoidHom : H → G) = id := by
      funext g
      exact e.apply_symm_apply g
    rw [he, MonoidAlgebra.mapDomain_id]
  have hφinj : Function.Injective φ := fun _ _ h => MonoidAlgebra.coeff_injective (Finsupp.mapDomain_injective e.injective (congrArg MonoidAlgebra.coeff h))
  let A' : J → I →₀ MonoidAlgebra ℤ H :=
    fun j => (A j).mapRange φ (map_zero _)
  have hboundary : fsExtendedBoundary H A' = fsRingMapBoundary θ A := by
    apply Finsupp.lhom_ext
    intro j a
    simp only [fsExtendedBoundary, fsRingMapBoundary, Finsupp.linearCombination_single]
    congr 1
    ext i : 1
    exact hφ (A j i)
  have hx' : fsExtendedBoundary H A' x = 0 := by
    rw [hboundary]
    exact hx
  have hmem := fs_cycle_mem_span_subgroup_cycles H A' x hx'
  refine Submodule.span_mono ?_ hmem
  rintro v ⟨w, hw, rfl⟩
  let y := w.mapRange ψ (map_zero _)
  have hy : y.mapRange φ (map_zero _) = w := by
    ext j : 1
    exact hφψ (w j)
  refine ⟨y, ?_, ?_⟩
  · have hb : (Finsupp.linearCombination (MonoidAlgebra ℤ G) A y).mapRange
        φ (map_zero _) = 0 := by
      rw [← fsRingMapBoundary_mapRange]
      change Finsupp.linearCombination (MonoidAlgebra ℤ H) A'
        (y.mapRange φ (map_zero _)) = 0
      rw [hy]
      exact hw
    apply Finsupp.ext
    intro i
    apply hφinj
    have hi := congrArg (fun z : I →₀ MonoidAlgebra ℤ H => z i) hb
    simpa only [Finsupp.mapRange_apply, Finsupp.zero_apply, map_zero] using hi
  · apply Finsupp.ext
    intro j
    change subRingHom H (w j) = θ (ψ (w j))
    rw [← hφ, hφψ]

end GroupMap

namespace BlockFamily

universe u

section ChainColumns

variable {Jr Sx R : Type u} {Mt : Sx → Type u} [Ring R]

/-- The filling of one block, in the actual substituted cell coordinates. -/
def fsSurfaceChain (c : ∀ s, Mt s →₀ R) (s : Sx) : (Jr ⊕ (Σ s, Mt s)) →₀ R :=
  (c s).mapDomain (fun m => Sum.inr ⟨s, m⟩)

@[simp] theorem fsSurfaceChain_inl (c : ∀ s, Mt s →₀ R) (s : Sx) (j : Jr) :
    fsSurfaceChain c s (Sum.inl j) = 0 := by
  apply Finsupp.mapDomain_notin_range
  rintro ⟨m, h⟩
  exact Sum.inr_ne_inl h

@[simp] theorem fsSurfaceChain_inr (c : ∀ s, Mt s →₀ R) (s : Sx) (m : Mt s) :
    fsSurfaceChain (Jr := Jr) c s (Sum.inr ⟨s, m⟩) = c s m := by
  apply Finsupp.mapDomain_apply_of_injective
  intro a b h
  exact eq_of_heq (Sigma.mk.inj (Sum.inr_injective h)).2

theorem fsSurfaceChain_inr_of_ne (c : ∀ s, Mt s →₀ R) {s t : Sx}
    (hst : s ≠ t) (m : Mt t) :
    fsSurfaceChain (Jr := Jr) c s (Sum.inr ⟨t, m⟩) = 0 := by
  apply Finsupp.mapDomain_notin_range
  rintro ⟨a, h⟩
  exact hst (congrArg Sigma.fst (Sum.inr_injective h))

@[simp] theorem fsCellsBase_single_inl (c : ∀ s, Mt s →₀ R) (j : Jr) :
    fsCellsBase c (Finsupp.single (Sum.inl j) 1) = Finsupp.single (Sum.inl j) 1 := by
  classical
  ext k
  cases k with
  | inl i => simp only [fsCellsBase_inl, Finsupp.single_apply, Sum.inl.injEq]
  | inr p => obtain ⟨s, m⟩ := p; simp

@[simp] theorem fsCellsBase_single_inr (c : ∀ s, Mt s →₀ R) (s : Sx) :
    fsCellsBase (Jr := Jr) c (Finsupp.single (Sum.inr s) 1) = fsSurfaceChain c s := by
  classical
  ext k
  cases k with
  | inl j => simp
  | inr p =>
      obtain ⟨t, m⟩ := p
      by_cases hst : s = t
      · subst t
        simp
      · simp [hst, fsSurfaceChain_inr_of_ne c hst m]

/-- Include old generator chains by extension by zero on the internal ones. -/
def fsOldOneIncl {α Z : Type u} : (α →₀ R) →ₗ[R] ((α ⊕ Z) →₀ R) where
  toFun x := Finsupp.sumElim x 0
  map_add' x y := by ext k; cases k <;> simp [Finsupp.sumElim_apply]
  map_smul' a x := by ext k; cases k <;> simp [Finsupp.sumElim_apply]

@[simp] theorem fsOldOneIncl_inl {α Z : Type u} (x : α →₀ R) (i : α) :
    fsOldOneIncl (Z := Z) x (Sum.inl i) = x i := rfl

@[simp] theorem fsOldOneIncl_inr {α Z : Type u} (x : α →₀ R) (z : Z) :
    fsOldOneIncl x (Sum.inr z) = 0 := rfl

theorem fsOldOneIncl_injective {α Z : Type u} :
    Function.Injective (fsOldOneIncl (α := α) (Z := Z) (R := R)) := by
  intro x y h
  ext i
  exact congrArg (fun z : (α ⊕ Z) →₀ R => z (Sum.inl i)) h

end ChainColumns

section Substitution

variable {α Jr Sx : Type u} {Zt Mt : Sx → Type u}
  [DecidableEq α] [DecidableEq Sx] [∀ s, DecidableEq (Zt s)]
  (ρ : Jr ⊕ Sx → FreeGroup α)
  (bsub : ∀ s, Mt s → FreeGroup (α ⊕ Zt s))
  (hfill : FilledF ρ bsub)

local notation "R'" => MonoidAlgebra ℤ (PresGroup (substPresF ρ bsub))
local notation "R₀" => MonoidAlgebra ℤ (PresGroup ρ)

/-- The old Fox boundary over the actual substituted group ring. -/
def fsFoxPushBoundary : ((Jr ⊕ Sx) →₀ R') →ₗ[R'] (α →₀ R') :=
  fsRingMapBoundary (coeffF ρ bsub hfill)
    (fun k => coverFoxGradient (relSub ρ) (ρ k))

omit [DecidableEq Sx] [∀ s, DecidableEq (Zt s)] in
@[simp] theorem fsFoxPushBoundary_single (k : Jr ⊕ Sx) (i : α) :
    fsFoxPushBoundary ρ bsub hfill (Finsupp.single k 1) i =
      coeffF ρ bsub hfill (foxMatrixPres ρ i k) := by
  simp only [fsFoxPushBoundary, fsRingMapBoundary, Finsupp.linearCombination_single,
    one_smul, Finsupp.mapRange_apply]
  rfl

/-- B1 in finite-support coordinates: the surface filling has the replaced
polygon's old boundary and zero internal boundary in its own block. -/
structure IsFillingFS (c : ∀ s, Mt s →₀ R') : Prop where
  base : ∀ (s : Sx) (i : α),
    (c s).sum (fun m a => a *
      foxMatrixPres (substPresF ρ bsub) (Sum.inl i) (Sum.inr ⟨s, m⟩)) =
        coeffF ρ bsub hfill (foxMatrixPres ρ i (Sum.inr s))
  internal : ∀ (s : Sx) (z : Zt s),
    (c s).sum (fun m a => a *
      foxMatrixPres (substPresF ρ bsub) (Sum.inr ⟨s, z⟩) (Sum.inr ⟨s, m⟩)) = 0

/-- A geometric B1 calculation on each finite block supplies the supported
input without imposing any finiteness on the family or the old presentation. -/
theorem isFillingFS_of_finite_blocks [∀ s, Fintype (Mt s)]
    (c : ∀ s, Mt s →₀ R')
    (hbase : ∀ (s : Sx) (i : α), ∑ m : Mt s, c s m *
      foxMatrixPres (substPresF ρ bsub) (Sum.inl i) (Sum.inr ⟨s, m⟩) =
        coeffF ρ bsub hfill (foxMatrixPres ρ i (Sum.inr s)))
    (hinternal : ∀ (s : Sx) (z : Zt s), ∑ m : Mt s, c s m *
      foxMatrixPres (substPresF ρ bsub) (Sum.inr ⟨s, z⟩) (Sum.inr ⟨s, m⟩) = 0) :
    IsFillingFS ρ bsub hfill c where
  base s i := by
    rw [Finsupp.sum_fintype _ _ (fun _ => zero_mul _)]
    exact hbase s i
  internal s z := by
    rw [Finsupp.sum_fintype _ _ (fun _ => zero_mul _)]
    exact hinternal s z

theorem fsSurfaceChain_boundary_apply (c : ∀ s, Mt s →₀ R') (s : Sx)
    (i : α ⊕ (Σ s, Zt s)) :
    coverSecondBoundary (relSub (substPresF ρ bsub)) (substPresF ρ bsub)
        (fsSurfaceChain c s) i =
      (c s).sum (fun m a => a *
        foxMatrixPres (substPresF ρ bsub) i (Sum.inr ⟨s, m⟩)) := by
  rw [fsCoverSecondBoundary_apply]
  exact Finsupp.sum_mapDomain_index (fun _ => zero_mul _)
    (fun _ _ _ => add_mul _ _ _)

/-- B1 extends from every single actual surface filling to the full
simultaneous substitution chain map, without finite index assumptions. -/
theorem fsCellsBase_chainMap (c : ∀ s, Mt s →₀ R')
    (hc : IsFillingFS ρ bsub hfill c) :
    (coverSecondBoundary (relSub (substPresF ρ bsub)) (substPresF ρ bsub)).comp
        (fsCellsBase c) =
      fsOldOneIncl.comp (fsFoxPushBoundary ρ bsub hfill) := by
  classical
  apply Finsupp.lhom_ext
  intro k a
  rw [← Finsupp.smul_single_one k a, map_smul, map_smul]
  congr 1
  simp only [LinearMap.comp_apply]
  cases k with
  | inl j =>
      rw [fsCellsBase_single_inl]
      ext i : 1
      cases i with
      | inl i =>
          rw [fsOldOneIncl_inl, fsFoxPushBoundary_single, fsCoverSecondBoundary_apply]
          simp [foxMatrix_inl_inl ρ bsub hfill]
      | inr p =>
          rw [fsOldOneIncl_inr, fsCoverSecondBoundary_apply]
          simp [foxMatrix_inr_inl ρ bsub]
  | inr s =>
      rw [fsCellsBase_single_inr]
      ext i : 1
      cases i with
      | inl i =>
          rw [fsOldOneIncl_inl, fsFoxPushBoundary_single, fsSurfaceChain_boundary_apply]
          exact hc.base s i
      | inr p =>
          obtain ⟨t, z⟩ := p
          rw [fsOldOneIncl_inr, fsSurfaceChain_boundary_apply]
          by_cases hst : s = t
          · subst t
            exact hc.internal s z
          · simp [foxMatrix_inr_inr_of_ne ρ bsub hst z]

/-- The supported structural map carries the actual old boundary to the
actual new boundary using the existing coefficient homomorphism. -/
theorem fsCellsF_boundary (c : ∀ s, Mt s →₀ R')
    (hc : IsFillingFS ρ bsub hfill c) (y : (Jr ⊕ Sx) →₀ R₀) :
    coverSecondBoundary (relSub (substPresF ρ bsub)) (substPresF ρ bsub)
        (fsCellsF ρ bsub hfill c y) =
      fsOldOneIncl ((coverSecondBoundary (relSub ρ) ρ y).mapRange
        (coeffF ρ bsub hfill) (map_zero _)) := by
  have h := LinearMap.congr_fun (fsCellsBase_chainMap ρ bsub hfill c hc)
    (y.mapRange (coeffF ρ bsub hfill) (map_zero _))
  change _ = fsOldOneIncl (fsFoxPushBoundary ρ bsub hfill
    (y.mapRange (coeffF ρ bsub hfill) (map_zero _))) at h
  rw [fsFoxPushBoundary, fsRingMapBoundary_mapRange] at h
  exact h

/-- Under B1, every cycle preimage constructed by block-local B2 is an
actual cycle for the base-changed old Fox boundary. -/
theorem fsCycle_preimage (c : ∀ s, Mt s →₀ R')
    (hc : IsFillingFS ρ bsub hfill c)
    (hblock : BlockSurfaceGeneratesFS ρ bsub c)
    (x : (Jr ⊕ (Σ s, Mt s)) →₀ R')
    (hx : coverSecondBoundary (relSub (substPresF ρ bsub)) (substPresF ρ bsub) x = 0) :
    ∃ y : (Jr ⊕ Sx) →₀ R', fsFoxPushBoundary ρ bsub hfill y = 0 ∧
      fsCellsBase c y = x := by
  obtain ⟨y, hy, _, _⟩ := fsCellsBase_preimage_of_internal_zero ρ bsub c hblock x
    (fun s z => congrArg (fun v => v (Sum.inr ⟨s, z⟩)) hx)
  refine ⟨y, ?_, hy⟩
  apply fsOldOneIncl_injective (Z := Σ s, Zt s)
  rw [map_zero]
  have h := LinearMap.congr_fun (fsCellsBase_chainMap ρ bsub hfill c hc) y
  change coverSecondBoundary (relSub (substPresF ρ bsub)) (substPresF ρ bsub)
    (fsCellsBase c y) = fsOldOneIncl (fsFoxPushBoundary ρ bsub hfill y) at h
  rw [hy, hx] at h
  exact h.symm

/-- Full arbitrary-family generation by actual original-group cycles. The
only remaining inputs are the geometric B1 filling, block-local B2, and the
already separately constructed injection of presentation groups. -/
theorem fsGenerates_familySubst (c : ∀ s, Mt s →₀ R')
    (hc : IsFillingFS ρ bsub hfill c)
    (hblock : BlockSurfaceGeneratesFS ρ bsub c)
    (hinj : Function.Injective (substHomF ρ bsub hfill))
    (x : (Jr ⊕ (Σ s, Mt s)) →₀ R')
    (hx : coverSecondBoundary (relSub (substPresF ρ bsub)) (substPresF ρ bsub) x = 0) :
    x ∈ Submodule.span R'
      {v : (Jr ⊕ (Σ s, Mt s)) →₀ R' | ∃ y : (Jr ⊕ Sx) →₀ R₀,
        coverSecondBoundary (relSub ρ) ρ y = 0 ∧ v = fsCellsF ρ bsub hfill c y} := by
  obtain ⟨y, hy, hxy⟩ := fsCycle_preimage ρ bsub hfill c hc hblock x hx
  have hmem := fs_cycle_mem_span_groupMap_cycles (substHomF ρ bsub hfill) hinj
    (fun k => coverFoxGradient (relSub ρ) (ρ k)) y hy
  rw [← hxy]
  clear hy hxy
  induction hmem using Submodule.span_induction with
  | mem v hv =>
      obtain ⟨a, ha, rfl⟩ := hv
      apply Submodule.subset_span
      exact ⟨a, ha, rfl⟩
  | zero =>
      rw [map_zero]
      exact Submodule.zero_mem _
  | add v w hv hw hv' hw' =>
      rw [map_add]
      exact Submodule.add_mem _ hv' hw'
  | smul a v hv hv' =>
      rw [map_smul]
      exact Submodule.smul_mem _ a hv'

end Substitution

end BlockFamily
end FiniteChains
