module

public import RequestProject.ChamberQuotientOldStar
public import RequestProject.ChamberQuotientNerveGeneration
public import RequestProject.NerveIntersectionGeneration

@[expose] public section

/-! Old-block cycles in the actual universal cover are generated by the attaching locus. -/
namespace FiniteChains.Davis
open RACG Mirror Comb Nerve
universe u
variable {V : Type u} [DecidableEq V] [Fintype V] {A : CommRel V}
  {X : Type u} [PartialOrder X] {att : NeSpx A →o X}

/-- Both the residual cycle and its finite correction are supported in old cells.
The residual cycle lies on positive old cubes, the actual attaching locus.
Ambient generation and the unmixed decomposition are proved, not additional inputs. -/
theorem qUniversal_old_generates_positive (x : X) (hx : IsConnected (orderCx X)) :
    GeneratesDegreeIn
      (fun p : UOrder (Qpos A X att) (qNew x) => InQOld (uOrderEnd p))
      (fun p => InQOld (uOrderEnd p) ∧ InQBaseStar (uOrderEnd p)) 3 := by
  apply generatesDegreeIn_intersection_of_ambient (U := fun _ => True)
    (fun _ _ => trivial)
    (fun a b hab _ _ => qOld_baseStar_unmixed _ _ (uOrderEnd_monotone hab))
  intro z hz hd hcyc
  obtain ⟨c, hc, y, hy, hcc, he⟩ := qUniversal_generatesDegreeIn_base x hx z hz hd hcyc
  exact ⟨c, incOn_mono (fun _ h => inQBase_in_star h) hc, y, hy, hcc, he⟩

end FiniteChains.Davis
