module

public import RequestProject.ChamberZCoverCellularGeneration
public import RequestProject.StrictSubposetChains
public import RequestProject.OrderComponentLabels
public import RequestProject.StrictLabelCycleDecomposition

@[expose] public section

/-! Global covering cycles are generated by genuine cycles in finitely many
actual path components of the lifted inserted base. -/
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains.Davis
open RACG Mirror Comb
universe u
variable {V : Type u} [DecidableEq V] [Fintype V] {A : CommRel V}
  {X : Type u} [PartialOrder X] [Nonempty X]
  {M : CayGroup A → Prop} {att : NeSpx A →o X}
  {P : Type u} [PartialOrder P] {f : P → Zpos A X M att}

abbrev CoverZBase (f : P → Zpos A X M att) := {p : P // InZBase (f p)}

def coverZBaseTriangleMap (f : P → Zpos A X M att) :
    StrictOrdTri (CoverZBase f) → StrictOrdTri P :=
  fun t => ⟨(t.1.1.1, t.1.2.1.1, t.1.2.2.1), t.2⟩

theorem exists_cover_base_component_cycles (hf : IsPosetCover f)
    (z : StrictOrdTri P →₀ ℤ) (hz : Comb.bdry2 (strictOrderCx P) z = 0) :
    ∃ (s : Finset (OrderComponent (CoverZBase f)))
      (d : OrderComponent (CoverZBase f) → (StrictOrdTri (CoverZBase f) →₀ ℤ)),
      (∀ i, Comb.bdry2 (strictOrderCx (CoverZBase f)) (d i) = 0) ∧
      (∀ i t, t ∈ (d i).support →
        orderComponentLabel (CoverZBase f) t.1.1 = i ∧
        orderComponentLabel (CoverZBase f) t.1.2.1 = i ∧
        orderComponentLabel (CoverZBase f) t.1.2.2 = i) ∧
      ∃ y : StrictOrdTet P →₀ ℤ,
        z = (∑ i ∈ s, Finsupp.mapDomain (coverZBaseTriangleMap f) (d i)) +
          strictOrdBoundary3 y := by
  classical
  obtain ⟨c, hc, hcc, y, he⟩ := exists_cover_base_strict_cellular_cycle hf z hz
  let S : Set P := {p | InZBase (f p)}
  obtain ⟨c', hc', hcc'⟩ := exists_strictSubposet_cycle S c hc hcc
  obtain ⟨s, d, hd, hds, hsum⟩ := exists_strict_label_cycle_decomposition
    (orderComponentLabel S) (fun {_ _} h => orderComponentLabel_eq_of_le h) c' hcc'
  refine ⟨s, d, hd, hds, y, ?_⟩
  have hmap : (∑ i ∈ s, Finsupp.mapDomain (coverZBaseTriangleMap f) (d i)) = c := by
    change (∑ i ∈ s, chain2 (strictSubposetIncl S) (d i)) = c
    rw (config := { transparency := .default }) [← map_sum, ← hsum, hc']
  exact he.trans (congrArg (fun w : StrictOrdTri P →₀ ℤ =>
    w + strictOrdBoundary3 y) hmap.symm)

end FiniteChains.Davis
