import RequestProject.RACGMedian

/-!
# Right descents, special subgroups and the chamber intersection formula

This file formalises the first step of the chamber proof of the block properties: the
combinatorial description of the intersection of a chamber of the Davis complex with the union
of the earlier chambers.

Recall the geometric picture.  The Davis complex of the right-angled Coxeter group `W = W_L` is
built from copies `F_w` (`w ∈ W`) of the chamber `F = Cone(|sd L|)`, two copies `F_w` and
`F_{w'}` being glued along the points whose *mirror type* `T` (a simplex of `L`) satisfies
`w⁻¹ w' ∈ W_T`.  Thus, if the elements of `W` are enumerated by nondecreasing length, the
statement

  `F_w ∩ ⋃_{ℓ(w') ≤ ℓ(w), w' ≠ w} F_{w'} = ⋃_{s ∈ D(w)} (F_s)_w`,  `D(w) = {s : ℓ(ws) < ℓ(w)}`,

is *exactly* the following group-theoretic statement, proved here without any reference to
topology:

* some `w' ≠ w` with `ℓ(w') ≤ ℓ(w)` lies in the coset `w W_T`
  ↔ `T ∩ D(w) ≠ ∅`  (`FiniteChains.RACG.exists_rdesc_iff_exists_earlier`).

The ingredients, all proved here for the model of `RequestProject/RACGGroup.lean`:

* `FiniteChains.RACG.IsRDesc` — the right descent relation `ℓ(ws) < ℓ(w)`, and its translation
  `FiniteChains.RACG.isRDesc_iff_isDesc` into the left descents of the existing development;
* `FiniteChains.RACG.Commuting` — a set of generators spanning a simplex of `L`, i.e. a clique
  of the commutation graph;
* `FiniteChains.RACG.specialSub` — the special subgroup `W_T`, together with its normal form
  `FiniteChains.RACG.exists_nodup_cword` (`W_T ≅ (ℤ/2)^T`: every element is the product of a
  duplicate-free list of generators from `T`);
* `FiniteChains.RACG.clen_mul_eq_of_no_rdesc` — if `w` has no right descent in `T` then
  `ℓ(wu) = ℓ(w) + ℓ(u)` for `u ∈ W_T`; hence `w` is the **unique** shortest element of `w W_T`
  (`FiniteChains.RACG.existsUnique_shortest_coset`,
  `FiniteChains.RACG.shortest_iff_no_rdesc`);
* `FiniteChains.RACG.rdesc_rel` and `FiniteChains.RACG.exists_rdesc` — the descent set `D(w)`
  is a simplex of `L`, and is nonempty for `w ≠ 1`.
-/

namespace FiniteChains
namespace RACG

universe u

variable {V : Type u} [DecidableEq V] (A : CommRel V)

/-! ### Right descents -/

/-- `s` is a **right descent** of `x`: multiplying by `s` on the right shortens `x`.  This is
the set `D(w) = {s : ℓ(ws) < ℓ(w)}` of the chamber argument. -/
def IsRDesc (x : CayGroup A) (s : V) : Prop := clen A (x * gen A s) < clen A x

theorem clen_mul_gen (x : CayGroup A) (s : V) :
    clen A (x * gen A s) = clen A (gen A s * x⁻¹) := by
  have h : (x * gen A s)⁻¹ = gen A s * x⁻¹ := by
    rw [mul_inv_rev, gen_inv]
  rw [← clen_inv A (x * gen A s), h]

/-- Right descents of `x` are the left descents of `x⁻¹`. -/
theorem isRDesc_iff_isDesc (x : CayGroup A) (s : V) : IsRDesc A x s ↔ IsDesc A x⁻¹ s := by
  unfold IsRDesc IsDesc
  rw [clen_mul_gen A x s, clen_inv A x]

/-- **The descent set is a simplex of `L`**: two distinct right descents commute. -/
theorem rdesc_rel {x : CayGroup A} {s r : V} (hsr : s ≠ r) (hs : IsRDesc A x s)
    (hr : IsRDesc A x r) : A.rel s r :=
  desc_rel A hsr ((isRDesc_iff_isDesc A x s).1 hs) ((isRDesc_iff_isDesc A x r).1 hr)

/-- **The descent set is nonempty** for `x ≠ 1`. -/
theorem exists_rdesc {x : CayGroup A} (hx : x ≠ 1) : ∃ s : V, IsRDesc A x s := by
  obtain ⟨s, hs⟩ := exists_desc A (x := x⁻¹) (by simpa using hx)
  exact ⟨s, (isRDesc_iff_isDesc A x s).2 hs⟩

/-! ### Simplices of `L` and their special subgroups -/

/-- A set of generators spanning a simplex of the flag complex `L`: its elements pairwise
commute. -/
def Commuting (T : Set V) : Prop := ∀ ⦃s⦄, s ∈ T → ∀ ⦃r⦄, r ∈ T → s ≠ r → A.rel s r

/-- The special subgroup `W_T`, generated by the generators indexed by `T`. -/
noncomputable def specialSub (T : Set V) : Subgroup (CayGroup A) :=
  Subgroup.closure (gen A '' T)

theorem gen_mem_specialSub {T : Set V} {s : V} (hs : s ∈ T) : gen A s ∈ specialSub A T :=
  Subgroup.subset_closure ⟨s, hs, rfl⟩

/-- Two commuting generators commute in the group. -/
theorem gen_comm {s r : V} (h : A.rel s r) : gen A s * gen A r = gen A r * gen A s := by
  have h1 : gen A s * gen A r = cword A [s, r] := by simp
  have h2 : gen A r * gen A s = cword A [r, s] := by simp
  rw [h1, h2]
  exact cword_ceq A (CEq.of_swap (Swap.head h []))

theorem cword_mem_specialSub {T : Set V} {l : List V} (hl : ∀ a ∈ l, a ∈ T) :
    cword A l ∈ specialSub A T := by
  induction l with
  | nil => simp
  | cons a t ih =>
      rw [cword_cons]
      exact Subgroup.mul_mem _ (gen_mem_specialSub A (hl a (by simp)))
        (ih fun b hb => hl b (by simp [hb]))

/-- Every element of `W_T` is the product of a list of generators from `T`. -/
theorem exists_cword_of_mem_specialSub {T : Set V} {u : CayGroup A} (hu : u ∈ specialSub A T) :
    ∃ l : List V, (∀ a ∈ l, a ∈ T) ∧ cword A l = u := by
  classical
  refine Subgroup.closure_induction (p := fun v _ => ∃ l : List V, (∀ a ∈ l, a ∈ T) ∧
    cword A l = v) ?_ ?_ ?_ ?_ hu
  · rintro v ⟨s, hs, rfl⟩
    exact ⟨[s], by simpa using hs, by simp⟩
  · exact ⟨[], by simp, by simp⟩
  · rintro v w _ _ ⟨l, hl, rfl⟩ ⟨m, hm, rfl⟩
    refine ⟨l ++ m, ?_, ?_⟩
    · intro a ha
      rcases List.mem_append.1 ha with h | h
      exacts [hl a h, hm a h]
    · exact Subtype.ext (by simpa using wordPerm_append A l m)
  · rintro v _ ⟨l, hl, rfl⟩
    refine ⟨l.reverse, ?_, ?_⟩
    · intro a ha; exact hl a (List.mem_reverse.1 ha)
    · exact Subtype.ext (by simpa using wordPerm_reverse A l)

omit [DecidableEq V] in
/-- If a letter can be moved to the front of a word, then it occurs in that word. -/
theorem mem_of_canStart {Cm : V → V → Prop} {s : V} :
    ∀ {l : List V}, canStart Cm s l → s ∈ l := by
  intro l
  induction l with
  | nil => intro h; exact absurd h (by simp)
  | cons a t ih =>
      intro h
      rcases h with h | ⟨-, h⟩
      · simp [h]
      · exact List.mem_cons_of_mem _ (ih h)

omit [DecidableEq V] in
/-- A duplicate-free word is reduced: no letter can be moved to the front to meet an equal
letter, since no letter occurs twice. -/
theorem isRed_of_nodup {l : List V} (hnd : l.Nodup) : IsRed A.rel l := by
  induction l with
  | nil => simp
  | cons a t ih =>
      refine ⟨ih hnd.of_cons, ?_⟩
      intro hcs
      exact (List.nodup_cons.1 hnd).1 (mem_of_canStart hcs)

/-- Cancelling a generator inside a duplicate-free word of pairwise commuting letters. -/
theorem gen_mul_cword_erase {T : Set V} (hT : Commuting A T) {s : V} (hs : s ∈ T) :
    ∀ l : List V, (∀ a ∈ l, a ∈ T) → l.Nodup → s ∈ l →
      gen A s * cword A l = cword A (l.erase s) := by
  intro l
  induction l with
  | nil => intro _ _ h; exact absurd h (by simp)
  | cons a t ih =>
      intro hl hnd hmem
      by_cases hat : a = s
      · subst hat
        simp [cword_cons, ← mul_assoc, gen_mul_gen]
      · have hst : s ∈ t := by
          rcases List.mem_cons.1 hmem with h | h
          · exact absurd h.symm hat
          · exact h
        have hrel : A.rel s a := hT hs (hl a (by simp)) (fun h => hat h.symm)
        have iht := ih (fun b hb => hl b (by simp [hb])) hnd.of_cons hst
        calc gen A s * cword A (a :: t)
            = (gen A s * gen A a) * cword A t := by rw [cword_cons, mul_assoc]
          _ = gen A a * (gen A s * cword A t) := by rw [gen_comm A hrel, mul_assoc]
          _ = gen A a * cword A (t.erase s) := by rw [iht]
          _ = cword A (a :: t.erase s) := (cword_cons A _ _).symm
          _ = cword A ((a :: t).erase s) := by rw [List.erase_cons_tail (by simpa using hat)]

/-- **Normal form in `W_T ≅ (ℤ/2)^T`**: every element of the special subgroup of a simplex is
the product of a duplicate-free list of its generators. -/
theorem exists_nodup_cword {T : Set V} (hT : Commuting A T) {u : CayGroup A}
    (hu : u ∈ specialSub A T) :
    ∃ l : List V, (∀ a ∈ l, a ∈ T) ∧ l.Nodup ∧ cword A l = u := by
  classical
  obtain ⟨l, hl, rfl⟩ := exists_cword_of_mem_specialSub A hu
  clear hu
  induction l with
  | nil => exact ⟨[], by simp, by simp, rfl⟩
  | cons a t ih =>
      obtain ⟨m, hm, hnd, hmt⟩ := ih fun b hb => hl b (by simp [hb])
      have ha : a ∈ T := hl a (by simp)
      by_cases hmem : a ∈ m
      · refine ⟨m.erase a, fun b hb => hm b (List.mem_of_mem_erase hb), hnd.erase a, ?_⟩
        rw [← gen_mul_cword_erase A hT ha m hm hnd hmem, hmt, cword_cons]
      · refine ⟨a :: m, ?_, by simpa using ⟨hmem, hnd⟩, by rw [cword_cons, hmt, cword_cons]⟩
        intro b hb
        rcases List.mem_cons.1 hb with h | h
        · exact h ▸ ha
        · exact hm b h

/-! ### Elements without descents in a simplex -/

/-- If no generator of the simplex `T` shortens `x` from the left, then no generator of `T`
missing from a word over `T` shortens the product from the left either. -/
theorem not_isDesc_cword_mul {T : Set V} (hT : Commuting A T) {x : CayGroup A}
    (hx : ∀ s ∈ T, ¬ IsDesc A x s) {s : V} (hs : s ∈ T) :
    ∀ l : List V, (∀ a ∈ l, a ∈ T) → s ∉ l → ¬ IsDesc A (cword A l * x) s := by
  intro l
  induction l with
  | nil => intro _ _; simpa using hx s hs
  | cons a t ih =>
      intro hl hsl
      have hat : a ≠ s := fun h => hsl (by simp [h])
      have hrel : A.rel s a := hT hs (hl a (by simp)) (fun h => hat h.symm)
      have iht := ih (fun b hb => hl b (by simp [hb])) (fun h => hsl (by simp [h]))
      intro hcon
      rw [cword_cons, mul_assoc] at hcon
      exact iht (by simpa [gen_mul_gen_mul] using desc_gen_mul_of_rel A hrel hcon)

/-- **Lengths add**: if no generator of `T` shortens `x` from the left, then the length of
`u * x` is the sum of the lengths, for `u ∈ W_T` written as a duplicate-free word. -/
theorem clen_cword_mul {T : Set V} (hT : Commuting A T) {x : CayGroup A}
    (hx : ∀ s ∈ T, ¬ IsDesc A x s) :
    ∀ l : List V, (∀ a ∈ l, a ∈ T) → l.Nodup →
      clen A (cword A l * x) = l.length + clen A x := by
  intro l
  induction l with
  | nil => intro _ _; simp
  | cons a t ih =>
      intro hl hnd
      have iht := ih (fun b hb => hl b (by simp [hb])) hnd.of_cons
      have hnot : ¬ IsDesc A (cword A t * x) a :=
        not_isDesc_cword_mul A hT hx (hl a (by simp)) t
          (fun b hb => hl b (by simp [hb])) (by simpa using (List.nodup_cons.1 hnd).1)
      have hstep := clen_gen_mul_of_not_desc A hnot
      rw [cword_cons, mul_assoc, hstep, iht]
      simp [Nat.add_right_comm]

theorem clen_lt_of_mem_specialSub_left {T : Set V} (hT : Commuting A T) {x : CayGroup A}
    (hx : ∀ s ∈ T, ¬ IsDesc A x s) {u : CayGroup A} (hu : u ∈ specialSub A T) (hu1 : u ≠ 1) :
    clen A x < clen A (u * x) := by
  obtain ⟨l, hl, hnd, rfl⟩ := exists_nodup_cword A hT hu
  have hlen : l ≠ [] := by
    rintro rfl
    exact hu1 (cword_nil A)
  have hsum := clen_cword_mul A hT hx l hl hnd
  have hpos : 0 < l.length := List.length_pos_iff.2 hlen
  omega

/-- The right-handed form: if no generator of the simplex `T` shortens `x` from the right, then
every nontrivial `u ∈ W_T` lengthens `x` on the right. -/
theorem clen_lt_of_mem_specialSub {T : Set V} (hT : Commuting A T) {x : CayGroup A}
    (hx : ∀ s ∈ T, ¬ IsRDesc A x s) {u : CayGroup A} (hu : u ∈ specialSub A T) (hu1 : u ≠ 1) :
    clen A x < clen A (x * u) := by
  have hx' : ∀ s ∈ T, ¬ IsDesc A x⁻¹ s := fun s hs hcon =>
    hx s hs ((isRDesc_iff_isDesc A x s).2 hcon)
  have hu' : u⁻¹ ∈ specialSub A T := Subgroup.inv_mem _ hu
  have hu1' : u⁻¹ ≠ 1 := inv_ne_one.2 hu1
  have h := clen_lt_of_mem_specialSub_left A hT hx' hu' hu1'
  have heq : clen A (u⁻¹ * x⁻¹) = clen A (x * u) := by
    rw [← clen_inv A (x * u), mul_inv_rev]
  rwa [heq, clen_inv A x] at h

/-- **Lengths add, on the right**: `ℓ(xu) = ℓ(x) + ℓ(u)` when `x` has no right descent in the
simplex `T` and `u ∈ W_T`. -/
theorem clen_mul_eq_of_no_rdesc {T : Set V} (hT : Commuting A T) {x : CayGroup A}
    (hx : ∀ s ∈ T, ¬ IsRDesc A x s) {u : CayGroup A} (hu : u ∈ specialSub A T) :
    clen A (x * u) = clen A x + clen A u := by
  have hx' : ∀ s ∈ T, ¬ IsDesc A x⁻¹ s := fun s hs hcon =>
    hx s hs ((isRDesc_iff_isDesc A x s).2 hcon)
  obtain ⟨l, hl, hnd, hlu⟩ := exists_nodup_cword A hT hu
  have hrev : ∀ a ∈ l.reverse, a ∈ T := fun a ha => hl a (List.mem_reverse.1 ha)
  have hndrev : l.reverse.Nodup := List.nodup_reverse.2 hnd
  have hsum := clen_cword_mul A hT hx' l.reverse hrev hndrev
  have hinv : cword A l.reverse = u⁻¹ := by
    have : cword A l.reverse = (cword A l)⁻¹ :=
      Subtype.ext (by simpa using wordPerm_reverse A l)
    rw [this, hlu]
  have hlenu : clen A u = l.length := by
    rw [← hlu, clen_cword A (isRed_of_nodup A hnd)]
  have hxu : clen A (x * u) = clen A (u⁻¹ * x⁻¹) := by
    rw [← clen_inv A (x * u), mul_inv_rev]
  rw [hxu, ← hinv, hsum, clen_inv A x, hlenu, List.length_reverse, Nat.add_comm]

/-! ### The chamber intersection formula -/

/-- If some element `y ≠ x` of the coset `x W_T` is not longer than `x`, then `T` meets the
descent set `D(x)`. -/
theorem exists_rdesc_of_earlier {T : Set V} (hT : Commuting A T) {x y : CayGroup A}
    (hy : x⁻¹ * y ∈ specialSub A T) (hne : y ≠ x) (hle : clen A y ≤ clen A x) :
    ∃ s ∈ T, IsRDesc A x s := by
  by_contra hcon
  push_neg at hcon
  have hu1 : x⁻¹ * y ≠ 1 := fun h => hne (inv_mul_eq_one.1 h).symm
  have hlt := clen_lt_of_mem_specialSub A hT hcon hy hu1
  rw [mul_inv_cancel_left] at hlt
  omega

/-- Conversely, a descent `s ∈ T ∩ D(x)` produces the strictly shorter element `x s` of the
coset `x W_T`. -/
theorem earlier_of_rdesc {T : Set V} {x : CayGroup A} {s : V} (hs : s ∈ T)
    (h : IsRDesc A x s) :
    x⁻¹ * (x * gen A s) ∈ specialSub A T ∧ x * gen A s ≠ x ∧
      clen A (x * gen A s) < clen A x := by
  have hlt : clen A (x * gen A s) < clen A x := h
  refine ⟨by simpa using gen_mem_specialSub A hs, ?_, hlt⟩
  intro hcon
  rw [hcon] at hlt
  omega

/-- **The chamber intersection formula.**  For a simplex `T` of `L`, the chamber `F_x` meets an
earlier chamber (one of length at most `ℓ(x)`, and different from `F_x`) in a point of mirror
type `T` exactly when `T` meets the descent set `D(x) = {s : ℓ(xs) < ℓ(x)}`. -/
theorem exists_rdesc_iff_exists_earlier {T : Set V} (hT : Commuting A T) (x : CayGroup A) :
    (∃ y : CayGroup A, x⁻¹ * y ∈ specialSub A T ∧ y ≠ x ∧ clen A y ≤ clen A x) ↔
      ∃ s ∈ T, IsRDesc A x s := by
  constructor
  · rintro ⟨y, hy, hne, hle⟩
    exact exists_rdesc_of_earlier A hT hy hne hle
  · rintro ⟨s, hs, hsd⟩
    obtain ⟨h1, h2, h3⟩ := earlier_of_rdesc A hs hsd
    exact ⟨x * gen A s, h1, h2, le_of_lt h3⟩

/-! ### The shortest element of a coset -/

/-- **`x` is the shortest element of `x W_T` exactly when `T ∩ D(x) = ∅`.** -/
theorem shortest_iff_no_rdesc {T : Set V} (hT : Commuting A T) (x : CayGroup A) :
    (∀ y : CayGroup A, x⁻¹ * y ∈ specialSub A T → clen A x ≤ clen A y) ↔
      ∀ s ∈ T, ¬ IsRDesc A x s := by
  constructor
  · intro h s hs hsd
    obtain ⟨h1, -, h3⟩ := earlier_of_rdesc A hs hsd
    exact absurd (h _ h1) (by omega)
  · intro h y hy
    by_cases hxy : y = x
    · simp [hxy]
    · have hu1 : x⁻¹ * y ≠ 1 := fun hc => hxy (inv_mul_eq_one.1 hc).symm
      have hlt := clen_lt_of_mem_specialSub A hT h hy hu1
      rw [mul_inv_cancel_left] at hlt
      omega

/-- Membership in the coset `x W_T` only depends on the coset. -/
theorem mem_coset_congr {T : Set V} {x y : CayGroup A} (hxy : x⁻¹ * y ∈ specialSub A T)
    (z : CayGroup A) : y⁻¹ * z ∈ specialSub A T ↔ x⁻¹ * z ∈ specialSub A T := by
  constructor
  · intro h
    have hz : x⁻¹ * z = (x⁻¹ * y) * (y⁻¹ * z) := by group
    rw [hz]
    exact Subgroup.mul_mem _ hxy h
  · intro h
    have hz : y⁻¹ * z = (x⁻¹ * y)⁻¹ * (x⁻¹ * z) := by group
    rw [hz]
    exact Subgroup.mul_mem _ (Subgroup.inv_mem _ hxy) h

/-- **Uniqueness of the shortest element of a coset.**  Every coset `x W_T` of the special
subgroup of a simplex contains exactly one element with no right descent in `T`. -/
theorem existsUnique_shortest_coset {T : Set V} (hT : Commuting A T) (x : CayGroup A) :
    ∃! y : CayGroup A, x⁻¹ * y ∈ specialSub A T ∧ ∀ s ∈ T, ¬ IsRDesc A y s := by
  classical
  have hne : ∃ n : ℕ, ∃ y : CayGroup A, x⁻¹ * y ∈ specialSub A T ∧ clen A y = n :=
    ⟨clen A x, x, by rw [inv_mul_cancel]; exact Subgroup.one_mem _, rfl⟩
  obtain ⟨y, hyc, hymin⟩ :
      ∃ y : CayGroup A, x⁻¹ * y ∈ specialSub A T ∧
        ∀ z : CayGroup A, x⁻¹ * z ∈ specialSub A T → clen A y ≤ clen A z := by
    obtain ⟨y, hy, hylen⟩ := Nat.find_spec hne
    refine ⟨y, hy, fun z hz => ?_⟩
    have hfind : Nat.find hne ≤ clen A z := Nat.find_le ⟨z, hz, rfl⟩
    omega
  have hyd : ∀ s ∈ T, ¬ IsRDesc A y s :=
    (shortest_iff_no_rdesc A hT y).1
      (fun z hz => hymin z ((mem_coset_congr A hyc z).1 hz))
  refine ⟨y, ⟨hyc, hyd⟩, ?_⟩
  rintro z ⟨hzc, hzd⟩
  have hyz : y⁻¹ * z ∈ specialSub A T := (mem_coset_congr A hyc z).2 hzc
  have hzy : z⁻¹ * y ∈ specialSub A T := by
    have := Subgroup.inv_mem _ hyz
    rwa [mul_inv_rev, inv_inv] at this
  by_contra hne'
  have h1 : y⁻¹ * z ≠ 1 := fun hc => hne' (inv_mul_eq_one.1 hc).symm
  have h2 : z⁻¹ * y ≠ 1 := fun hc => hne' (inv_mul_eq_one.1 hc)
  have hlt1 := clen_lt_of_mem_specialSub A hT hyd hyz h1
  have hlt2 := clen_lt_of_mem_specialSub A hT hzd hzy h2
  rw [mul_inv_cancel_left] at hlt1 hlt2
  omega

end RACG
end FiniteChains
