module

public import RequestProject.ChamberZUniversalCycleGeneration
public import RequestProject.UniversalCoverCoverMap
public import RequestProject.UniversalOrderThreeNaturality
public import RequestProject.ChamberQuotientCover
public import RequestProject.StrictChamberInjection

@[expose] public section

/-! Genuine universal-cover two-cycle generation in the quotient chamber model. -/
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains.Davis
open RACG Mirror Comb
universe u
variable {V : Type u} [DecidableEq V] [Fintype V] {A : CommRel V}
  {X : Type u} [PartialOrder X] [Nonempty X] {att : NeSpx A →o X}

def InQBase (q : Qpos A X att) : Prop := ∃ x : X, qNew (A := A) (att := att) x = q

omit [Fintype V] [Nonempty X] in
theorem inQBase_zProj {z : Zpos A X (IsGamma A) att} (hz : InZBase z) :
    InQBase (zProj z) := by
  cases z with
  | inl p => exact hz.elim
  | inr wx => exact ⟨wx.2, rfl⟩

/-- The quotient's actual universal-cover cycles are generated by cycles on the
actual inverse image of its inserted base, modulo genuine lifted three-boundaries. -/
theorem exists_qCover_base_cellular_cycle (a : Zpos A X (IsGamma A) att)
    (hconn : IsConnected (orderCx (Zpos A X (IsGamma A) att)))
    (z : UF (orderCx (Qpos A X att)) (zProj a) →₀ ℤ)
    (hz : Comb.bdry2 (uCover (orderCx (Qpos A X att)) (zProj a)) z = 0) :
    ∃ c : UF (orderCx (Qpos A X att)) (zProj a) →₀ ℤ,
      (∀ t ∈ c.support, InQBase t.1.2.1.1 ∧ InQBase t.1.2.1.2.1 ∧
        InQBase t.1.2.1.2.2) ∧
      Comb.bdry2 (uCover (orderCx (Qpos A X att)) (zProj a)) c = 0 ∧
      ∃ y : UOrdTet (Qpos A X att) (zProj a) →₀ ℤ, z = c + uOrdBoundary3 y := by
  classical
  let p := orderCxMap (zProj (A := A) (X := X) (att := att)) zProj_monotone
  have hp : IsCovering p := isCovering_orderCxMap_zProj
  obtain ⟨d, ⟨hd, hdc⟩, _⟩ := exists_unique_cycle_lift_of_covering hp a z hz
  obtain ⟨c, hc, hcc, y, he⟩ := exists_uCover_base_cellular_cycle a hconn d hdc
  refine ⟨Finsupp.mapDomain (@univLiftF (orderCx (Zpos A X (IsGamma A) att))
    (orderCx (Qpos A X att)) a p) c, ?_, ?_,
    Finsupp.mapDomain (uOrdTetMap zProj zProj_monotone a) y, ?_⟩
  · intro t ht
    obtain ⟨s, hs, rfl⟩ := Finset.mem_image.mp (Finsupp.mapDomain_support ht)
    obtain ⟨h₀, h₁, h₂⟩ := hc s hs
    exact ⟨inQBase_zProj h₀, inQBase_zProj h₁, inQBase_zProj h₂⟩
  · exact (univLift_cycle_iff_of_covering hp a c).mpr hcc
  · have h := congrArg (chain2 (univLift (orderCx (Zpos A X (IsGamma A) att)) p a)) he
    rw [hd, map_add, univLift_uOrdBoundary3] at h
    exact h

end FiniteChains.Davis
