import Mathlib

/-!
# Step 2 of Proposition 3.11: `π₂` of the pushout is generated by the term upstairs

Proposition 3.11 forms the cellular pushouts `E_i = K ∪_{p : D → K} L_i` and computes their
second homotopy group.  The chains of the pullbacks of the three pieces to the universal
cover of `E_i` sit in a short exact sequence of `ℤ[Λ]`-modules (`Λ = π₁(E_i)`)

  `0 → ⊕_Λ C_*(D) → (⊕_{Λ/H} C_*(D)) ⊕ (⊕_{Λ/J} C_*(L̃_i)) → C_*(Ẽ_i) → 0`,

and, since `H₁(D) = H₂(D) = 0`, the homology sequence gives the isomorphism (3.5)

  `ℤ[H * J_i] ⊗_{ℤ[J_i]} π₂(L_i) ≅ π₂(E_i)`,

which is what the rest of the proof uses: `π₂(E_i)` is generated, over the group ring of
`π₁(E_i)`, by the image of `π₂(L_i)`.

This file proves the algebraic core of that step for the cellular chain complexes of
two-complexes, i.e. for complexes concentrated in degrees `0, 1, 2`.  The key point is that
no homology functor is needed: the argument is a diagram chase which lifts a **two-cycle**
of the quotient complex to a **two-cycle** of the middle complex, using only that the
subcomplex has vanishing first homology (`H₁(D) = 0`) and that the map in degree zero is
injective.

* `FiniteChains.cycle_image_of_exact` — every two-cycle of the quotient complex is the image
  of a two-cycle of the middle complex;
* `FiniteChains.prod_cycle_of_left_cycles_trivial` — if the middle complex splits as a
  product and the left factor has no two-cycles (`H₂(D) = 0`), the lift lives in the right
  factor;
* `FiniteChains.descent_cycles_mem_span` — **the generation statement (3.5)**: if the
  two-cycles of the right factor are spanned by a set `S`, then the two-cycles of the
  quotient complex are spanned by the image of `S`.
-/

namespace FiniteChains

section Descent

variable {R : Type*} [Ring R]
variable {A₂ A₁ A₀ B₂ B₁ B₀ C₂ C₁ : Type*}
  [AddCommGroup A₂] [Module R A₂] [AddCommGroup A₁] [Module R A₁]
  [AddCommGroup A₀] [Module R A₀]
  [AddCommGroup B₂] [Module R B₂] [AddCommGroup B₁] [Module R B₁]
  [AddCommGroup B₀] [Module R B₀]
  [AddCommGroup C₂] [Module R C₂] [AddCommGroup C₁] [Module R C₁]

/-- **A two-cycle of the quotient complex lifts to a two-cycle of the middle complex.**

This is the homological content of step 2 of Proposition 3.11.  The data is a short exact
sequence of chain complexes concentrated in degrees `0, 1, 2`

  `A_* --f--> B_* --g--> C_*`,

of which only the following is used: `g` is surjective in degree two, `f` is injective in
degree zero, the sequence is exact at `B₁`, the composite `g ∘ f` vanishes in degree two,
both `f` and `g` are chain maps, `d₁ ∘ d₂ = 0` in `B`, and the subcomplex `A` has vanishing
first homology (`H₁(D) = 0` in the application). -/
theorem cycle_image_of_exact
    (dA₂ : A₂ →ₗ[R] A₁) (dA₁ : A₁ →ₗ[R] A₀)
    (dB₂ : B₂ →ₗ[R] B₁) (dB₁ : B₁ →ₗ[R] B₀)
    (dC₂ : C₂ →ₗ[R] C₁)
    (f₂ : A₂ →ₗ[R] B₂) (f₁ : A₁ →ₗ[R] B₁) (f₀ : A₀ →ₗ[R] B₀)
    (g₂ : B₂ →ₗ[R] C₂) (g₁ : B₁ →ₗ[R] C₁)
    (hf₀ : Function.Injective f₀)
    (hgf₂ : ∀ a, g₂ (f₂ a) = 0)
    (hexB₁ : ∀ b : B₁, g₁ b = 0 → ∃ a : A₁, f₁ a = b)
    (hg₂ : Function.Surjective g₂)
    (hchainG : ∀ b : B₂, dC₂ (g₂ b) = g₁ (dB₂ b))
    (hchainF₂ : ∀ a : A₂, dB₂ (f₂ a) = f₁ (dA₂ a))
    (hchainF₁ : ∀ a : A₁, dB₁ (f₁ a) = f₀ (dA₁ a))
    (hdB : ∀ b : B₂, dB₁ (dB₂ b) = 0)
    (hA₁ : ∀ a : A₁, dA₁ a = 0 → ∃ a₂ : A₂, dA₂ a₂ = a)
    (c : C₂) (hc : dC₂ c = 0) : ∃ b : B₂, dB₂ b = 0 ∧ g₂ b = c := by
  obtain ⟨b, hb⟩ := hg₂ c
  -- the boundary of the lift comes from the subcomplex
  have hg₁ : g₁ (dB₂ b) = 0 := by rw [← hchainG b, hb, hc]
  obtain ⟨a₁, ha₁⟩ := hexB₁ _ hg₁
  -- it is a one-cycle there
  have hcyc : dA₁ a₁ = 0 := by
    refine hf₀ ?_
    rw [map_zero, ← hchainF₁ a₁, ha₁, hdB b]
  obtain ⟨a₂, ha₂⟩ := hA₁ a₁ hcyc
  refine ⟨b - f₂ a₂, ?_, ?_⟩
  · rw [map_sub, hchainF₂ a₂, ha₂, ha₁, sub_self]
  · rw [map_sub, hgf₂ a₂, sub_zero, hb]

variable {B'₂ B'₁ B''₂ B''₁ : Type*}
  [AddCommGroup B'₂] [Module R B'₂] [AddCommGroup B'₁] [Module R B'₁]
  [AddCommGroup B''₂] [Module R B''₂] [AddCommGroup B''₁] [Module R B''₁]

/-- **The lift lives in the right-hand factor.**  In the application the middle complex is a
product of the chains of the copies of the acyclic complex `D` and of the chains of the
copies of the universal cover of `L_i`; the first factor has no two-cycles because
`H₂(D) = 0`. -/
theorem prod_cycle_of_left_cycles_trivial
    (dB'₂ : B'₂ →ₗ[R] B'₁) (dB''₂ : B''₂ →ₗ[R] B''₁)
    (hB' : ∀ x : B'₂, dB'₂ x = 0 → x = 0)
    (b : B'₂ × B''₂) (hb : (dB'₂.prodMap dB''₂) b = 0) :
    b.1 = 0 ∧ dB''₂ b.2 = 0 := by
  have h1 : dB'₂ b.1 = 0 := congrArg Prod.fst hb
  have h2 : dB''₂ b.2 = 0 := congrArg Prod.snd hb
  exact ⟨hB' _ h1, h2⟩

/-- **Equation (3.5): the second homotopy group of the pushout is generated by the image of
the one upstairs.**  Combining the two previous statements: every two-cycle of the quotient
complex is the image of a two-cycle of the right-hand factor of the middle complex, so a
spanning set of the latter maps to a spanning set of the former. -/
theorem descent_cycles_mem_span
    (dA₂ : A₂ →ₗ[R] A₁) (dA₁ : A₁ →ₗ[R] A₀)
    (dB'₂ : B'₂ →ₗ[R] B'₁) (dB''₂ : B''₂ →ₗ[R] B''₁)
    (dB₁ : B'₁ × B''₁ →ₗ[R] B₀) (dC₂ : C₂ →ₗ[R] C₁)
    (f₂ : A₂ →ₗ[R] B'₂ × B''₂) (f₁ : A₁ →ₗ[R] B'₁ × B''₁) (f₀ : A₀ →ₗ[R] B₀)
    (g₂ : B'₂ × B''₂ →ₗ[R] C₂) (g₁ : B'₁ × B''₁ →ₗ[R] C₁)
    (hf₀ : Function.Injective f₀)
    (hgf₂ : ∀ a, g₂ (f₂ a) = 0)
    (hexB₁ : ∀ b : B'₁ × B''₁, g₁ b = 0 → ∃ a : A₁, f₁ a = b)
    (hg₂ : Function.Surjective g₂)
    (hchainG : ∀ b, dC₂ (g₂ b) = g₁ ((dB'₂.prodMap dB''₂) b))
    (hchainF₂ : ∀ a : A₂, (dB'₂.prodMap dB''₂) (f₂ a) = f₁ (dA₂ a))
    (hchainF₁ : ∀ a : A₁, dB₁ (f₁ a) = f₀ (dA₁ a))
    (hdB : ∀ b, dB₁ ((dB'₂.prodMap dB''₂) b) = 0)
    (hA₁ : ∀ a : A₁, dA₁ a = 0 → ∃ a₂ : A₂, dA₂ a₂ = a)
    (hB' : ∀ x : B'₂, dB'₂ x = 0 → x = 0)
    (S : Set B''₂) (hS : ∀ z : B''₂, dB''₂ z = 0 → z ∈ Submodule.span R S)
    (c : C₂) (hc : dC₂ c = 0) :
    c ∈ Submodule.span R ((fun z : B''₂ => g₂ (0, z)) '' S) := by
  obtain ⟨b, hbcyc, hbc⟩ :=
    cycle_image_of_exact dA₂ dA₁ (dB'₂.prodMap dB''₂) dB₁ dC₂ f₂ f₁ f₀ g₂ g₁
      hf₀ hgf₂ hexB₁ hg₂ hchainG hchainF₂ hchainF₁ hdB hA₁ c hc
  obtain ⟨hb1, hb2⟩ := prod_cycle_of_left_cycles_trivial dB'₂ dB''₂ hB' b hbcyc
  -- the lift is `(0, z)` with `z` a two-cycle of the right-hand factor
  have hb0 : b = (0, b.2) := by
    refine Prod.ext ?_ rfl
    simpa using hb1
  have hmap : c = (g₂.comp (LinearMap.inr R B'₂ B''₂)) b.2 := by
    rw [← hbc]
    conv_lhs => rw [hb0]
    rfl
  rw [hmap]
  have hmapspan : Submodule.map (g₂.comp (LinearMap.inr R B'₂ B''₂)) (Submodule.span R S)
      ≤ Submodule.span R ((fun z : B''₂ => g₂ (0, z)) '' S) := by
    rw [Submodule.map_span]
    refine Submodule.span_mono ?_
    rintro _ ⟨z, hz, rfl⟩
    exact ⟨z, hz, rfl⟩
  exact hmapspan ⟨b.2, hS b.2 hb2, rfl⟩

end Descent

end FiniteChains
