import RequestProject.SL25Table

/-!
# Remark 2: the group of the presentation `A` is `SL(2,5)`

Remark 2 of the paper uses the presentation

  `A = ⟨x, y | x²yx⁻¹y, xy⁴xy⁻¹⟩`,  `G(A) ≅ SL(2,5)`,

whose exponent-sum matrix has determinant `-1`, so that `K(A)` is acyclic
(`RequestProject/ExampleSL25.lean`), while `G(A)` has torsion, so `K(A)` is not aspherical.

This file proves the quoted isomorphism `G(A) ≅ SL(2,5)`, using the 240 coset-table
identities of `RequestProject/SL25Table.lean`.  The two halves are:

* an upper bound `|G| ≤ 120` for *every* group generated by two elements satisfying the
  relators (`surjective_Wv`, `card_le_120`): the 120 coset words cover the group, because
  the table shows the set of their values is stable under right multiplication by the
  generators and their inverses;
* the homomorphism `G(A) → SL(2,5)` sending the generators to two explicit matrices, which
  is injective and surjective because the 120 words already take 120 distinct matrix
  values.

The final statement is `presentedA_mulEquiv_SL25`.  As a consequence `G(A)` has elements of
finite order, for instance `x` has order `6` (`orderOf_x`), which is the property of the
example that Remark 2 actually uses.
-/

set_option maxRecDepth 1000000
set_option maxHeartbeats 4000000

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains
namespace ExampleA

variable {G : Type*} [Group G] {x y : G}

/-- The 120 coset representatives of the enumeration. -/
def Wv (x y : G) : Fin 120 → G := ![(1 : G), (x), (y), (x⁻¹), (y⁻¹), (x * x), (x * y), (x * y⁻¹), (y * x), (y * y), (y * x⁻¹), (x⁻¹ * y), (x⁻¹ * x⁻¹), (x⁻¹ * y⁻¹), (y⁻¹ * x), (y⁻¹ * x⁻¹), (y⁻¹ * y⁻¹), (x * x * x), (x * x * y⁻¹), (x * y * x), (x * y * y), (x * y⁻¹ * x), (x * y⁻¹ * y⁻¹), (y * x * y), (y * x * y⁻¹), (y * y * x), (y * y * y), (y * y * x⁻¹), (y * x⁻¹ * x⁻¹), (y * x⁻¹ * y⁻¹), (x⁻¹ * y * y), (x⁻¹ * y * x⁻¹), (x⁻¹ * x⁻¹ * y), (x⁻¹ * y⁻¹ * x⁻¹), (x⁻¹ * y⁻¹ * y⁻¹), (y⁻¹ * x * x), (y⁻¹ * x * y), (y⁻¹ * x⁻¹ * y), (y⁻¹ * x⁻¹ * y⁻¹), (y⁻¹ * y⁻¹ * x), (y⁻¹ * y⁻¹ * x⁻¹), (y⁻¹ * y⁻¹ * y⁻¹), (x * x * y⁻¹ * y⁻¹), (x * y * x * y), (x * y * x * y⁻¹), (x * y * y * x), (x * y * y * x⁻¹), (x * y⁻¹ * y⁻¹ * x), (x * y⁻¹ * y⁻¹ * x⁻¹), (x * y⁻¹ * y⁻¹ * y⁻¹), (y * x * y * y), (y * x * y⁻¹ * y⁻¹), (y * y * x * y), (y * y * y * x⁻¹), (y * y * x⁻¹ * x⁻¹), (y * y * x⁻¹ * y⁻¹), (y * x⁻¹ * y⁻¹ * x⁻¹), (x⁻¹ * y * y * x), (x⁻¹ * y * y * x⁻¹), (x⁻¹ * y⁻¹ * x⁻¹ * y), (x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹), (y⁻¹ * x * y * x), (y⁻¹ * x⁻¹ * y * y), (y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹), (y⁻¹ * y⁻¹ * x * y), (y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹), (x * x * y⁻¹ * y⁻¹ * x⁻¹), (x * y * x * y * y), (x * y * x * y⁻¹ * y⁻¹), (x * y * y * x * y), (x * y * y * x⁻¹ * x⁻¹), (x * y * y * x⁻¹ * y⁻¹), (x * y⁻¹ * y⁻¹ * x * y), (x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹), (y * x * y * y * x), (y * x * y * y * x⁻¹), (y * x * y⁻¹ * y⁻¹ * x), (y * x * y⁻¹ * y⁻¹ * x⁻¹), (y * y * x * y * y), (y * y * y * x⁻¹ * y⁻¹), (y * y * x⁻¹ * y⁻¹ * x⁻¹), (x⁻¹ * y * y * x * y), (x⁻¹ * y * y * x⁻¹ * y⁻¹), (x⁻¹ * y⁻¹ * x⁻¹ * y * y), (x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹), (y⁻¹ * x * y * x * y), (y⁻¹ * x⁻¹ * y * y * x), (y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹), (y⁻¹ * y⁻¹ * x * y * x), (y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹), (x * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹), (x * y * x * y * y * x), (x * y * x * y⁻¹ * y⁻¹ * x), (x * y * x * y⁻¹ * y⁻¹ * x⁻¹), (x * y * y * x * y * y), (x * y * y * x⁻¹ * y⁻¹ * x⁻¹), (x * y⁻¹ * y⁻¹ * x * y * x), (x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹), (y * x * y * y * x * y), (y * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹), (y * y * x * y * y * x), (y * y * x * y * y * x⁻¹), (x⁻¹ * y * y * x * y * y), (x⁻¹ * y * y * x⁻¹ * y⁻¹ * x⁻¹), (x⁻¹ * y⁻¹ * x⁻¹ * y * y * x), (x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹), (y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹), (y⁻¹ * y⁻¹ * x * y * x * y), (x * y * x * y * y * x * y), (x * y * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹), (x * y * y * x * y * y * x⁻¹), (x * y⁻¹ * y⁻¹ * x * y * x * y), (y * x * y * y * x * y * y), (y * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹), (y * y * x * y * y * x * y), (x⁻¹ * y * y * x * y * y * x), (x⁻¹ * y * y * x * y * y * x⁻¹), (y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹), (x * y * x * y * y * x * y * y), (x * y * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹)]

/-- The action of `x` on cosets. -/
def txv : Fin 120 → Fin 120 := ![1, 5, 8, 0, 14, 17, 19, 21, 7, 25, 2, 15, 3, 6, 35, 4, 39, 12, 32, 18, 45, 28, 47, 48, 41, 24, 37, 9, 10, 23, 57, 11, 33, 13, 43, 31, 61, 40, 36, 53, 16, 54, 59, 66, 49, 44, 20, 56, 22, 70, 74, 76, 77, 26, 27, 52, 29, 38, 30, 60, 34, 58, 86, 85, 88, 64, 42, 91, 92, 93, 46, 69, 96, 72, 73, 50, 80, 51, 100, 62, 55, 87, 81, 104, 67, 103, 65, 63, 79, 107, 83, 90, 95, 68, 98, 71, 75, 111, 109, 89, 99, 78, 115, 82, 84, 108, 105, 101, 116, 97, 94, 110, 114, 117, 119, 106, 102, 118, 112, 113]

/-- The action of `y` on cosets. -/
def tyv : Fin 120 → Fin 120 := ![2, 6, 9, 11, 0, 14, 20, 1, 23, 26, 12, 30, 32, 3, 36, 37, 4, 21, 5, 43, 29, 41, 7, 50, 8, 52, 31, 28, 47, 10, 42, 17, 49, 59, 13, 39, 34, 62, 15, 64, 25, 16, 18, 67, 19, 69, 33, 72, 45, 22, 55, 24, 78, 54, 76, 27, 70, 81, 35, 83, 57, 85, 82, 38, 63, 40, 61, 71, 44, 94, 92, 46, 51, 48, 98, 56, 89, 74, 79, 53, 96, 102, 58, 68, 60, 105, 100, 86, 107, 65, 66, 108, 97, 91, 75, 104, 111, 73, 112, 77, 114, 80, 90, 88, 115, 84, 87, 117, 118, 93, 95, 113, 101, 99, 116, 119, 103, 106, 110, 109]

/-- The action of `x⁻¹` on cosets. -/
def txinv : Fin 120 → Fin 120 := ![3, 0, 10, 12, 15, 1, 13, 8, 2, 27, 28, 31, 17, 33, 4, 11, 40, 5, 19, 6, 46, 7, 48, 29, 25, 9, 53, 54, 21, 56, 58, 35, 18, 32, 60, 14, 38, 26, 57, 16, 37, 24, 66, 34, 45, 20, 70, 22, 23, 44, 75, 77, 55, 39, 41, 80, 47, 30, 61, 42, 59, 36, 79, 87, 65, 86, 43, 84, 93, 71, 49, 95, 73, 74, 50, 96, 51, 52, 101, 88, 76, 82, 103, 90, 104, 63, 62, 81, 64, 99, 91, 67, 68, 69, 110, 92, 72, 109, 94, 100, 78, 107, 116, 85, 83, 106, 115, 89, 105, 98, 111, 97, 118, 119, 112, 102, 108, 113, 117, 114]

/-- The action of `y⁻¹` on cosets. -/
def tyinv : Fin 120 → Fin 120 := ![4, 7, 0, 13, 16, 18, 1, 22, 24, 2, 29, 3, 10, 34, 5, 38, 41, 31, 42, 44, 6, 17, 49, 8, 51, 40, 9, 55, 27, 20, 11, 26, 12, 46, 36, 58, 14, 15, 63, 35, 65, 21, 30, 19, 68, 48, 71, 28, 73, 32, 23, 72, 25, 79, 53, 50, 75, 60, 82, 33, 84, 66, 37, 64, 39, 89, 90, 43, 83, 45, 56, 67, 47, 97, 77, 94, 54, 99, 52, 78, 101, 57, 62, 59, 105, 61, 87, 106, 103, 76, 102, 93, 70, 109, 69, 110, 80, 92, 74, 113, 86, 112, 81, 116, 95, 85, 117, 88, 91, 119, 118, 96, 98, 111, 100, 104, 114, 107, 108, 115]

theorem Wv_zero (x y : G) : Wv x y 0 = 1 := rfl

/-- The coset words are words in the two generators, so any group homomorphism carries the
`i`-th word of one pair of generators to the `i`-th word of its image pair. -/
theorem map_Wv {H : Type*} [Group H] (f : G →* H) (x y : G) (i : Fin 120) :
    f (Wv x y i) = Wv (f x) (f y) i := by
  fin_cases i
  · show f (1) = 1
    simp
  · show f (x) = f x
    simp
  · show f (y) = f y
    simp
  · show f (x⁻¹) = (f x)⁻¹
    simp
  · show f (y⁻¹) = (f y)⁻¹
    simp
  · show f (x * x) = f x * f x
    simp
  · show f (x * y) = f x * f y
    simp
  · show f (x * y⁻¹) = f x * (f y)⁻¹
    simp
  · show f (y * x) = f y * f x
    simp
  · show f (y * y) = f y * f y
    simp
  · show f (y * x⁻¹) = f y * (f x)⁻¹
    simp
  · show f (x⁻¹ * y) = (f x)⁻¹ * f y
    simp
  · show f (x⁻¹ * x⁻¹) = (f x)⁻¹ * (f x)⁻¹
    simp
  · show f (x⁻¹ * y⁻¹) = (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (y⁻¹ * x) = (f y)⁻¹ * f x
    simp
  · show f (y⁻¹ * x⁻¹) = (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (y⁻¹ * y⁻¹) = (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (x * x * x) = f x * f x * f x
    simp
  · show f (x * x * y⁻¹) = f x * f x * (f y)⁻¹
    simp
  · show f (x * y * x) = f x * f y * f x
    simp
  · show f (x * y * y) = f x * f y * f y
    simp
  · show f (x * y⁻¹ * x) = f x * (f y)⁻¹ * f x
    simp
  · show f (x * y⁻¹ * y⁻¹) = f x * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (y * x * y) = f y * f x * f y
    simp
  · show f (y * x * y⁻¹) = f y * f x * (f y)⁻¹
    simp
  · show f (y * y * x) = f y * f y * f x
    simp
  · show f (y * y * y) = f y * f y * f y
    simp
  · show f (y * y * x⁻¹) = f y * f y * (f x)⁻¹
    simp
  · show f (y * x⁻¹ * x⁻¹) = f y * (f x)⁻¹ * (f x)⁻¹
    simp
  · show f (y * x⁻¹ * y⁻¹) = f y * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (x⁻¹ * y * y) = (f x)⁻¹ * f y * f y
    simp
  · show f (x⁻¹ * y * x⁻¹) = (f x)⁻¹ * f y * (f x)⁻¹
    simp
  · show f (x⁻¹ * x⁻¹ * y) = (f x)⁻¹ * (f x)⁻¹ * f y
    simp
  · show f (x⁻¹ * y⁻¹ * x⁻¹) = (f x)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (x⁻¹ * y⁻¹ * y⁻¹) = (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (y⁻¹ * x * x) = (f y)⁻¹ * f x * f x
    simp
  · show f (y⁻¹ * x * y) = (f y)⁻¹ * f x * f y
    simp
  · show f (y⁻¹ * x⁻¹ * y) = (f y)⁻¹ * (f x)⁻¹ * f y
    simp
  · show f (y⁻¹ * x⁻¹ * y⁻¹) = (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (y⁻¹ * y⁻¹ * x) = (f y)⁻¹ * (f y)⁻¹ * f x
    simp
  · show f (y⁻¹ * y⁻¹ * x⁻¹) = (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (y⁻¹ * y⁻¹ * y⁻¹) = (f y)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (x * x * y⁻¹ * y⁻¹) = f x * f x * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (x * y * x * y) = f x * f y * f x * f y
    simp
  · show f (x * y * x * y⁻¹) = f x * f y * f x * (f y)⁻¹
    simp
  · show f (x * y * y * x) = f x * f y * f y * f x
    simp
  · show f (x * y * y * x⁻¹) = f x * f y * f y * (f x)⁻¹
    simp
  · show f (x * y⁻¹ * y⁻¹ * x) = f x * (f y)⁻¹ * (f y)⁻¹ * f x
    simp
  · show f (x * y⁻¹ * y⁻¹ * x⁻¹) = f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (x * y⁻¹ * y⁻¹ * y⁻¹) = f x * (f y)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (y * x * y * y) = f y * f x * f y * f y
    simp
  · show f (y * x * y⁻¹ * y⁻¹) = f y * f x * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (y * y * x * y) = f y * f y * f x * f y
    simp
  · show f (y * y * y * x⁻¹) = f y * f y * f y * (f x)⁻¹
    simp
  · show f (y * y * x⁻¹ * x⁻¹) = f y * f y * (f x)⁻¹ * (f x)⁻¹
    simp
  · show f (y * y * x⁻¹ * y⁻¹) = f y * f y * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (y * x⁻¹ * y⁻¹ * x⁻¹) = f y * (f x)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (x⁻¹ * y * y * x) = (f x)⁻¹ * f y * f y * f x
    simp
  · show f (x⁻¹ * y * y * x⁻¹) = (f x)⁻¹ * f y * f y * (f x)⁻¹
    simp
  · show f (x⁻¹ * y⁻¹ * x⁻¹ * y) = (f x)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * f y
    simp
  · show f (x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹) = (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (y⁻¹ * x * y * x) = (f y)⁻¹ * f x * f y * f x
    simp
  · show f (y⁻¹ * x⁻¹ * y * y) = (f y)⁻¹ * (f x)⁻¹ * f y * f y
    simp
  · show f (y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹) = (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (y⁻¹ * y⁻¹ * x * y) = (f y)⁻¹ * (f y)⁻¹ * f x * f y
    simp
  · show f (y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹) = (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (x * x * y⁻¹ * y⁻¹ * x⁻¹) = f x * f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (x * y * x * y * y) = f x * f y * f x * f y * f y
    simp
  · show f (x * y * x * y⁻¹ * y⁻¹) = f x * f y * f x * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (x * y * y * x * y) = f x * f y * f y * f x * f y
    simp
  · show f (x * y * y * x⁻¹ * x⁻¹) = f x * f y * f y * (f x)⁻¹ * (f x)⁻¹
    simp
  · show f (x * y * y * x⁻¹ * y⁻¹) = f x * f y * f y * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (x * y⁻¹ * y⁻¹ * x * y) = f x * (f y)⁻¹ * (f y)⁻¹ * f x * f y
    simp
  · show f (x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹) = f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (y * x * y * y * x) = f y * f x * f y * f y * f x
    simp
  · show f (y * x * y * y * x⁻¹) = f y * f x * f y * f y * (f x)⁻¹
    simp
  · show f (y * x * y⁻¹ * y⁻¹ * x) = f y * f x * (f y)⁻¹ * (f y)⁻¹ * f x
    simp
  · show f (y * x * y⁻¹ * y⁻¹ * x⁻¹) = f y * f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (y * y * x * y * y) = f y * f y * f x * f y * f y
    simp
  · show f (y * y * y * x⁻¹ * y⁻¹) = f y * f y * f y * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (y * y * x⁻¹ * y⁻¹ * x⁻¹) = f y * f y * (f x)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (x⁻¹ * y * y * x * y) = (f x)⁻¹ * f y * f y * f x * f y
    simp
  · show f (x⁻¹ * y * y * x⁻¹ * y⁻¹) = (f x)⁻¹ * f y * f y * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (x⁻¹ * y⁻¹ * x⁻¹ * y * y) = (f x)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * f y * f y
    simp
  · show f (x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹) = (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (y⁻¹ * x * y * x * y) = (f y)⁻¹ * f x * f y * f x * f y
    simp
  · show f (y⁻¹ * x⁻¹ * y * y * x) = (f y)⁻¹ * (f x)⁻¹ * f y * f y * f x
    simp
  · show f (y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹) = (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (y⁻¹ * y⁻¹ * x * y * x) = (f y)⁻¹ * (f y)⁻¹ * f x * f y * f x
    simp
  · show f (y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹) = (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (x * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹) = f x * f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (x * y * x * y * y * x) = f x * f y * f x * f y * f y * f x
    simp
  · show f (x * y * x * y⁻¹ * y⁻¹ * x) = f x * f y * f x * (f y)⁻¹ * (f y)⁻¹ * f x
    simp
  · show f (x * y * x * y⁻¹ * y⁻¹ * x⁻¹) = f x * f y * f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (x * y * y * x * y * y) = f x * f y * f y * f x * f y * f y
    simp
  · show f (x * y * y * x⁻¹ * y⁻¹ * x⁻¹) = f x * f y * f y * (f x)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (x * y⁻¹ * y⁻¹ * x * y * x) = f x * (f y)⁻¹ * (f y)⁻¹ * f x * f y * f x
    simp
  · show f (x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹) = f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (y * x * y * y * x * y) = f y * f x * f y * f y * f x * f y
    simp
  · show f (y * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹) = f y * f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (y * y * x * y * y * x) = f y * f y * f x * f y * f y * f x
    simp
  · show f (y * y * x * y * y * x⁻¹) = f y * f y * f x * f y * f y * (f x)⁻¹
    simp
  · show f (x⁻¹ * y * y * x * y * y) = (f x)⁻¹ * f y * f y * f x * f y * f y
    simp
  · show f (x⁻¹ * y * y * x⁻¹ * y⁻¹ * x⁻¹) = (f x)⁻¹ * f y * f y * (f x)⁻¹ * (f y)⁻¹ * (f x)⁻¹
    simp
  · show f (x⁻¹ * y⁻¹ * x⁻¹ * y * y * x) = (f x)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * f y * f y * f x
    simp
  · show f (x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹) = (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹) = (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (y⁻¹ * y⁻¹ * x * y * x * y) = (f y)⁻¹ * (f y)⁻¹ * f x * f y * f x * f y
    simp
  · show f (x * y * x * y * y * x * y) = f x * f y * f x * f y * f y * f x * f y
    simp
  · show f (x * y * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹) = f x * f y * f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹
    simp
  · show f (x * y * y * x * y * y * x⁻¹) = f x * f y * f y * f x * f y * f y * (f x)⁻¹
    simp
  · show f (x * y⁻¹ * y⁻¹ * x * y * x * y) = f x * (f y)⁻¹ * (f y)⁻¹ * f x * f y * f x * f y
    simp
  · show f (y * x * y * y * x * y * y) = f y * f x * f y * f y * f x * f y * f y
    simp
  · show f (y * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹) = f y * f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (y * y * x * y * y * x * y) = f y * f y * f x * f y * f y * f x * f y
    simp
  · show f (x⁻¹ * y * y * x * y * y * x) = (f x)⁻¹ * f y * f y * f x * f y * f y * f x
    simp
  · show f (x⁻¹ * y * y * x * y * y * x⁻¹) = (f x)⁻¹ * f y * f y * f x * f y * f y * (f x)⁻¹
    simp
  · show f (y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹) = (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp
  · show f (x * y * x * y * y * x * y * y) = f x * f y * f x * f y * f y * f x * f y * f y
    simp
  · show f (x * y * x * y⁻¹ * y⁻¹ * x⁻¹ * y⁻¹ * y⁻¹) = f x * f y * f x * (f y)⁻¹ * (f y)⁻¹ * (f x)⁻¹ * (f y)⁻¹ * (f y)⁻¹
    simp

theorem txv_txinv (i : Fin 120) : txv (txinv i) = i := by fin_cases i <;> rfl

theorem tyv_tyinv (i : Fin 120) : tyv (tyinv i) = i := by fin_cases i <;> rfl

/-- The `x`-column of the coset table. -/
theorem tab_x (hr : x * x * y * x⁻¹ * y = 1 ∧ x * y * y * y * y * x * y⁻¹ = 1) (i : Fin 120) :
    Wv x y i * x = Wv x y (txv i) := by
  fin_cases i
  · exact mul_inv_eq_one.mp (e_0_x)
  · exact mul_inv_eq_one.mp (e_1_x)
  · exact mul_inv_eq_one.mp (e_2_x)
  · exact mul_inv_eq_one.mp (e_3_x)
  · exact mul_inv_eq_one.mp (e_4_x)
  · exact mul_inv_eq_one.mp (e_5_x)
  · exact mul_inv_eq_one.mp (e_6_x)
  · exact mul_inv_eq_one.mp (e_7_x)
  · exact mul_inv_eq_one.mp (e_8_x hr)
  · exact mul_inv_eq_one.mp (e_9_x)
  · exact mul_inv_eq_one.mp (e_10_x)
  · exact mul_inv_eq_one.mp (e_11_x hr)
  · exact mul_inv_eq_one.mp (e_12_x)
  · exact mul_inv_eq_one.mp (e_13_x hr)
  · exact mul_inv_eq_one.mp (e_14_x)
  · exact mul_inv_eq_one.mp (e_15_x)
  · exact mul_inv_eq_one.mp (e_16_x)
  · exact mul_inv_eq_one.mp (e_17_x hr)
  · exact mul_inv_eq_one.mp (e_18_x hr)
  · exact mul_inv_eq_one.mp (e_19_x hr)
  · exact mul_inv_eq_one.mp (e_20_x)
  · exact mul_inv_eq_one.mp (e_21_x hr)
  · exact mul_inv_eq_one.mp (e_22_x)
  · exact mul_inv_eq_one.mp (e_23_x hr)
  · exact mul_inv_eq_one.mp (e_24_x hr)
  · exact mul_inv_eq_one.mp (e_25_x hr)
  · exact mul_inv_eq_one.mp (e_26_x hr)
  · exact mul_inv_eq_one.mp (e_27_x)
  · exact mul_inv_eq_one.mp (e_28_x)
  · exact mul_inv_eq_one.mp (e_29_x hr)
  · exact mul_inv_eq_one.mp (e_30_x)
  · exact mul_inv_eq_one.mp (e_31_x)
  · exact mul_inv_eq_one.mp (e_32_x hr)
  · exact mul_inv_eq_one.mp (e_33_x)
  · exact mul_inv_eq_one.mp (e_34_x hr)
  · exact mul_inv_eq_one.mp (e_35_x hr)
  · exact mul_inv_eq_one.mp (e_36_x)
  · exact mul_inv_eq_one.mp (e_37_x hr)
  · exact mul_inv_eq_one.mp (e_38_x hr)
  · exact mul_inv_eq_one.mp (e_39_x hr)
  · exact mul_inv_eq_one.mp (e_40_x)
  · exact mul_inv_eq_one.mp (e_41_x hr)
  · exact mul_inv_eq_one.mp (e_42_x hr)
  · exact mul_inv_eq_one.mp (e_43_x hr)
  · exact mul_inv_eq_one.mp (e_44_x hr)
  · exact mul_inv_eq_one.mp (e_45_x hr)
  · exact mul_inv_eq_one.mp (e_46_x)
  · exact mul_inv_eq_one.mp (e_47_x hr)
  · exact mul_inv_eq_one.mp (e_48_x)
  · exact mul_inv_eq_one.mp (e_49_x hr)
  · exact mul_inv_eq_one.mp (e_50_x)
  · exact mul_inv_eq_one.mp (e_51_x)
  · exact mul_inv_eq_one.mp (e_52_x hr)
  · exact mul_inv_eq_one.mp (e_53_x)
  · exact mul_inv_eq_one.mp (e_54_x)
  · exact mul_inv_eq_one.mp (e_55_x hr)
  · exact mul_inv_eq_one.mp (e_56_x)
  · exact mul_inv_eq_one.mp (e_57_x hr)
  · exact mul_inv_eq_one.mp (e_58_x)
  · exact mul_inv_eq_one.mp (e_59_x hr)
  · exact mul_inv_eq_one.mp (e_60_x)
  · exact mul_inv_eq_one.mp (e_61_x hr)
  · exact mul_inv_eq_one.mp (e_62_x)
  · exact mul_inv_eq_one.mp (e_63_x hr)
  · exact mul_inv_eq_one.mp (e_64_x)
  · exact mul_inv_eq_one.mp (e_65_x hr)
  · exact mul_inv_eq_one.mp (e_66_x)
  · exact mul_inv_eq_one.mp (e_67_x)
  · exact mul_inv_eq_one.mp (e_68_x)
  · exact mul_inv_eq_one.mp (e_69_x hr)
  · exact mul_inv_eq_one.mp (e_70_x)
  · exact mul_inv_eq_one.mp (e_71_x hr)
  · exact mul_inv_eq_one.mp (e_72_x)
  · exact mul_inv_eq_one.mp (e_73_x hr)
  · exact mul_inv_eq_one.mp (e_74_x hr)
  · exact mul_inv_eq_one.mp (e_75_x)
  · exact mul_inv_eq_one.mp (e_76_x hr)
  · exact mul_inv_eq_one.mp (e_77_x)
  · exact mul_inv_eq_one.mp (e_78_x)
  · exact mul_inv_eq_one.mp (e_79_x hr)
  · exact mul_inv_eq_one.mp (e_80_x)
  · exact mul_inv_eq_one.mp (e_81_x hr)
  · exact mul_inv_eq_one.mp (e_82_x hr)
  · exact mul_inv_eq_one.mp (e_83_x)
  · exact mul_inv_eq_one.mp (e_84_x hr)
  · exact mul_inv_eq_one.mp (e_85_x hr)
  · exact mul_inv_eq_one.mp (e_86_x hr)
  · exact mul_inv_eq_one.mp (e_87_x)
  · exact mul_inv_eq_one.mp (e_88_x hr)
  · exact mul_inv_eq_one.mp (e_89_x hr)
  · exact mul_inv_eq_one.mp (e_90_x hr)
  · exact mul_inv_eq_one.mp (e_91_x hr)
  · exact mul_inv_eq_one.mp (e_92_x hr)
  · exact mul_inv_eq_one.mp (e_93_x)
  · exact mul_inv_eq_one.mp (e_94_x hr)
  · exact mul_inv_eq_one.mp (e_95_x)
  · exact mul_inv_eq_one.mp (e_96_x hr)
  · exact mul_inv_eq_one.mp (e_97_x hr)
  · exact mul_inv_eq_one.mp (e_98_x hr)
  · exact mul_inv_eq_one.mp (e_99_x hr)
  · exact mul_inv_eq_one.mp (e_100_x hr)
  · exact mul_inv_eq_one.mp (e_101_x)
  · exact mul_inv_eq_one.mp (e_102_x)
  · exact mul_inv_eq_one.mp (e_103_x)
  · exact mul_inv_eq_one.mp (e_104_x hr)
  · exact mul_inv_eq_one.mp (e_105_x hr)
  · exact mul_inv_eq_one.mp (e_106_x hr)
  · exact mul_inv_eq_one.mp (e_107_x hr)
  · exact mul_inv_eq_one.mp (e_108_x hr)
  · exact mul_inv_eq_one.mp (e_109_x hr)
  · exact mul_inv_eq_one.mp (e_110_x)
  · exact mul_inv_eq_one.mp (e_111_x hr)
  · exact mul_inv_eq_one.mp (e_112_x hr)
  · exact mul_inv_eq_one.mp (e_113_x hr)
  · exact mul_inv_eq_one.mp (e_114_x hr)
  · exact mul_inv_eq_one.mp (e_115_x hr)
  · exact mul_inv_eq_one.mp (e_116_x)
  · exact mul_inv_eq_one.mp (e_117_x hr)
  · exact mul_inv_eq_one.mp (e_118_x hr)
  · exact mul_inv_eq_one.mp (e_119_x hr)

/-- The `y`-column of the coset table. -/
theorem tab_y (hr : x * x * y * x⁻¹ * y = 1 ∧ x * y * y * y * y * x * y⁻¹ = 1) (i : Fin 120) :
    Wv x y i * y = Wv x y (tyv i) := by
  fin_cases i
  · exact mul_inv_eq_one.mp (e_0_y)
  · exact mul_inv_eq_one.mp (e_1_y)
  · exact mul_inv_eq_one.mp (e_2_y)
  · exact mul_inv_eq_one.mp (e_3_y)
  · exact mul_inv_eq_one.mp (e_4_y)
  · exact mul_inv_eq_one.mp (e_5_y hr)
  · exact mul_inv_eq_one.mp (e_6_y)
  · exact mul_inv_eq_one.mp (e_7_y)
  · exact mul_inv_eq_one.mp (e_8_y)
  · exact mul_inv_eq_one.mp (e_9_y)
  · exact mul_inv_eq_one.mp (e_10_y hr)
  · exact mul_inv_eq_one.mp (e_11_y)
  · exact mul_inv_eq_one.mp (e_12_y)
  · exact mul_inv_eq_one.mp (e_13_y)
  · exact mul_inv_eq_one.mp (e_14_y)
  · exact mul_inv_eq_one.mp (e_15_y)
  · exact mul_inv_eq_one.mp (e_16_y)
  · exact mul_inv_eq_one.mp (e_17_y hr)
  · exact mul_inv_eq_one.mp (e_18_y)
  · exact mul_inv_eq_one.mp (e_19_y)
  · exact mul_inv_eq_one.mp (e_20_y hr)
  · exact mul_inv_eq_one.mp (e_21_y hr)
  · exact mul_inv_eq_one.mp (e_22_y)
  · exact mul_inv_eq_one.mp (e_23_y)
  · exact mul_inv_eq_one.mp (e_24_y)
  · exact mul_inv_eq_one.mp (e_25_y)
  · exact mul_inv_eq_one.mp (e_26_y hr)
  · exact mul_inv_eq_one.mp (e_27_y hr)
  · exact mul_inv_eq_one.mp (e_28_y hr)
  · exact mul_inv_eq_one.mp (e_29_y)
  · exact mul_inv_eq_one.mp (e_30_y hr)
  · exact mul_inv_eq_one.mp (e_31_y hr)
  · exact mul_inv_eq_one.mp (e_32_y hr)
  · exact mul_inv_eq_one.mp (e_33_y)
  · exact mul_inv_eq_one.mp (e_34_y)
  · exact mul_inv_eq_one.mp (e_35_y hr)
  · exact mul_inv_eq_one.mp (e_36_y hr)
  · exact mul_inv_eq_one.mp (e_37_y)
  · exact mul_inv_eq_one.mp (e_38_y)
  · exact mul_inv_eq_one.mp (e_39_y)
  · exact mul_inv_eq_one.mp (e_40_y hr)
  · exact mul_inv_eq_one.mp (e_41_y)
  · exact mul_inv_eq_one.mp (e_42_y)
  · exact mul_inv_eq_one.mp (e_43_y)
  · exact mul_inv_eq_one.mp (e_44_y)
  · exact mul_inv_eq_one.mp (e_45_y)
  · exact mul_inv_eq_one.mp (e_46_y hr)
  · exact mul_inv_eq_one.mp (e_47_y)
  · exact mul_inv_eq_one.mp (e_48_y hr)
  · exact mul_inv_eq_one.mp (e_49_y)
  · exact mul_inv_eq_one.mp (e_50_y hr)
  · exact mul_inv_eq_one.mp (e_51_y)
  · exact mul_inv_eq_one.mp (e_52_y)
  · exact mul_inv_eq_one.mp (e_53_y hr)
  · exact mul_inv_eq_one.mp (e_54_y hr)
  · exact mul_inv_eq_one.mp (e_55_y)
  · exact mul_inv_eq_one.mp (e_56_y hr)
  · exact mul_inv_eq_one.mp (e_57_y)
  · exact mul_inv_eq_one.mp (e_58_y hr)
  · exact mul_inv_eq_one.mp (e_59_y)
  · exact mul_inv_eq_one.mp (e_60_y hr)
  · exact mul_inv_eq_one.mp (e_61_y)
  · exact mul_inv_eq_one.mp (e_62_y hr)
  · exact mul_inv_eq_one.mp (e_63_y)
  · exact mul_inv_eq_one.mp (e_64_y hr)
  · exact mul_inv_eq_one.mp (e_65_y)
  · exact mul_inv_eq_one.mp (e_66_y hr)
  · exact mul_inv_eq_one.mp (e_67_y hr)
  · exact mul_inv_eq_one.mp (e_68_y)
  · exact mul_inv_eq_one.mp (e_69_y)
  · exact mul_inv_eq_one.mp (e_70_y hr)
  · exact mul_inv_eq_one.mp (e_71_y)
  · exact mul_inv_eq_one.mp (e_72_y hr)
  · exact mul_inv_eq_one.mp (e_73_y)
  · exact mul_inv_eq_one.mp (e_74_y)
  · exact mul_inv_eq_one.mp (e_75_y hr)
  · exact mul_inv_eq_one.mp (e_76_y hr)
  · exact mul_inv_eq_one.mp (e_77_y hr)
  · exact mul_inv_eq_one.mp (e_78_y hr)
  · exact mul_inv_eq_one.mp (e_79_y)
  · exact mul_inv_eq_one.mp (e_80_y hr)
  · exact mul_inv_eq_one.mp (e_81_y)
  · exact mul_inv_eq_one.mp (e_82_y)
  · exact mul_inv_eq_one.mp (e_83_y hr)
  · exact mul_inv_eq_one.mp (e_84_y)
  · exact mul_inv_eq_one.mp (e_85_y hr)
  · exact mul_inv_eq_one.mp (e_86_y hr)
  · exact mul_inv_eq_one.mp (e_87_y hr)
  · exact mul_inv_eq_one.mp (e_88_y)
  · exact mul_inv_eq_one.mp (e_89_y)
  · exact mul_inv_eq_one.mp (e_90_y)
  · exact mul_inv_eq_one.mp (e_91_y)
  · exact mul_inv_eq_one.mp (e_92_y hr)
  · exact mul_inv_eq_one.mp (e_93_y hr)
  · exact mul_inv_eq_one.mp (e_94_y hr)
  · exact mul_inv_eq_one.mp (e_95_y hr)
  · exact mul_inv_eq_one.mp (e_96_y)
  · exact mul_inv_eq_one.mp (e_97_y)
  · exact mul_inv_eq_one.mp (e_98_y)
  · exact mul_inv_eq_one.mp (e_99_y)
  · exact mul_inv_eq_one.mp (e_100_y)
  · exact mul_inv_eq_one.mp (e_101_y hr)
  · exact mul_inv_eq_one.mp (e_102_y hr)
  · exact mul_inv_eq_one.mp (e_103_y hr)
  · exact mul_inv_eq_one.mp (e_104_y hr)
  · exact mul_inv_eq_one.mp (e_105_y)
  · exact mul_inv_eq_one.mp (e_106_y)
  · exact mul_inv_eq_one.mp (e_107_y hr)
  · exact mul_inv_eq_one.mp (e_108_y)
  · exact mul_inv_eq_one.mp (e_109_y)
  · exact mul_inv_eq_one.mp (e_110_y hr)
  · exact mul_inv_eq_one.mp (e_111_y hr)
  · exact mul_inv_eq_one.mp (e_112_y hr)
  · exact mul_inv_eq_one.mp (e_113_y)
  · exact mul_inv_eq_one.mp (e_114_y hr)
  · exact mul_inv_eq_one.mp (e_115_y hr)
  · exact mul_inv_eq_one.mp (e_116_y hr)
  · exact mul_inv_eq_one.mp (e_117_y)
  · exact mul_inv_eq_one.mp (e_118_y hr)
  · exact mul_inv_eq_one.mp (e_119_y)

theorem tab_xinv (hr : x * x * y * x⁻¹ * y = 1 ∧ x * y * y * y * y * x * y⁻¹ = 1) (i : Fin 120) :
    Wv x y i * x⁻¹ = Wv x y (txinv i) := by
  have h := tab_x hr (txinv i)
  rw [txv_txinv] at h
  rw [← h]
  group

theorem tab_yinv (hr : x * x * y * x⁻¹ * y = 1 ∧ x * y * y * y * y * x * y⁻¹ = 1) (i : Fin 120) :
    Wv x y i * y⁻¹ = Wv x y (tyinv i) := by
  have h := tab_y hr (tyinv i)
  rw [tyv_tyinv] at h
  rw [← h]
  group

/-- **The coset enumeration closes.**  In any group generated by two elements satisfying the
two relators of `A`, the 120 words of the table exhaust the group. -/
theorem surjective_Wv (hr : x * x * y * x⁻¹ * y = 1 ∧ x * y * y * y * y * x * y⁻¹ = 1)
    (hgen : Subgroup.closure ({x, y} : Set G) = ⊤) : Function.Surjective (Wv x y) := by
  have key : ∀ g ∈ Subgroup.closure ({x, y} : Set G),
      (∀ i, ∃ j, Wv x y i * g = Wv x y j) ∧ (∀ i, ∃ j, Wv x y i * g⁻¹ = Wv x y j) := by
    intro g hg
    induction hg using Subgroup.closure_induction with
    | mem z hz =>
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
        rcases hz with rfl | rfl
        · exact ⟨fun i => ⟨txv i, tab_x hr i⟩, fun i => ⟨txinv i, tab_xinv hr i⟩⟩
        · exact ⟨fun i => ⟨tyv i, tab_y hr i⟩, fun i => ⟨tyinv i, tab_yinv hr i⟩⟩
    | one => exact ⟨fun i => ⟨i, mul_one _⟩, fun i => ⟨i, by simp⟩⟩
    | mul a b _ _ iha ihb =>
        refine ⟨fun i => ?_, fun i => ?_⟩
        · obtain ⟨j, hj⟩ := iha.1 i
          obtain ⟨k, hk⟩ := ihb.1 j
          exact ⟨k, by rw [← mul_assoc, hj, hk]⟩
        · obtain ⟨j, hj⟩ := ihb.2 i
          obtain ⟨k, hk⟩ := iha.2 j
          exact ⟨k, by rw [_root_.mul_inv_rev, ← mul_assoc, hj, hk]⟩
    | inv a _ iha =>
        refine ⟨iha.2, fun i => ?_⟩
        obtain ⟨j, hj⟩ := iha.1 i
        exact ⟨j, by rwa [inv_inv]⟩
  intro g
  obtain ⟨j, hj⟩ := (key g (by rw [hgen]; exact Subgroup.mem_top g)).1 0
  exact ⟨j, by rw [← hj, Wv_zero, one_mul]⟩

/-- Every group generated by two elements satisfying the relators of `A` has at most `120`
elements. -/
theorem card_le_120 (hr : x * x * y * x⁻¹ * y = 1 ∧ x * y * y * y * y * x * y⁻¹ = 1)
    (hgen : Subgroup.closure ({x, y} : Set G) = ⊤) : Nat.card G ≤ 120 := by
  have h := Nat.card_le_card_of_surjective _ (surjective_Wv hr hgen)
  simpa using h

/-!
## The presented group of `A` and the isomorphism with `SL(2,5)`
-/

/-- The group `SL(2,5)`. -/
abbrev SL25 := Matrix.SpecialLinearGroup (Fin 2) (ZMod 5)

instance : DecidableEq SL25 := fun a b =>
  decidable_of_iff _ (Matrix.SpecialLinearGroup.ext_iff a b).symm

/-- The matrix chosen as the image of the first generator. -/
def XM : SL25 := ⟨!![0, 1; 4, 1], by decide⟩

/-- The matrix chosen as the image of the second generator. -/
def YM : SL25 := ⟨!![0, 2; 2, 3], by decide⟩

theorem hrM : XM * XM * YM * XM⁻¹ * YM = 1 ∧ XM * YM * YM * YM * YM * XM * YM⁻¹ = 1 := by
  constructor <;> decide

/-- The 120 matrices that the coset words take as values. -/
def matv : Fin 120 → SL25 := ![⟨!![1,0;0,1], by decide⟩, ⟨!![0,1;4,1], by decide⟩, ⟨!![0,2;2,3], by decide⟩, ⟨!![1,4;1,0], by decide⟩, ⟨!![3,3;3,0], by decide⟩, ⟨!![4,1;4,0], by decide⟩, ⟨!![2,3;2,1], by decide⟩, ⟨!![3,0;0,2], by decide⟩, ⟨!![3,2;2,0], by decide⟩, ⟨!![4,1;1,3], by decide⟩, ⟨!![2,0;0,3], by decide⟩, ⟨!![3,4;0,2], by decide⟩, ⟨!![0,4;1,4], by decide⟩, ⟨!![0,3;3,3], by decide⟩, ⟨!![2,1;0,3], by decide⟩, ⟨!![1,2;3,2], by decide⟩, ⟨!![3,4;4,4], by decide⟩, ⟨!![4,0;0,4], by decide⟩, ⟨!![0,2;2,2], by decide⟩, ⟨!![2,0;4,3], by decide⟩, ⟨!![1,3;2,2], by decide⟩, ⟨!![0,3;3,2], by decide⟩, ⟨!![4,4;1,0], by decide⟩, ⟨!![4,2;0,4], by decide⟩, ⟨!![0,4;1,1], by decide⟩, ⟨!![4,0;2,4], by decide⟩, ⟨!![2,1;1,1], by decide⟩, ⟨!![0,1;4,4], by decide⟩, ⟨!![2,3;3,0], by decide⟩, ⟨!![1,1;4,0], by decide⟩, ⟨!![3,3;4,1], by decide⟩, ⟨!![2,2;2,0], by decide⟩, ⟨!![3,2;3,4], by decide⟩, ⟨!![3,0;1,2], by decide⟩, ⟨!![4,0;3,4], by decide⟩, ⟨!![4,3;2,3], by decide⟩, ⟨!![2,2;1,4], by decide⟩, ⟨!![4,3;4,2], by decide⟩, ⟨!![4,3;0,4], by decide⟩, ⟨!![1,2;1,3], by decide⟩, ⟨!![2,2;3,1], by decide⟩, ⟨!![1,4;4,2], by decide⟩, ⟨!![1,0;2,1], by decide⟩, ⟨!![0,4;1,2], by decide⟩, ⟨!![1,1;1,2], by decide⟩, ⟨!![2,4;3,4], by decide⟩, ⟨!![4,4;4,3], by decide⟩, ⟨!![1,3;0,1], by decide⟩, ⟨!![3,1;1,4], by decide⟩, ⟨!![4,2;3,3], by decide⟩, ⟨!![4,4;3,2], by decide⟩, ⟨!![2,0;1,3], by decide⟩, ⟨!![0,3;3,1], by decide⟩, ⟨!![3,3;2,4], by decide⟩, ⟨!![1,0;3,1], by decide⟩, ⟨!![3,0;4,2], by decide⟩, ⟨!![2,4;4,1], by decide⟩, ⟨!![2,1;4,0], by decide⟩, ⟨!![1,2;0,1], by decide⟩, ⟨!![0,1;4,3], by decide⟩, ⟨!![4,1;2,2], by decide⟩, ⟨!![3,4;1,0], by decide⟩, ⟨!![1,2;4,4], by decide⟩, ⟨!![1,2;2,0], by decide⟩, ⟨!![4,3;1,1], by decide⟩, ⟨!![2,1;2,4], by decide⟩, ⟨!![1,4;3,3], by decide⟩, ⟨!![3,2;4,3], by decide⟩, ⟨!![1,3;4,3], by decide⟩, ⟨!![3,1;3,3], by decide⟩, ⟨!![3,1;2,1], by decide⟩, ⟨!![4,2;1,2], by decide⟩, ⟨!![1,1;2,3], by decide⟩, ⟨!![2,4;0,3], by decide⟩, ⟨!![1,3;3,0], by decide⟩, ⟨!![3,1;0,2], by decide⟩, ⟨!![0,2;2,4], by decide⟩, ⟨!![2,3;4,4], by decide⟩, ⟨!![1,4;2,4], by decide⟩, ⟨!![3,4;3,1], by decide⟩, ⟨!![3,2;1,1], by decide⟩, ⟨!![2,2;0,3], by decide⟩, ⟨!![4,3;3,0], by decide⟩, ⟨!![2,3;1,2], by decide⟩, ⟨!![0,2;2,1], by decide⟩, ⟨!![3,3;0,2], by decide⟩, ⟨!![3,3;1,3], by decide⟩, ⟨!![3,4;2,3], by decide⟩, ⟨!![2,2;4,2], by decide⟩, ⟨!![4,1;3,1], by decide⟩, ⟨!![0,3;3,4], by decide⟩, ⟨!![3,0;2,2], by decide⟩, ⟨!![2,4;2,2], by decide⟩, ⟨!![4,4;2,1], by decide⟩, ⟨!![2,4;1,0], by decide⟩, ⟨!![1,1;3,4], by decide⟩, ⟨!![4,2;2,0], by decide⟩, ⟨!![3,1;4,0], by decide⟩, ⟨!![1,1;0,1], by decide⟩, ⟨!![0,1;4,2], by decide⟩, ⟨!![1,0;1,1], by decide⟩, ⟨!![0,4;1,3], by decide⟩, ⟨!![4,0;1,4], by decide⟩, ⟨!![2,1;3,2], by decide⟩, ⟨!![2,0;3,3], by decide⟩, ⟨!![1,0;4,1], by decide⟩, ⟨!![1,4;0,1], by decide⟩, ⟨!![4,0;4,4], by decide⟩, ⟨!![0,1;4,0], by decide⟩, ⟨!![4,2;4,1], by decide⟩, ⟨!![1,3;1,4], by decide⟩, ⟨!![4,4;0,4], by decide⟩, ⟨!![2,0;2,3], by decide⟩, ⟨!![3,0;3,2], by decide⟩, ⟨!![0,2;2,0], by decide⟩, ⟨!![0,4;1,0], by decide⟩, ⟨!![4,1;0,4], by decide⟩, ⟨!![0,3;3,0], by decide⟩, ⟨!![2,3;0,3], by decide⟩, ⟨!![3,2;0,2], by decide⟩]

theorem Wv_XM_YM (i : Fin 120) : Wv XM YM i = matv i := by fin_cases i <;> decide

theorem matv_injective : Function.Injective matv := by decide

/-!
### The presented group `G(A)`
-/

/-- The first relator `x²yx⁻¹y` of `A`. -/
def rel1 : FreeGroup (Fin 2) :=
  FreeGroup.of 0 * FreeGroup.of 0 * FreeGroup.of 1 * (FreeGroup.of 0)⁻¹ * FreeGroup.of 1

/-- The second relator `xy⁴xy⁻¹` of `A`. -/
def rel2 : FreeGroup (Fin 2) :=
  FreeGroup.of 0 * FreeGroup.of 1 * FreeGroup.of 1 * FreeGroup.of 1 * FreeGroup.of 1 *
    FreeGroup.of 0 * (FreeGroup.of 1)⁻¹

/-- The relators of the presentation `A = ⟨x, y | x²yx⁻¹y, xy⁴xy⁻¹⟩`. -/
def relsA : Set (FreeGroup (Fin 2)) := {rel1, rel2}

/-- The group `G(A)` of the presentation `A`. -/
abbrev GA := PresentedGroup relsA

/-- The generator `x` of `G(A)`. -/
def xA : GA := PresentedGroup.of 0

/-- The generator `y` of `G(A)`. -/
def yA : GA := PresentedGroup.of 1

theorem hrA : xA * xA * yA * xA⁻¹ * yA = 1 ∧ xA * yA * yA * yA * yA * xA * yA⁻¹ = 1 := by
  constructor
  · have h : PresentedGroup.mk relsA rel1 = 1 :=
      PresentedGroup.one_of_mem (Or.inl rfl)
    simpa [rel1, xA, yA, PresentedGroup.of, map_mul, map_inv] using h
  · have h : PresentedGroup.mk relsA rel2 = 1 :=
      PresentedGroup.one_of_mem (Or.inr rfl)
    simpa [rel2, xA, yA, PresentedGroup.of, map_mul, map_inv] using h

theorem range_of_eq : Set.range (PresentedGroup.of : Fin 2 → GA) = {xA, yA} := by
  ext z
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i
    · exact Or.inl rfl
    · exact Or.inr rfl
  · rintro (rfl | rfl)
    · exact ⟨0, rfl⟩
    · exact ⟨1, rfl⟩

theorem hgenA : Subgroup.closure ({xA, yA} : Set GA) = ⊤ := by
  rw [← range_of_eq]
  exact PresentedGroup.closure_range_of relsA

theorem liftM_rels : ∀ r ∈ relsA, FreeGroup.lift ![XM, YM] r = 1 := by
  rintro r (rfl | rfl)
  · simp only [rel1, map_mul, map_inv, FreeGroup.lift_apply_of, Matrix.cons_val_zero,
      Matrix.cons_val_one]
    exact hrM.1
  · simp only [rel2, map_mul, map_inv, FreeGroup.lift_apply_of, Matrix.cons_val_zero,
      Matrix.cons_val_one]
    exact hrM.2

/-- The homomorphism `G(A) → SL(2,5)` sending the generators to `XM` and `YM`. -/
def phi : GA →* SL25 := PresentedGroup.toGroup liftM_rels

theorem phi_xA : phi xA = XM := PresentedGroup.toGroup.of liftM_rels

theorem phi_yA : phi yA = YM := PresentedGroup.toGroup.of liftM_rels

theorem phi_Wv (i : Fin 120) : phi (Wv xA yA i) = Wv XM YM i := by
  rw [map_Wv, phi_xA, phi_yA]

theorem card_SL25 : Fintype.card SL25 = 120 := by decide

theorem matv_bijective : Function.Bijective matv := by
  refine (Fintype.bijective_iff_injective_and_card matv).mpr ⟨matv_injective, ?_⟩
  simp [card_SL25]

theorem phi_surjective : Function.Surjective phi := by
  intro M
  obtain ⟨i, hi⟩ := matv_bijective.2 M
  exact ⟨Wv xA yA i, by rw [phi_Wv, Wv_XM_YM, hi]⟩

theorem phi_injective : Function.Injective phi := by
  intro a b hab
  obtain ⟨i, rfl⟩ := surjective_Wv hrA hgenA a
  obtain ⟨j, rfl⟩ := surjective_Wv hrA hgenA b
  rw [phi_Wv, phi_Wv, Wv_XM_YM, Wv_XM_YM] at hab
  rw [matv_injective hab]

/-- **Remark 2: `G(A) ≅ SL(2,5)`.**  The group of the presentation
`A = ⟨x, y | x²yx⁻¹y, xy⁴xy⁻¹⟩` is isomorphic to `SL(2,5)`, by the homomorphism sending the
two generators to the matrices `XM` and `YM`. -/
noncomputable def presentedA_mulEquiv_SL25 : GA ≃* SL25 :=
  MulEquiv.ofBijective phi ⟨phi_injective, phi_surjective⟩

/-- `G(A)` is finite of order `120`. -/
theorem card_GA : Nat.card GA = 120 := by
  have : Nat.card GA = Nat.card SL25 := Nat.card_congr presentedA_mulEquiv_SL25.toEquiv
  rw [this, Nat.card_eq_fintype_card, card_SL25]

/-- The matrix `XM` has order `6` in `SL(2,5)`. -/
theorem orderOf_XM : orderOf XM = 6 := by
  refine orderOf_eq_of_pow_and_pow_div_prime (by norm_num) (by decide) ?_
  intro p hp hdvd
  have hmem : p ∈ Nat.divisors 6 := Nat.mem_divisors.mpr ⟨hdvd, by norm_num⟩
  fin_cases hmem
  · exact absurd hp (by norm_num)
  · decide
  · decide
  · exact absurd hp (by norm_num)

/-- **`G(A)` has torsion**: the generator `x` has order `6`.  This is the property of the
example used in Remark 2 to see that `K(A)`, which is acyclic, is not aspherical. -/
theorem orderOf_xA : orderOf xA = 6 := by
  have h : orderOf xA = orderOf (phi xA) := (orderOf_injective phi phi_injective xA).symm
  rw [h, phi_xA, orderOf_XM]

end ExampleA
end FiniteChains
