import RequestProject.CombCellularIso
import RequestProject.MapChainDescent

/-!
# The generation statement (3.5) for an isomorphism, and the pushout along an isomorphism

Step 2 of the proof of Proposition 3.11 asserts that `π₂(E)` of the pushout `E = K ∪_p L` is
generated by the spherical classes coming from the copies of `L̃`.  This file proves that
statement in the case where the covering `p : D → K` is an isomorphism (in particular for the
identity covering `D = K`, the case in which the paper takes the acyclic complex `K` itself as
its own acyclic cover).  In that case the map `L → K ∪_p L` is an isomorphism of complexes,
and the statement becomes the assertion that an isomorphism identifies the two `π₂`'s.

* `FiniteChains.Comb.homInv` — the inverse of a cellular map which is bijective on cells;
* `FiniteChains.Comb.univLiftV_bijective`, `univLiftF_bijective`, `univLiftE_injective` — the
  lift of such a map to the universal covers is again bijective on cells;
* `FiniteChains.Comb.pi2_le_span_pi2FromSub_of_bijective` — hence every spherical class of `E`
  comes from `L`;
* `FiniteChains.Comb.pushV_bijective`, `pushE_bijective`, `pushF_bijective` — the map
  `L → K ∪_p L` is bijective on cells when `p` is;
* `FiniteChains.Comb.pi2GeneratedByUpstairsFor_of_bijective` — the generation statement (3.5)
  for an isomorphism covering.
-/

namespace FiniteChains
namespace Comb

universe u

/-! ### The inverse of a cellular map which is bijective on cells -/



/-! ### The lift of an isomorphism to the universal covers -/

section Lift

variable {L E : Complex2.{u}} (ι : Hom L E)
variable (hV : Function.Bijective ι.onV) (hE : Function.Bijective ι.onE)
  (hF : Function.Bijective ι.onF) (l₀ : L.V)

include hV hE hF in
/-- The lift of a cellular map which is bijective on cells is bijective on the vertices of the
universal covers. -/
theorem univLiftV_bijective : Function.Bijective (univLiftV l₀ ι) := by
  classical
  set ψ := homInv ι hV hE hF with hψ
  constructor
  · intro c c' h
    induction c using UV.ind with
    | h p =>
      induction c' using UV.ind with
      | h q =>
        have hq := Quotient.exact h
        have hmap := mapPath_htpy ψ hq
        have hp1 : (mapPathFrom l₀ ι p).1 = mapPath ι p.1 := rfl
        have hq1 : (mapPathFrom l₀ ι q).1 = mapPath ι q.1 := rfl
        rw [hp1, hq1, mapPath_homInv ι hV hE hF, mapPath_homInv ι hV hE hF] at hmap
        refine Quotient.sound ?_
        have h1 : ψ.onV (ι.onV l₀) = l₀ := homInv_onV_comp ι hV hE hF l₀
        have h2 : ψ.onV (endpt E (ι.onV l₀) (mapPath ι p.1)) = endpt L l₀ p.1 := by
          rw [endpt_mapPath ι p.1 l₀, homInv_onV_comp ι hV hE hF]
        rw [h1, h2] at hmap
        exact hmap
  · intro d
    induction d using UV.ind with
    | h r =>
      have hpath : IsPath L.src L.tgt (mapPath ψ r.1) (ψ.onV (ι.onV l₀))
          (ψ.onV (endpt E (ι.onV l₀) r.1)) := isPath_mapPath ψ r.2
      have h1 : ψ.onV (ι.onV l₀) = l₀ := homInv_onV_comp ι hV hE hF l₀
      have h2 : endpt L l₀ (mapPath ψ r.1) = ψ.onV (endpt E (ι.onV l₀) r.1) := by
        have h3 := endpt_mapPath ψ r.1 (ι.onV l₀)
        rw [h1] at h3
        exact h3
      rw [h1] at hpath
      refine ⟨UV.mk ⟨mapPath ψ r.1, by rw [h2]; exact hpath⟩, ?_⟩
      refine congrArg (UV.mk (X := E) (x₀ := ι.onV l₀)) ?_
      exact Subtype.ext (mapPath_homInv' ι hV hE hF r.1)

include hV hE hF in
/-- The lift of a cellular map which is bijective on cells is bijective on the two-cells of the
universal covers. -/
theorem univLiftF_bijective : Function.Bijective (univLiftF l₀ ι) := by
  constructor
  · rintro ⟨⟨c, f⟩, hc⟩ ⟨⟨c', f'⟩, hc'⟩ h
    have h1 : univLiftV l₀ ι c = univLiftV l₀ ι c' := congrArg (fun F => F.1.1) h
    have h2 : ι.onF f = ι.onF f' := congrArg (fun F => F.1.2) h
    exact Subtype.ext (Prod.ext ((univLiftV_bijective ι hV hE hF l₀).1 h1) (hF.1 h2))
  · rintro ⟨⟨c, f⟩, hc⟩
    obtain ⟨c', rfl⟩ := (univLiftV_bijective ι hV hE hF l₀).2 c
    refine ⟨⟨(c', (homInv ι hV hE hF).onF f), ?_⟩, ?_⟩
    · have hc' : endV (univLiftV l₀ ι c') = E.base f := hc
      refine hV.1 ?_
      show ι.onV (endV c') = ι.onV (L.base ((homInv ι hV hE hF).onF f))
      rw [← endV_univLiftV (x₀ := l₀) ι c', hc', ← ι.base_onF, homInv_onF_apply]
    · exact Subtype.ext (Prod.ext rfl (homInv_onF_apply ι hV hE hF f))

include hV hE hF in
/-- The lift of a cellular map which is bijective on cells is injective on the edges of the
universal covers. -/
theorem univLiftE_injective : Function.Injective (univLiftE l₀ ι) := by
  rintro ⟨⟨c, e⟩, hc⟩ ⟨⟨c', e'⟩, hc'⟩ h
  have h1 : univLiftV l₀ ι c = univLiftV l₀ ι c' := congrArg (fun F => F.1.1) h
  have h2 : ι.onE e = ι.onE e' := congrArg (fun F => F.1.2) h
  exact Subtype.ext (Prod.ext ((univLiftV_bijective ι hV hE hF l₀).1 h1) (hE.1 h2))

include hV hE hF in
/-- **An isomorphism of complexes identifies the two `π₂`'s**: every spherical class of `E`
comes from a spherical class of `L`. -/
theorem pi2_le_span_pi2FromSub_of_bijective (z : (uCover E (ι.onV l₀)).F →₀ ℤ)
    (hz : z ∈ Pi2 E (ι.onV l₀)) :
    z ∈ Submodule.span ℤ (Pi2FromSub ι (ι.onV l₀)) := by
  classical
  set φ : Hom (uCover L l₀) (uCover E (ι.onV l₀)) := univLift L ι l₀ with hφ
  have hbF : Function.Bijective φ.onF := univLiftF_bijective ι hV hE hF l₀
  have hiE : Function.Injective φ.onE := univLiftE_injective ι hV hE hF l₀
  set eF : (uCover L l₀).F ≃ (uCover E (ι.onV l₀)).F := Equiv.ofBijective _ hbF with heF
  set w : (uCover L l₀).F →₀ ℤ := Finsupp.equivMapDomain eF.symm z with hw
  have hchain : chain2 φ w = z := by
    have h1 : Finsupp.mapDomain φ.onF w = Finsupp.equivMapDomain eF w := by
      rw [Finsupp.equivMapDomain_eq_mapDomain]
      rfl
    rw [chain2_apply, h1, hw, ← Finsupp.equivMapDomain_trans, Equiv.symm_trans_self,
      Finsupp.equivMapDomain_refl]
  have hwmem : w ∈ Pi2 L l₀ := by
    have h0 : chain1 φ (bdry2 (uCover L l₀) w) = 0 := by
      rw [← bdry2_chain2 φ w, hchain]
      exact hz
    have hinj : Function.Injective (chain1 φ) := by
      intro a b hab
      exact Finsupp.mapDomain_injective hiE hab
    have : bdry2 (uCover L l₀) w = 0 := by
      apply hinj
      rw [h0, map_zero]
    exact this
  have hmem := mem_pi2FromSub_univLift ι l₀ hwmem
  rw [hchain] at hmem
  exact Submodule.subset_span hmem

end Lift

/-! ### The pushout along an isomorphism -/

section Pushout

variable {D K L : Complex2.{u}} (p : Hom D K) (i : Hom D L)

theorem pushV_bijective (hiV : Function.Injective i.onV) (hpV : Function.Bijective p.onV) :
    Function.Bijective (pushV p i) := by
  classical
  constructor
  · intro v v' h
    by_cases hv : ∃ d, i.onV d = v
    · obtain ⟨d, rfl⟩ := hv
      by_cases hv' : ∃ d', i.onV d' = v'
      · obtain ⟨d', rfl⟩ := hv'
        rw [pushV_of_mem p hiV d, pushV_of_mem p hiV d'] at h
        exact congrArg i.onV (hpV.1 (Sum.inl_injective h))
      · rw [pushV_of_mem p hiV d,
          pushV_of_off p i ⟨v', fun d' hd' => hv' ⟨d', hd'⟩⟩] at h
        exact absurd h (by simp)
    · by_cases hv' : ∃ d', i.onV d' = v'
      · obtain ⟨d', rfl⟩ := hv'
        rw [pushV_of_mem p hiV d', pushV_of_off p i ⟨v, fun d hd => hv ⟨d, hd⟩⟩] at h
        exact absurd h (by simp)
      · rw [pushV_of_off p i ⟨v, fun d hd => hv ⟨d, hd⟩⟩,
          pushV_of_off p i ⟨v', fun d' hd' => hv' ⟨d', hd'⟩⟩] at h
        exact congrArg (fun w : OffV i => w.1) (Sum.inr_injective h)
  · rintro (a | v)
    · obtain ⟨d, rfl⟩ := hpV.2 a
      exact ⟨i.onV d, pushV_of_mem p hiV d⟩
    · exact ⟨v.1, pushV_of_off p i v⟩

theorem pushE_bijective (hiE : Function.Injective i.onE) (hpE : Function.Bijective p.onE) :
    Function.Bijective (pushE p i) := by
  classical
  constructor
  · intro v v' h
    by_cases hv : ∃ d, i.onE d = v
    · obtain ⟨d, rfl⟩ := hv
      by_cases hv' : ∃ d', i.onE d' = v'
      · obtain ⟨d', rfl⟩ := hv'
        rw [pushE_of_mem p hiE d, pushE_of_mem p hiE d'] at h
        exact congrArg i.onE (hpE.1 (Sum.inl_injective h))
      · rw [pushE_of_mem p hiE d,
          pushE_of_off p i ⟨v', fun d' hd' => hv' ⟨d', hd'⟩⟩] at h
        exact absurd h (by simp)
    · by_cases hv' : ∃ d', i.onE d' = v'
      · obtain ⟨d', rfl⟩ := hv'
        rw [pushE_of_mem p hiE d', pushE_of_off p i ⟨v, fun d hd => hv ⟨d, hd⟩⟩] at h
        exact absurd h (by simp)
      · rw [pushE_of_off p i ⟨v, fun d hd => hv ⟨d, hd⟩⟩,
          pushE_of_off p i ⟨v', fun d' hd' => hv' ⟨d', hd'⟩⟩] at h
        exact congrArg (fun w : OffE i => w.1) (Sum.inr_injective h)
  · rintro (a | v)
    · obtain ⟨d, rfl⟩ := hpE.2 a
      exact ⟨i.onE d, pushE_of_mem p hiE d⟩
    · exact ⟨v.1, pushE_of_off p i v⟩

theorem pushF_bijective (hiF : Function.Injective i.onF) (hpF : Function.Bijective p.onF) :
    Function.Bijective (pushF p i) := by
  classical
  constructor
  · intro v v' h
    by_cases hv : ∃ d, i.onF d = v
    · obtain ⟨d, rfl⟩ := hv
      by_cases hv' : ∃ d', i.onF d' = v'
      · obtain ⟨d', rfl⟩ := hv'
        rw [pushF_of_mem p hiF d, pushF_of_mem p hiF d'] at h
        exact congrArg i.onF (hpF.1 (Sum.inl_injective h))
      · rw [pushF_of_mem p hiF d,
          pushF_of_off p i ⟨v', fun d' hd' => hv' ⟨d', hd'⟩⟩] at h
        exact absurd h (by simp)
    · by_cases hv' : ∃ d', i.onF d' = v'
      · obtain ⟨d', rfl⟩ := hv'
        rw [pushF_of_mem p hiF d', pushF_of_off p i ⟨v, fun d hd => hv ⟨d, hd⟩⟩] at h
        exact absurd h (by simp)
      · rw [pushF_of_off p i ⟨v, fun d hd => hv ⟨d, hd⟩⟩,
          pushF_of_off p i ⟨v', fun d' hd' => hv' ⟨d', hd'⟩⟩] at h
        exact congrArg (fun w : OffF i => w.1) (Sum.inr_injective h)
  · rintro (a | v)
    · obtain ⟨d, rfl⟩ := hpF.2 a
      exact ⟨i.onF d, pushF_of_mem p hiF d⟩
    · exact ⟨v.1, pushF_of_off p i v⟩

end Pushout

/-! ### The generation statement (3.5) for an isomorphism covering -/

/-- **The generation statement (3.5) holds for an isomorphism covering.**  If the covering
`p : D → K` is bijective on cells — the case `D = K`, `p = id` of the paper, where the acyclic
complex is its own acyclic cover — then the map `L → K ∪_p L` is an isomorphism, so every
spherical class of the pushout comes from `L`. -/
theorem pi2GeneratedByUpstairsFor_of_bijective {D K : Complex2.{u}} (p : Hom D K)
    (hpV : Function.Bijective p.onV) (hpE : Function.Bijective p.onE)
    (hpF : Function.Bijective p.onF) : Pi2GeneratedByUpstairsFor p := by
  intro L ι hV hE hF _ _ _ _ _ x₀ z hz
  have hbV : Function.Bijective (pushoutMap p ι hV hE hF).onV := pushV_bijective p ι hV hpV
  have hbE : Function.Bijective (pushoutMap p ι hV hE hF).onE := pushE_bijective p ι hE hpE
  have hbF : Function.Bijective (pushoutMap p ι hV hE hF).onF := pushF_bijective p ι hF hpF
  obtain ⟨l₀, rfl⟩ := hbV.2 x₀
  exact pi2_le_span_pi2FromSub_of_bijective (pushoutMap p ι hV hE hF) hbV hbE hbF l₀ z hz

end Comb
end FiniteChains
