import RequestProject.SquareComplexMedianCriterion
import RequestProject.MedianSquareComplexWalls
import RequestProject.MedianSimplyConnected

/-!
# The hypotheses of the criterion are exactly those of a median complex

`RequestProject/SquareComplexMedianCriterion.lean` reduces the conclusion of Gromov's criterion to
two conditions on the one-skeleton of a connected, simply connected square complex: the quadrangle
condition, and convexity of the halfspaces of the hyperplanes.  This file checks that the
reduction is **not vacuous**: both conditions hold for the square complex of an arbitrary median
graph, alongside simple connectivity, which was proved in
`RequestProject/MedianSimplyConnected.lean`.

* `FiniteChains.MedianSimpleGraph.quadrangleCondition` — a median graph satisfies the quadrangle
  condition;
* `FiniteChains.SquareComplex.hyp_le_wall` — the hyperplane of an edge is contained in the wall of
  that edge: parallel edges (opposite sides of a two-cell) cross the same wall;
* `FiniteChains.SquareComplex.median_hyp_geodesic_crossings` — hence a shortest walk crosses each
  hyperplane at most once, and
* `FiniteChains.MedianSimpleGraph.criterion_hypotheses` — **all the hypotheses of
  `FiniteChains.SquareComplex.medianSimpleGraph_of_criterion` hold for the square complex of a
  median graph.**
-/

namespace FiniteChains

universe u

variable {Vx : Type u}

namespace MedianSimpleGraph

/-- **A median graph satisfies the quadrangle condition.** -/
theorem quadrangleCondition (M : MedianSimpleGraph Vx) : QuadrangleCondition M.G := by
  intro x q u v huq hvq huv hlu hlv
  obtain ⟨h1, h2, h3, -⟩ := M.quadrangle_graph huq hvq.symm huv hlu hlv
  exact ⟨M.med u v x, h1.symm, h2.symm, by omega⟩

end MedianSimpleGraph

namespace SquareComplex

variable {S : SquareComplex Vx} {M : MedianSimpleGraph Vx}

/-- A label supported off the walk contributes no crossings. -/
theorem crossCount_eq_zero_of_label_zero {χ : Vx → Vx → ZMod 2} (h : ∀ a b : Vx, χ a b = 0) :
    ∀ l : List Vx, crossCount χ l = 0 := by
  intro l
  induction l with
  | nil => simp
  | cons a t ih =>
      match t with
      | [] => simp
      | b :: t' =>
          rw [crossCount_cons_cons, h a b]
          simpa using ih

/-- Crossing counts are monotone in the label. -/
theorem crossCount_mono {χ χ' : Vx → Vx → ZMod 2} (h : ∀ a b : Vx, χ a b = 1 → χ' a b = 1) :
    ∀ l : List Vx, crossCount χ l ≤ crossCount χ' l := by
  intro l
  induction l with
  | nil => simp
  | cons a t ih =>
      match t with
      | [] => simp
      | b :: t' =>
          rw [crossCount_cons_cons, crossCount_cons_cons]
          have hstep : (if χ a b = 1 then 1 else 0) ≤ (if χ' a b = 1 then 1 else 0 : ℕ) := by
            by_cases hab : χ a b = 1
            · rw [if_pos hab, if_pos (h a b hab)]
            · rw [if_neg hab]
              omega
          have := ih
          omega

section Compatible

variable (hadj : ∀ a b : Vx, S.adj a b ↔ M.G.Adj a b)
    (hsq : ∀ {a b c d : Vx}, S.sq a b c d → a ≠ c ∧ b ≠ d)

include hadj hsq

/-- **Parallel edges cross the same wall.**  Reversing an edge and passing to the opposite side of
a two-cell both preserve the property of crossing a given wall, so the property only depends on
the hyperplane of the edge. -/
theorem crossesWall_parStep {R : Vx → Vx → Prop} (hR : R ∈ (M.toMedianGraph).Walls)
    {p q : Vx × Vx} (hpq : parStep S p q) : (¬ R p.1 p.2) ↔ (¬ R q.1 q.2) := by
  rcases hpq with hswap | hsquare
  · subst hswap
    obtain ⟨X, Y, -, rfl⟩ := hR
    simp only [MedianGraph.wallRel]
    exact not_congr Iff.comm
  · constructor
    · intro h
      exact square_not_wallRel hadj hsq hR hsquare h
    · intro h
      exact square_not_wallRel hadj hsq hR
        (S.sq_rotate (S.sq_rotate hsquare)) h

/-- The property of crossing a wall is invariant along the equivalence generated by
parallelism. -/
theorem crossesWall_eqvGen {R : Vx → Vx → Prop} (hR : R ∈ (M.toMedianGraph).Walls)
    {p q : Vx × Vx} (h : Relation.EqvGen (parStep S) p q) :
    (¬ R p.1 p.2) ↔ (¬ R q.1 q.2) := by
  induction h with
  | rel p q hpq => exact crossesWall_parStep hadj hsq hR hpq
  | refl p => exact Iff.rfl
  | symm p q _ ih => exact ih.symm
  | trans p q r _ _ ih1 ih2 => exact ih1.trans ih2

/-- The hyperplane of an edge determines the wall it crosses. -/
theorem crossesWall_of_hypOf_eq {R : Vx → Vx → Prop} (hR : R ∈ (M.toMedianGraph).Walls)
    {a b u v : Vx} (h : S.hypOf a b = S.hypOf u v) : (¬ R a b) ↔ (¬ R u v) :=
  crossesWall_eqvGen hadj hsq hR (p := (a, b)) (q := (u, v)) (Quot.eq.mp h)

omit hadj hsq in
/-- An edge carries the label of a wall exactly when it crosses it. -/
theorem wallLabel_eq_one_iff (R : (M.toMedianGraph).Walls) (c d : Vx) :
    wallLabel R c d = 1 ↔ ¬ R.1 c d := by
  classical
  by_cases h : R.1 c d <;> simp [wallLabel, h]

open Classical in
/-- **A shortest walk crosses every hyperplane at most once**, in a square complex whose
one-skeleton is a median graph: each hyperplane is contained in a wall of the graph, for which the
criterion is already proved. -/
theorem median_hyp_geodesic_crossings (x₀ : Vx) :
    ∀ (u v : Vx) (l : List Vx), S.IsGeodesic u v l →
      ∀ H : S.Hyp, crossCount (S.hypLabel H) l ≤ 1 := by
  classical
  intro u v l hl H
  by_cases hedge : ∃ a b : Vx, S.adj a b ∧ S.hypOf a b = H
  · obtain ⟨a, b, hab, hH⟩ := hedge
    obtain ⟨R, hR, -⟩ := (medianWallSystem hadj hsq).edge_unique a b hab
    have hRmem : (R : Vx → Vx → Prop) ∈ (M.toMedianGraph).Walls := R.2
    have hcross : ¬ (R : Vx → Vx → Prop) a b := (wallLabel_eq_one_iff R a b).mp hR
    -- every edge of the hyperplane crosses `R`
    have hle : ∀ c d : Vx, S.hypLabel H c d = 1 →
        (medianWallSystem hadj hsq).χ R c d = 1 := by
      intro c d hcd
      obtain ⟨-, hcdH⟩ := hypLabel_eq_one_iff.mp hcd
      exact (wallLabel_eq_one_iff R c d).mpr
        ((crossesWall_of_hypOf_eq hadj hsq hRmem (hcdH.trans hH.symm)).mpr hcross)
    calc crossCount (S.hypLabel H) l
        ≤ crossCount ((medianWallSystem hadj hsq).χ R) l := crossCount_mono hle l
      _ ≤ 1 := median_geodesic_crossings hadj hsq x₀ u v l hl R
  · push_neg at hedge
    have hzero : ∀ a b : Vx, S.hypLabel H a b = 0 := by
      intro a b
      by_cases h : S.adj a b ∧ S.hypOf a b = H
      · exact absurd h.2 (hedge a b h.1)
      · simp [hypLabel, h]
    have : crossCount (S.hypLabel H) l = 0 := crossCount_eq_zero_of_label_zero hzero l
    omega

end Compatible

end SquareComplex

namespace MedianSimpleGraph

open SquareComplex

/-- **The criterion is not vacuous.**  For the square complex of a median graph all the hypotheses
of `FiniteChains.SquareComplex.medianSimpleGraph_of_criterion` are satisfied: the complex is
connected and simply connected, the one-skeleton satisfies the quadrangle condition, and the
halfspaces of the hyperplanes are convex. -/
theorem criterion_hypotheses (M : MedianSimpleGraph Vx) :
    (M.toSquareComplex).SimplyConnected ∧ QuadrangleCondition M.G ∧
      ∃ σ : (M.toSquareComplex).Hyp → Vx → ZMod 2,
        (∀ (H : (M.toSquareComplex).Hyp) (u v : Vx), (M.toSquareComplex).adj u v →
            σ H u + σ H v = (M.toSquareComplex).hypLabel H u v) ∧
          HalfspaceConvex (S := M.toSquareComplex) M.G σ := by
  classical
  have hadj : ∀ a b : Vx, (M.toSquareComplex).adj a b ↔ M.G.Adj a b := M.toSquareComplex_adj
  have hsq : ∀ {a b c d : Vx}, (M.toSquareComplex).sq a b c d → a ≠ c ∧ b ≠ d :=
    fun h => M.toSquareComplex_sq_nondeg h
  have hSC : (M.toSquareComplex).SimplyConnected := M.toSquareComplex_simplyConnected
  refine ⟨hSC, M.quadrangleCondition, ?_⟩
  obtain ⟨σ, -, hσ, -, -⟩ :=
    exists_hypCoordinates (S := M.toSquareComplex) hSC
      (walkConnected_of_adj_connected hadj M.conn M.base)
  refine ⟨σ, hσ, ?_⟩
  exact halfspaceConvex_of_geodesic_crossings hadj M.conn hσ
    (median_hyp_geodesic_crossings hadj hsq M.base)

end MedianSimpleGraph

end FiniteChains
