module

public import RequestProject.NervePrism

@[expose] public section

/-!
# Chains supported on a subposet, and the chain-level gluing (Mayer–Vietoris) step

This file provides the coefficient-level technique that the chamber route needs in order to pass
from `π₁` to homology: the subgroup of chains of the nerve *supported on a subposet*, the
characterisation of that subgroup by the support of a chain, and the resulting gluing lemma.

* `FiniteChains.Nerve.mem_closure_image_of_iff` — a chain lies in the subgroup generated by a set
  of basis elements exactly when its support consists of those basis elements.  This is the
  "criterion through the support" the whole argument rests on.
* `FiniteChains.Nerve.IncOn A` — the subgroup `C_*(A) ⊆ ℤ[List P]` generated by the increasing
  lists all of whose vertices satisfy `A`.  In degree `n` its generators are exactly the
  admissible increasing lists of length `n + 1` with vertices in `A`.
* `FiniteChains.Nerve.incOn_inf` — `C_*(A) ⊓ C_*(B) = C_*(A ∩ B)`.
* `FiniteChains.Nerve.exists_split_of_unmixed` — under the "unmixedness" hypothesis (every
  comparable pair of the union lies in a single piece) every chain of `C_*(A ∪ B)` splits as
  `a + b` with `a ∈ C_*(A)`, `b ∈ C_*(B)`; the splitting is defined on the basis, by putting a
  list into `a` iff all its vertices are in `A`.
* `FiniteChains.Nerve.incOn_sup_of_unmixed` — `C_*(A ∪ B) = C_*(A) + C_*(B)`.
* `FiniteChains.Nerve.exists_bdry_eq_of_cycle_union` — **the gluing computation**: if cycles are
  filled in `A`, in `B` and in `A ∩ B`, then they are filled in `A ∪ B`.  For a cycle `z = a + b`
  one has `∂a = -∂b ∈ C_*(A ∩ B)`; filling that cycle by `u` makes `a - u` and `b + u` cycles of
  the two pieces, and the sum of their fillings fills `z`.
* `FiniteChains.Nerve.exists_bdry_eq_of_cycle_incOn_of_subtype` — transfer: acyclicity of the
  order complex of the subposet `{p // A p}` (the form in which the contractions of the project
  are stated) gives acyclicity of `C_*(A)` inside `ℤ[List P]`.

All statements are degree-free: they speak about the whole augmented complex at once, which is
how the contractions of `RequestProject/NervePrism.lean` are stated.  In particular the boundary
`∂₃` and the chains `C₃` are kept throughout; nothing here truncates the complex.
-/

namespace FiniteChains
namespace Nerve

universe u

open FreeAbelianGroup

/-! ### The support criterion -/

section Support

variable {X : Type u}

/-- **Membership in the subgroup generated by a set of basis elements, read off the support.** -/
theorem mem_closure_image_of_iff (S : Set X) (x : FreeAbelianGroup X) :
    x ∈ AddSubgroup.closure (FreeAbelianGroup.of '' S) ↔ ∀ y ∈ x.support, y ∈ S := by
  classical
  constructor
  · intro hx
    refine AddSubgroup.closure_induction (p := fun z _ => ∀ y ∈ z.support, y ∈ S) ?_ ?_ ?_ ?_ hx
    · rintro z ⟨l, hl, rfl⟩
      intro y hy
      rw [support_of, Finset.mem_singleton] at hy
      exact hy ▸ hl
    · simp
    · intro u v _ _ hu hv y hy
      rcases Finset.mem_union.1 (support_add u v hy) with h | h
      exacts [hu y h, hv y h]
    · intro u _ hu y hy
      rw [support_neg] at hy
      exact hu y hy
  · intro h
    have key : ∀ f : X →₀ ℤ, (∀ y ∈ f.support, y ∈ S) →
        (equivFinsupp X).symm f ∈ AddSubgroup.closure (FreeAbelianGroup.of '' S) := by
      intro f
      induction f using Finsupp.induction with
      | zero => intro _; simp
      | @single_add a b f ha hb ih =>
          intro hsup
          have hsupport : (Finsupp.single a b + f).support = Finset.cons a f.support ha :=
            Finsupp.support_single_add ha hb
          have haS : a ∈ S := hsup a (by rw [hsupport]; exact Finset.mem_cons_self _ _)
          have hfS : ∀ y ∈ f.support, y ∈ S := by
            intro y hy
            exact hsup y (by rw [hsupport]; exact Finset.mem_cons_of_mem hy)
          have hsingle : (equivFinsupp X).symm (Finsupp.single a b) = b • FreeAbelianGroup.of a := by
            apply (equivFinsupp X).injective
            simp [equivFinsupp]
          rw [map_add, hsingle]
          refine AddSubgroup.add_mem _ ?_ (ih hfS)
          exact AddSubgroup.zsmul_mem _
            (AddSubgroup.subset_closure (Set.mem_image_of_mem _ haS)) b
    have hx : x = (equivFinsupp X).symm ((equivFinsupp X) x) := by simp
    rw [hx]
    exact key _ h

end Support

/-! ### Chains supported on a subposet -/

variable {P Q : Type u} [Preorder P]

/-- The admissible increasing lists with all vertices in `A`. -/
def IncLists (A : P → Prop) : Set (List P) :=
  {l : List P | List.IsChain (· ≤ ·) l ∧ ∀ a ∈ l, A a}

/-- **The chains supported on the subposet `A`**: the subgroup `C_*(A)` of `ℤ[List P]` generated
by the increasing lists whose vertices all satisfy `A`. -/
def IncOn (A : P → Prop) : AddSubgroup (Ch P) :=
  AddSubgroup.closure (FreeAbelianGroup.of '' IncLists A)

/-- **The support criterion for `C_*(A)`.** -/
theorem mem_incOn_iff {A : P → Prop} (x : Ch P) :
    x ∈ IncOn A ↔ ∀ l ∈ x.support, List.IsChain (· ≤ ·) l ∧ ∀ a ∈ l, A a :=
  mem_closure_image_of_iff _ x

theorem of_mem_incOn {A : P → Prop} {l : List P} (hl : List.IsChain (· ≤ ·) l)
    (hA : ∀ a ∈ l, A a) : FreeAbelianGroup.of l ∈ IncOn A :=
  AddSubgroup.subset_closure ⟨l, ⟨hl, hA⟩, rfl⟩

/-- The support criterion for the full complex of increasing chains. -/
theorem mem_inc_iff (x : Ch P) :
    x ∈ Inc P ↔ ∀ l ∈ x.support, List.IsChain (· ≤ ·) l := by
  have hset : {x : Ch P | ∃ l : List P, List.IsChain (· ≤ ·) l ∧ x = FreeAbelianGroup.of l} =
      FreeAbelianGroup.of '' {l : List P | List.IsChain (· ≤ ·) l} := by
    ext y
    constructor
    · rintro ⟨l, hl, rfl⟩; exact ⟨l, hl, rfl⟩
    · rintro ⟨l, hl, rfl⟩; exact ⟨l, hl, rfl⟩
  rw [Inc, hset]
  exact mem_closure_image_of_iff _ x

theorem incOn_le_inc (A : P → Prop) : IncOn A ≤ Inc P := by
  intro x hx
  rw [mem_inc_iff]
  intro l hl
  exact ((mem_incOn_iff x).1 hx l hl).1

theorem incOn_mono {A B : P → Prop} (h : ∀ p, A p → B p) : IncOn A ≤ IncOn B := by
  intro x hx
  rw [mem_incOn_iff] at hx ⊢
  intro l hl
  exact ⟨(hx l hl).1, fun a ha => h a ((hx l hl).2 a ha)⟩

theorem incOn_congr {A B : P → Prop} (h : ∀ p, A p ↔ B p) : IncOn A = IncOn B :=
  le_antisymm (incOn_mono fun p hp => (h p).1 hp) (incOn_mono fun p hp => (h p).2 hp)

/-- **`C_*(A) ∩ C_*(B) = C_*(A ∩ B)`.** -/
theorem incOn_inf (A B : P → Prop) :
    IncOn A ⊓ IncOn B = IncOn (fun p => A p ∧ B p) := by
  ext x
  simp only [AddSubgroup.mem_inf, mem_incOn_iff]
  constructor
  · rintro ⟨hA, hB⟩ l hl
    exact ⟨(hA l hl).1, fun a ha => ⟨(hA l hl).2 a ha, (hB l hl).2 a ha⟩⟩
  · intro h
    exact ⟨fun l hl => ⟨(h l hl).1, fun a ha => ((h l hl).2 a ha).1⟩,
      fun l hl => ⟨(h l hl).1, fun a ha => ((h l hl).2 a ha).2⟩⟩

/-! ### The boundary preserves `C_*(A)` -/

theorem consList_bdryOn_mem_incOn (A : P → Prop) :
    ∀ (l pre : List P), List.IsChain (· ≤ ·) (pre ++ l) → (∀ a ∈ pre ++ l, A a) →
      consList pre (bdryOn l) ∈ IncOn A := by
  intro l
  induction l with
  | nil => intro pre _ _; simp
  | cons a t ih =>
      intro pre hchain hall
      rw [bdryOn_cons, map_sub, consList_of, consList_consMap]
      refine AddSubgroup.sub_mem _ ?_ ?_
      · refine of_mem_incOn (isChain_append_of_isChain_append_cons hchain) ?_
        intro b hb
        rcases List.mem_append.1 hb with h | h
        · exact hall b (List.mem_append.2 (Or.inl h))
        · exact hall b (List.mem_append.2 (Or.inr (List.mem_cons_of_mem _ h)))
      · refine ih (pre ++ [a]) (by simpa using hchain) ?_
        intro b hb
        simp only [List.append_assoc, List.cons_append, List.nil_append] at hb
        exact hall b (by simpa using hb)

theorem bdryOn_mem_incOn {A : P → Prop} {l : List P} (hl : List.IsChain (· ≤ ·) l)
    (hA : ∀ a ∈ l, A a) : bdryOn l ∈ IncOn A := by
  have := consList_bdryOn_mem_incOn A l [] (by simpa using hl) (by simpa using hA)
  simpa using this

/-- The boundary preserves the chains supported on a subposet. -/
theorem bdry_mem_incOn {A : P → Prop} {x : Ch P} (hx : x ∈ IncOn A) : bdry x ∈ IncOn A := by
  refine AddSubgroup.closure_induction (p := fun y _ => bdry y ∈ IncOn A) ?_ ?_ ?_ ?_ hx
  · rintro y ⟨l, ⟨hl, hA⟩, rfl⟩
    simpa using bdryOn_mem_incOn hl hA
  · simp
  · intro y z _ _ hy hz
    simpa using AddSubgroup.add_mem _ hy hz
  · intro y _ hy
    simpa using AddSubgroup.neg_mem _ hy

/-! ### Unmixedness and the splitting of chains of a union -/

/-- Every increasing list with vertices in the union lies entirely in one of the two pieces.
This is where "unmixedness" of the covering is used: any two vertices of an increasing list are
comparable, so a vertex outside `A` forces every vertex into `B`. -/
theorem forall_mem_or_of_unmixed {A B U : P → Prop}
    (hmix : ∀ a b : P, a ≤ b → U a → U b → (A a ∧ A b) ∨ (B a ∧ B b))
    {l : List P} (hl : List.IsChain (· ≤ ·) l) (hlU : ∀ a ∈ l, U a) :
    (∀ a ∈ l, A a) ∨ (∀ a ∈ l, B a) := by
  by_cases hA : ∀ a ∈ l, A a
  · exact Or.inl hA
  · refine Or.inr ?_
    push Not at hA
    obtain ⟨c₀, hc₀l, hc₀⟩ := hA
    have hpair : ∀ x ∈ l, ∀ y ∈ l, x ≤ y ∨ y ≤ x := by
      have hpw : l.Pairwise (fun x y : P => x ≤ y ∨ y ≤ x) :=
        (List.IsChain.pairwise hl).imp (fun h => Or.inl h)
      intro x hx y hy
      by_cases hxy : x = y
      · exact Or.inl (le_of_eq hxy)
      · letI : Std.Symm (fun x y : P => x ≤ y ∨ y ≤ x) := ⟨fun _ _ h => h.symm⟩
        exact hpw.forall hx hy hxy
    intro c hc
    rcases hpair c₀ hc₀l c hc with h | h
    · rcases hmix c₀ c h (hlU c₀ hc₀l) (hlU c hc) with ⟨h1, _⟩ | ⟨_, h2⟩
      · exact absurd h1 hc₀
      · exact h2
    · rcases hmix c c₀ h (hlU c hc) (hlU c₀ hc₀l) with ⟨_, h2⟩ | ⟨h1, _⟩
      · exact absurd h2 hc₀
      · exact h1

/-- **Splitting a chain of the union.**  The decomposition is defined on the basis: a list goes
into `a` if all its vertices lie in `A`, and into `b` otherwise. -/
theorem exists_split_of_unmixed {A B U : P → Prop}
    (hmix : ∀ a b : P, a ≤ b → U a → U b → (A a ∧ A b) ∨ (B a ∧ B b))
    {z : Ch P} (hz : z ∈ IncOn U) :
    ∃ a ∈ IncOn A, ∃ b ∈ IncOn B, z = a + b := by
  refine AddSubgroup.closure_induction
    (p := fun y _ => ∃ a ∈ IncOn A, ∃ b ∈ IncOn B, y = a + b) ?_ ?_ ?_ ?_ hz
  · rintro y ⟨l, ⟨hl, hlU⟩, rfl⟩
    rcases forall_mem_or_of_unmixed hmix hl hlU with h | h
    · exact ⟨FreeAbelianGroup.of l, of_mem_incOn hl h, 0, AddSubgroup.zero_mem _, by simp⟩
    · exact ⟨0, AddSubgroup.zero_mem _, FreeAbelianGroup.of l, of_mem_incOn hl h, by simp⟩
  · exact ⟨0, AddSubgroup.zero_mem _, 0, AddSubgroup.zero_mem _, by simp⟩
  · rintro y z _ _ ⟨a, ha, b, hb, rfl⟩ ⟨a', ha', b', hb', rfl⟩
    exact ⟨a + a', AddSubgroup.add_mem _ ha ha', b + b', AddSubgroup.add_mem _ hb hb', by abel⟩
  · rintro y _ ⟨a, ha, b, hb, rfl⟩
    exact ⟨-a, AddSubgroup.neg_mem _ ha, -b, AddSubgroup.neg_mem _ hb, by abel⟩

/-- **`C_*(A ∪ B) = C_*(A) + C_*(B)`** for an unmixed covering. -/
theorem incOn_sup_of_unmixed {A B U : P → Prop}
    (hU : ∀ p, U p ↔ (A p ∨ B p))
    (hmix : ∀ a b : P, a ≤ b → U a → U b → (A a ∧ A b) ∨ (B a ∧ B b)) :
    IncOn U = IncOn A ⊔ IncOn B := by
  refine le_antisymm ?_ ?_
  · intro z hz
    obtain ⟨a, ha, b, hb, rfl⟩ := exists_split_of_unmixed hmix hz
    exact AddSubgroup.add_mem _ (AddSubgroup.mem_sup_left ha) (AddSubgroup.mem_sup_right hb)
  · refine sup_le (incOn_mono fun p hp => (hU p).2 (Or.inl hp))
      (incOn_mono fun p hp => (hU p).2 (Or.inr hp))

/-! ### The gluing computation -/

/-- Acyclicity of the part of the complex supported on `A`: every cycle supported on `A` is the
boundary of a chain supported on `A`. -/
def AcyclicIn (A : P → Prop) : Prop :=
  ∀ x ∈ IncOn A, bdry x = 0 → ∃ y ∈ IncOn A, bdry y = x

theorem acyclicIn_congr {A B : P → Prop} (h : ∀ p, A p ↔ B p) (hA : AcyclicIn A) :
    AcyclicIn B := by
  have hAB : IncOn A = IncOn B := incOn_congr h
  intro x hx hcyc
  obtain ⟨y, hy, hdy⟩ := hA x (by rw [hAB]; exact hx) hcyc
  exact ⟨y, by rwa [hAB] at hy, hdy⟩

/-- **The chain-level gluing step.**  If the two pieces and their intersection have vanishing
homology (in all degrees, in the augmented complex), so does their union. -/
theorem acyclicIn_union_of_unmixed {A B U : P → Prop}
    (hU : ∀ p, U p ↔ (A p ∨ B p))
    (hmix : ∀ a b : P, a ≤ b → U a → U b → (A a ∧ A b) ∨ (B a ∧ B b))
    (hA : AcyclicIn A) (hB : AcyclicIn B) (hJ : AcyclicIn (fun p => A p ∧ B p)) :
    AcyclicIn U := by
  intro z hz hcyc
  obtain ⟨a, ha, b, hb, rfl⟩ := exists_split_of_unmixed hmix hz
  -- `t = ∂a = -∂b` is a cycle supported on the intersection
  have hda : bdry a ∈ IncOn A := bdry_mem_incOn ha
  have hdb : bdry b ∈ IncOn B := bdry_mem_incOn hb
  have hsum : bdry a + bdry b = 0 := by rw [← map_add]; exact hcyc
  have hdaB : bdry a ∈ IncOn B := by
    have : bdry a = -bdry b := by linear_combination (norm := abel) hsum
    rw [this]
    exact AddSubgroup.neg_mem _ hdb
  have htJ : bdry a ∈ IncOn (fun p => A p ∧ B p) := by
    rw [← incOn_inf]
    exact ⟨hda, hdaB⟩
  obtain ⟨u, hu, hdu⟩ := hJ (bdry a) htJ (by simp [bdry_bdry])
  have huA : u ∈ IncOn A := (incOn_mono (fun p hp => hp.1)) hu
  have huB : u ∈ IncOn B := (incOn_mono (fun p hp => hp.2)) hu
  -- `a - u` and `b + u` are cycles of the two pieces
  obtain ⟨p, hp, hdp⟩ := hA (a - u) (AddSubgroup.sub_mem _ ha huA) (by
    rw [map_sub, hdu, sub_self])
  obtain ⟨q, hq, hdq⟩ := hB (b + u) (AddSubgroup.add_mem _ hb huB) (by
    rw [map_add, hdu]
    linear_combination (norm := abel) hsum)
  refine ⟨p + q, AddSubgroup.add_mem _ ?_ ?_, ?_⟩
  · exact incOn_mono (fun r hr => (hU r).2 (Or.inl hr)) hp
  · exact incOn_mono (fun r hr => (hU r).2 (Or.inr hr)) hq
  · rw [map_add, hdp, hdq]
    abel

/-! ### Transfer between a subposet and the chains supported on it -/

section Transfer

variable (A : P → Prop)

theorem cmap_val_mem_incOn {x : Ch {p : P // A p}} (hx : x ∈ Inc {p : P // A p}) :
    cmap (Subtype.val) x ∈ IncOn A := by
  refine AddSubgroup.closure_induction (p := fun y _ => cmap (Subtype.val) y ∈ IncOn A)
    ?_ ?_ ?_ ?_ hx
  · rintro y ⟨l, hl, rfl⟩
    rw [cmap_of]
    refine of_mem_incOn ?_ ?_
    · exact List.isChain_map_of_isChain (Subtype.val : {p : P // A p} → P) (fun _ _ h => h) hl
    · intro a ha
      obtain ⟨b, -, rfl⟩ := List.mem_map.1 ha
      exact b.2
  · simp
  · intro y z _ _ hy hz
    simpa using AddSubgroup.add_mem _ hy hz
  · intro y _ hy
    simpa using AddSubgroup.neg_mem _ hy

theorem exists_preimage_of_mem_incOn {x : Ch P} (hx : x ∈ IncOn A) :
    ∃ x' ∈ Inc {p : P // A p}, cmap (Subtype.val) x' = x := by
  refine AddSubgroup.closure_induction
    (p := fun y _ => ∃ y' ∈ Inc {p : P // A p}, cmap (Subtype.val) y' = y) ?_ ?_ ?_ ?_ hx
  · rintro y ⟨l, ⟨hl, hA⟩, rfl⟩
    refine ⟨FreeAbelianGroup.of (l.attachWith A hA), of_mem_inc ?_, ?_⟩
    · have hmap : (l.attachWith A hA).map Subtype.val = l := by
        simp
      have : List.IsChain (· ≤ ·) ((l.attachWith A hA).map (Subtype.val : {p // A p} → P)) := by
        rw [hmap]; exact hl
      exact List.isChain_of_isChain_map (f := (Subtype.val : {p // A p} → P))
        (fun _ _ h => h) this
    · rw [cmap_of]
      simp
  · exact ⟨0, AddSubgroup.zero_mem _, by simp⟩
  · rintro y z _ _ ⟨y', hy', rfl⟩ ⟨z', hz', rfl⟩
    exact ⟨y' + z', AddSubgroup.add_mem _ hy' hz', by simp⟩
  · rintro y _ ⟨y', hy', rfl⟩
    exact ⟨-y', AddSubgroup.neg_mem _ hy', by simp⟩

omit [Preorder P] in
/-- The pushforward along the inclusion of a nonempty subposet is injective: it has the
retraction induced by any retraction of the inclusion of types. -/
theorem cmap_val_injective (hne : ∃ p : P, A p) :
    Function.Injective (cmap (Subtype.val : {p : P // A p} → P)) := by
  classical
  obtain ⟨p₀, hp₀⟩ := hne
  set r : P → {p : P // A p} := fun p => if h : A p then ⟨p, h⟩ else ⟨p₀, hp₀⟩ with hr
  have hcomp : ∀ q : {p : P // A p}, r q.1 = q := by
    intro q
    simp [hr, q.2]
  intro x y hxy
  have h : ∀ z : Ch {p : P // A p}, cmap r (cmap (Subtype.val) z) = z := by
    intro z
    refine ext_apply (F := (cmap r).comp (cmap (Subtype.val : {p : P // A p} → P)))
      (G := AddMonoidHom.id _) ?_ z
    intro l
    simp only [AddMonoidHom.coe_comp, Function.comp_apply, cmap_of, List.map_map,
      AddMonoidHom.id_apply]
    congr 1
    have : (fun q : {p : P // A p} => r q.1) = id := by
      funext q; exact hcomp q
    simp [Function.comp_def, this]
  have := congrArg (cmap r) hxy
  rwa [h, h] at this

/-- **Transfer of acyclicity from the subposet to the chains supported on it.** -/
theorem acyclicIn_of_subtype (hne : ∃ p : P, A p)
    (hsub : ∀ x ∈ Inc {p : P // A p}, bdry x = 0 →
      ∃ y ∈ Inc {p : P // A p}, bdry y = x) :
    AcyclicIn A := by
  intro x hx hcyc
  obtain ⟨x', hx', rfl⟩ := exists_preimage_of_mem_incOn A hx
  have hcyc' : bdry x' = 0 := by
    refine cmap_val_injective A hne ?_
    rw [cmap_bdry, hcyc, map_zero]
  obtain ⟨y', hy', hdy'⟩ := hsub x' hx' hcyc'
  exact ⟨cmap (Subtype.val) y', cmap_val_mem_incOn A hy', by rw [← cmap_bdry, hdy']⟩

end Transfer

end Nerve
end FiniteChains
