module

public import RequestProject.NerveRelativeGluing
public import RequestProject.NerveDegree

@[expose] public section

/-! Relative generation in a specified degree needs intersection fillings only
one degree lower, and does not require augmented acyclicity of disconnected pieces. -/
namespace FiniteChains.Nerve
universe u
variable {P : Type u} [Preorder P]

/-- All homogeneous increasing cycles of list length `n` supported on `U` bound. -/
def FillsDegreeIn (U : P → Prop) (n : ℕ) : Prop :=
  ∀ z ∈ IncOn U, lengthProjection n z = z → bdry z = 0 →
    ∃ y ∈ IncOn U, bdry y = z

/-- Homogeneous cycles of list length `n` are generated by cycles on `Base`,
modulo genuine full-nerve boundaries supported on `U`. -/
def GeneratesDegreeIn (U Base : P → Prop) (n : ℕ) : Prop :=
  ∀ z ∈ IncOn U, lengthProjection n z = z → bdry z = 0 →
    ∃ c ∈ IncOn Base, ∃ y ∈ IncOn U, bdry c = 0 ∧ z = c + bdry y

theorem generatesDegreeIn_of_acyclicRelIn {U Base : P → Prop} {n : ℕ}
    (h : AcyclicRelIn U Base) : GeneratesDegreeIn U Base n := by
  intro z hz _ hc
  exact h z hz hc

theorem generatesDegreeIn_of_fillsDegreeIn {U Base : P → Prop} {n : ℕ}
    (h : FillsDegreeIn U n) : GeneratesDegreeIn U Base n := by
  intro z hz hd hc
  obtain ⟨y, hy, hdy⟩ := h z hz hd hc
  exact ⟨0, AddSubgroup.zero_mem _, y, hy, by simp, by rw [hdy, zero_add]⟩

theorem generatesDegreeIn_union_of_unmixed {A B U Base : P → Prop} {n : ℕ}
    (hU : ∀ p, U p ↔ (A p ∨ B p))
    (hmix : ∀ a b : P, a ≤ b → U a → U b → (A a ∧ A b) ∨ (B a ∧ B b))
    (hA : GeneratesDegreeIn A Base (n + 1))
    (hB : GeneratesDegreeIn B Base (n + 1))
    (hJ : FillsDegreeIn (fun p => A p ∧ B p) n) :
    GeneratesDegreeIn U Base (n + 1) := by
  intro z hz hdeg hcyc
  obtain ⟨a₀, ha₀, b₀, hb₀, hsplit⟩ := exists_split_of_unmixed hmix hz
  let a := lengthProjection (n + 1) a₀
  let b := lengthProjection (n + 1) b₀
  have ha : a ∈ IncOn A := lengthProjection_mem_incOn _ ha₀
  have hb : b ∈ IncOn B := lengthProjection_mem_incOn _ hb₀
  have had : lengthProjection (n + 1) a = a := lengthProjection_idempotent _ _
  have hbd : lengthProjection (n + 1) b = b := lengthProjection_idempotent _ _
  have hab : z = a + b := by
    rw [← hdeg, hsplit, map_add]
  have hda : bdry a ∈ IncOn A := bdry_mem_incOn ha
  have hdb : bdry b ∈ IncOn B := bdry_mem_incOn hb
  have hsum : bdry a + bdry b = 0 := by rw [← map_add, ← hab]; exact hcyc
  have hdaB : bdry a ∈ IncOn B := by
    have h : bdry a = -bdry b := by linear_combination (norm := abel) hsum
    rw [h]
    exact AddSubgroup.neg_mem _ hdb
  have htJ : bdry a ∈ IncOn (fun p => A p ∧ B p) := by
    rw [← incOn_inf]
    exact ⟨hda, hdaB⟩
  have hdad : lengthProjection n (bdry a) = bdry a := by
    rw [lengthProjection_bdry, had]
  obtain ⟨u₀, hu₀, hdu₀⟩ := hJ (bdry a) htJ hdad (by simp [bdry_bdry])
  let t := lengthProjection (n + 1) u₀
  have ht : t ∈ IncOn (fun p => A p ∧ B p) := lengthProjection_mem_incOn _ hu₀
  have htd : lengthProjection (n + 1) t = t := lengthProjection_idempotent _ _
  have hdt : bdry t = bdry a := by
    dsimp only [t]
    rw [← lengthProjection_bdry, hdu₀, hdad]
  have htA : t ∈ IncOn A := incOn_mono (fun _ h => h.1) ht
  have htB : t ∈ IncOn B := incOn_mono (fun _ h => h.2) ht
  obtain ⟨c₁, hc₁, y₁, hy₁, hdc₁, he₁⟩ := hA (a - t)
    (AddSubgroup.sub_mem _ ha htA) (by rw [map_sub, had, htd])
    (by rw [map_sub, hdt, sub_self])
  obtain ⟨c₂, hc₂, y₂, hy₂, hdc₂, he₂⟩ := hB (b + t)
    (AddSubgroup.add_mem _ hb htB) (by rw [map_add, hbd, htd]) (by
      rw [map_add, hdt]
      linear_combination (norm := abel) hsum)
  refine ⟨c₁ + c₂, AddSubgroup.add_mem _ hc₁ hc₂, y₁ + y₂,
    AddSubgroup.add_mem _ ?_ ?_, ?_, ?_⟩
  · exact incOn_mono (fun r hr => (hU r).2 (Or.inl hr)) hy₁
  · exact incOn_mono (fun r hr => (hU r).2 (Or.inr hr)) hy₂
  · rw [map_add, hdc₁, hdc₂, add_zero]
  · have h : (a - t) + (b + t) = a + b := by abel
    rw [he₁, he₂] at h
    rw [hab, ← h, map_add]
    abel

end FiniteChains.Nerve
