module

public import RequestProject.OrderComplexGluing

@[expose] public section

/-!
# Homotopies of edge paths *inside* a subposet

`RequestProject/OrderComplexGluing.lean` works with paths of the ambient order complex whose
edges lie in a subposet (`FiniteChains.Comb.PathIn`), but with homotopies of the **ambient**
complex.  For the injectivity statements of the chamber argument one needs the finer notion:
a homotopy all of whose intermediate paths — and therefore all of whose elementary
cancellations, including the two-cells used — stay inside a subposet.

* `FiniteChains.Comb.StepIn A a b l l'` — one elementary cancellation between two paths, both
  of which lie inside `A`;
* `FiniteChains.Comb.HtpyIn A a b p q` — the equivalence relation generated by those steps;
* the usual path algebra for `HtpyIn` (`refl`, `symm`, `trans`, concatenation, cancelling a
  path against its reverse);
* `FiniteChains.Comb.HtpyIn.htpy` and `FiniteChains.Comb.HtpyIn.mono` — forgetting the
  subposet, and enlarging it;
* `FiniteChains.Comb.htpyIn_mapPath` — pushing a homotopy forward along a monotone map, and
  `FiniteChains.Comb.htpy_lift_of_htpyIn` — lifting a homotopy inside `A` to the order complex
  of the subposet `A` itself.  The two together let one move homotopies between a subposet and
  the ambient complex in both directions.

A two-cell of the order complex is a triple `x ≤ y ≤ z`; if both paths of an elementary
cancellation lie inside `A`, the two-cell used lies inside `A` as well, because all three of its
vertices occur as endpoints of the edges of the longer path.  This is why no separate condition
on two-cells is needed in the definition of `StepIn`.
-/

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains
namespace Comb

universe u

variable {P Q : Type u} [Preorder P] [Preorder Q]

/-- One elementary cancellation between two paths, both lying inside the subposet `A`. -/
def StepIn (A : P → Prop) (a b : P) (l l' : List ((orderCx P).E × Bool)) : Prop :=
  Step (orderCx P) a b l l' ∧ PathIn A l ∧ PathIn A l'

/-- **Homotopy of edge paths inside a subposet**: the equivalence relation generated by the
elementary cancellations through paths lying inside `A`. -/
def HtpyIn (A : P → Prop) (a b : P) (p q : List ((orderCx P).E × Bool)) : Prop :=
  Relation.ReflTransGen (fun l l' => StepIn A a b l l' ∨ StepIn A a b l' l) p q

namespace HtpyIn

variable {A B : P → Prop} {a b c d : P} {p q r : List ((orderCx P).E × Bool)}

theorem refl (p : List ((orderCx P).E × Bool)) : HtpyIn A a b p p := Relation.ReflTransGen.refl

theorem trans (h : HtpyIn A a b p q) (h' : HtpyIn A a b q r) : HtpyIn A a b p r :=
  Relation.ReflTransGen.trans h h'

theorem symm (h : HtpyIn A a b p q) : HtpyIn A a b q p := by
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail _ hstep ih =>
      exact Relation.ReflTransGen.trans (Relation.ReflTransGen.single hstep.symm) ih

theorem of_step (h : StepIn A a b p q) : HtpyIn A a b p q :=
  Relation.ReflTransGen.single (Or.inl h)

/-- Forgetting the subposet: a homotopy inside `A` is a homotopy of the ambient complex. -/
theorem htpy (h : HtpyIn A a b p q) : Htpy (orderCx P) a b p q :=
  Relation.ReflTransGen.mono (fun _ _ hs => hs.imp (fun h => h.1) (fun h => h.1)) _ _ h

/-- Enlarging the subposet. -/
theorem mono (hAB : ∀ x, A x → B x) (h : HtpyIn A a b p q) : HtpyIn B a b p q :=
  Relation.ReflTransGen.mono
    (fun _ _ hs => hs.imp
      (fun h => ⟨h.1, pathIn_mono hAB h.2.1, pathIn_mono hAB h.2.2⟩)
      (fun h => ⟨h.1, pathIn_mono hAB h.2.1, pathIn_mono hAB h.2.2⟩)) _ _ h

/-- A homotopy inside `A` preserves the property of lying inside `A`. -/
theorem pathIn (h : HtpyIn A a b p q) (hp : PathIn A p) : PathIn A q := by
  induction h with
  | refl => exact hp
  | tail _ hstep ih =>
      rcases hstep with hs | hs
      · exact hs.2.2
      · exact hs.2.1

theorem isPath (h : HtpyIn A a b p q)
    (hp : IsPath (orderCx P).src (orderCx P).tgt p a b) :
    IsPath (orderCx P).src (orderCx P).tgt q a b := Htpy.isPath h.htpy hp

end HtpyIn

/-- An elementary cancellation survives inside a longer path. -/
theorem StepIn.append {A : P → Prop} {a b c d : P} {l l' : List ((orderCx P).E × Bool)}
    (h : StepIn A a b l l') {r s : List ((orderCx P).E × Bool)}
    (hr : IsPath (orderCx P).src (orderCx P).tgt r c a)
    (hs : IsPath (orderCx P).src (orderCx P).tgt s b d)
    (hrA : PathIn A r) (hsA : PathIn A s) :
    StepIn A c d (r ++ l ++ s) (r ++ l' ++ s) :=
  ⟨h.1.append hr hs, pathIn_append (pathIn_append hrA h.2.1) hsA,
    pathIn_append (pathIn_append hrA h.2.2) hsA⟩

theorem HtpyIn.congr_append {A : P → Prop} {a b c d : P} {p q : List ((orderCx P).E × Bool)}
    (h : HtpyIn A a b p q) {r s : List ((orderCx P).E × Bool)}
    (hr : IsPath (orderCx P).src (orderCx P).tgt r c a)
    (hs : IsPath (orderCx P).src (orderCx P).tgt s b d)
    (hrA : PathIn A r) (hsA : PathIn A s) :
    HtpyIn A c d (r ++ p ++ s) (r ++ q ++ s) := by
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail _ hstep ih =>
      refine Relation.ReflTransGen.tail ih ?_
      rcases hstep with h | h
      · exact Or.inl (h.append hr hs hrA hsA)
      · exact Or.inr (h.append hr hs hrA hsA)

/-- Homotopies inside `A` may be concatenated. -/
theorem HtpyIn.append_congr {A : P → Prop} {a b c : P} {p p' q q' : List ((orderCx P).E × Bool)}
    (hp : IsPath (orderCx P).src (orderCx P).tgt p a b)
    (hq : IsPath (orderCx P).src (orderCx P).tgt q b c)
    (hpA : PathIn A p) (hqA : PathIn A q)
    (h : HtpyIn A a b p p') (h' : HtpyIn A b c q q') :
    HtpyIn A a c (p ++ q) (p' ++ q') := by
  have hp' : IsPath (orderCx P).src (orderCx P).tgt p' a b := h.isPath hp
  have hp'A : PathIn A p' := h.pathIn hpA
  have h1 : HtpyIn A a c (p ++ q) (p' ++ q) := by
    simpa using
      h.congr_append (r := ([] : List ((orderCx P).E × Bool))) (s := q) rfl hq (pathIn_nil A) hqA
  have h2 : HtpyIn A a c (p' ++ q) (p' ++ q') := by
    simpa using
      h'.congr_append (r := p') (s := ([] : List ((orderCx P).E × Bool))) hp' rfl hp'A
        (pathIn_nil A)
  exact h1.trans h2

/-- Cancelling a path against its reverse, inside `A`. -/
theorem htpyIn_append_revPath {A : P → Prop} {p : List ((orderCx P).E × Bool)} {a b : P}
    (hp : IsPath (orderCx P).src (orderCx P).tgt p a b) (hpA : PathIn A p) :
    HtpyIn A a a (p ++ revPath p) [] := by
  induction p generalizing a with
  | nil => cases hp; exact Relation.ReflTransGen.refl
  | cons eb p ih =>
      obtain ⟨ha, hrest⟩ := hp
      subst ha
      obtain ⟨hebA, hpA'⟩ := pathIn_of_cons hpA
      have hih : HtpyIn A (germTgt (orderCx P).src (orderCx P).tgt eb)
          (germTgt (orderCx P).src (orderCx P).tgt eb) (p ++ revPath p) [] := ih hrest hpA'
      have hebPath : IsPath (orderCx P).src (orderCx P).tgt [eb]
          (germSrc (orderCx P).src (orderCx P).tgt eb)
          (germTgt (orderCx P).src (orderCx P).tgt eb) := isPath_single eb
      have hrevPath : IsPath (orderCx P).src (orderCx P).tgt [revGerm eb]
          (germTgt (orderCx P).src (orderCx P).tgt eb)
          (germSrc (orderCx P).src (orderCx P).tgt eb) := by
        exact ⟨(germSrc_revGerm (X := orderCx P) eb).symm,
          germTgt_revGerm (X := orderCx P) eb⟩
      have hsingleA : PathIn A [eb] := pathIn_cons hebA (pathIn_nil A)
      have hrevA : PathIn A [revGerm eb] := pathIn_cons hebA (pathIn_nil A)
      have hcongr : HtpyIn A (germSrc (orderCx P).src (orderCx P).tgt eb)
          (germSrc (orderCx P).src (orderCx P).tgt eb)
          ([eb] ++ (p ++ revPath p) ++ [revGerm eb]) ([eb] ++ [] ++ [revGerm eb]) :=
        hih.congr_append hebPath hrevPath hsingleA hrevA
      have hrw : (eb :: p) ++ revPath (eb :: p) = [eb] ++ (p ++ revPath p) ++ [revGerm eb] := by
        simp [revPath, List.append_assoc]
      have hlast : HtpyIn A (germSrc (orderCx P).src (orderCx P).tgt eb)
          (germSrc (orderCx P).src (orderCx P).tgt eb) [eb, revGerm eb] [] := by
        refine HtpyIn.of_step ⟨⟨?_, rfl, Or.inl ⟨[], [], eb, rfl, rfl⟩⟩, ?_, pathIn_nil A⟩
        · exact ⟨rfl, (germSrc_revGerm (X := orderCx P) eb).symm,
            germTgt_revGerm (X := orderCx P) eb⟩
        · exact pathIn_cons hebA (pathIn_cons hebA (pathIn_nil A))
      rw [hrw]
      refine hcongr.trans ?_
      simpa using hlast

theorem htpyIn_revPath_append {A : P → Prop} {p : List ((orderCx P).E × Bool)} {a b : P}
    (hp : IsPath (orderCx P).src (orderCx P).tgt p a b) (hpA : PathIn A p) :
    HtpyIn A b b (revPath p ++ p) [] := by
  have h := htpyIn_append_revPath (isPath_revPath hp) (pathIn_revPath hpA)
  simpa using h

/-! ### Moving homotopies between a subposet and the ambient complex -/

/-- **Pushing a homotopy forward along a monotone map.**  If the values of `f` lie in the
subposet `C`, the image of a homotopy of the order complex of `Q` is a homotopy inside `C`. -/
theorem htpyIn_mapPath {C : P → Prop} (f : Q → P) (hf : Monotone f) (hC : ∀ x, C (f x))
    {a b : Q} {p q : List ((orderCx Q).E × Bool)} (h : Htpy (orderCx Q) a b p q) :
    HtpyIn C (f a) (f b) (mapPath (orderCxMap f hf) p) (mapPath (orderCxMap f hf) q) := by
  have hpathIn : ∀ l : List ((orderCx Q).E × Bool), PathIn C (mapPath (orderCxMap f hf) l) := by
    intro l e he
    simp only [mapPath, List.mem_map] at he
    obtain ⟨x, -, rfl⟩ := he
    exact ⟨hC _, hC _⟩
  have hstep : ∀ l l' : List ((orderCx Q).E × Bool), Step (orderCx Q) a b l l' →
      StepIn C (f a) (f b) (mapPath (orderCxMap f hf) l) (mapPath (orderCxMap f hf) l') := by
    intro l l' hs
    refine ⟨?_, hpathIn l, hpathIn l'⟩
    obtain ⟨hl, hl', hc⟩ := hs
    refine ⟨isPath_mapPath (orderCxMap f hf) hl, isPath_mapPath (orderCxMap f hf) hl', ?_⟩
    rcases hc with ⟨p', q', eb, hlEq, hl'Eq⟩ | ⟨p', q', t, hlEq, hl'Eq⟩
    · refine Or.inl ⟨mapPath (orderCxMap f hf) p', mapPath (orderCxMap f hf) q',
        ((orderCxMap f hf).onE eb.1, eb.2), ?_, ?_⟩
      · rw [hlEq]; simp [mapPath, revGerm]
      · rw [hl'Eq]; simp [mapPath]
    · refine Or.inr ⟨mapPath (orderCxMap f hf) p', mapPath (orderCxMap f hf) q',
        (orderCxMap f hf).onF t, ?_, ?_⟩
      · rw [hlEq]
        have hatt : mapPath (orderCxMap f hf) ((orderCx Q).att t) =
            (orderCx P).att ((orderCxMap f hf).onF t) := by
          rw [(orderCxMap f hf).att_onF t]; rfl
        simp [mapPath, orderCxMap, orderCx]
      · rw [hl'Eq]; simp [mapPath]
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail _ hs ih =>
      rcases hs with hel | hel
      · exact ih.trans (HtpyIn.of_step (hstep _ _ hel))
      · exact ih.trans (HtpyIn.of_step (hstep _ _ hel)).symm

/-! ### Lifting a homotopy inside `A` to the order complex of `A` -/

section Lift

variable {C : P → Prop}

theorem liftPathIn_append (l l' : List ((orderCx P).E × Bool)) (h : PathIn C l)
    (h' : PathIn C l') (hall : PathIn C (l ++ l')) :
    liftPathIn (A := C) (l ++ l') hall = liftPathIn l h ++ liftPathIn l' h' := by
  induction l with
  | nil => rfl
  | cons e t ih =>
      simp only [List.cons_append, liftPathIn, List.cons.injEq, true_and]
      exact ih (pathIn_of_cons h).2 (pathIn_of_cons hall).2

theorem liftGermIn_revGerm (e : (orderCx P).E × Bool) (h : C e.1.1.1 ∧ C e.1.1.2)
    (h' : C (revGerm e).1.1.1 ∧ C (revGerm e).1.1.2) :
    liftGermIn (A := C) (revGerm e) h' = revGerm (liftGermIn (A := C) e h) := rfl

/-- The lift of the attaching path of a two-cell whose vertices lie in `C` is the attaching
path of the corresponding two-cell of the subposet. -/
theorem liftPathIn_att (t : OrdTri P) (hx : C t.1.1) (hy : C t.1.2.1) (hz : C t.1.2.2)
    (h : PathIn C ((orderCx P).att t)) :
    liftPathIn (A := C) ((orderCx P).att t) h =
      (orderCx {x : P // C x}).att
        (⟨(⟨t.1.1, hx⟩, ⟨t.1.2.1, hy⟩, ⟨t.1.2.2, hz⟩), t.2.1, t.2.2⟩ : OrdTri {x : P // C x}) :=
  rfl

/-- **Lifting a homotopy inside `C` to the order complex of `C`.** -/
theorem htpy_lift_of_htpyIn {a b : P} {p q : List ((orderCx P).E × Bool)}
    (h : HtpyIn C a b p q) (ha : C a) (hb : C b) (hp : PathIn C p) (hq : PathIn C q) :
    Htpy (orderCx {x : P // C x}) ⟨a, ha⟩ ⟨b, hb⟩ (liftPathIn p hp) (liftPathIn q hq) := by
  have hstep : ∀ l l' : List ((orderCx P).E × Bool), ∀ (hl : PathIn C l) (hl' : PathIn C l'),
      StepIn C a b l l' →
      Step (orderCx {x : P // C x}) ⟨a, ha⟩ ⟨b, hb⟩ (liftPathIn l hl) (liftPathIn l' hl') := by
    intro l l' hl hl' hs
    obtain ⟨⟨hpl, hpl', hc⟩, -, -⟩ := hs
    refine ⟨isPath_liftPathIn l hl ha hb hpl, isPath_liftPathIn l' hl' ha hb hpl', ?_⟩
    rcases hc with ⟨p', q', eb, hlEq, hl'Eq⟩ | ⟨p', q', t, hlEq, hl'Eq⟩
    · subst hlEq
      subst hl'Eq
      have hp' : PathIn C p' := pathIn_of_append_left hl
      have hrest : PathIn C (eb :: revGerm eb :: q') := pathIn_of_append_right hl
      have heb : C eb.1.1.1 ∧ C eb.1.1.2 := (pathIn_of_cons hrest).1
      have hq' : PathIn C q' := (pathIn_of_cons (pathIn_of_cons hrest).2).2
      refine Or.inl ⟨liftPathIn p' hp', liftPathIn q' hq', liftGermIn eb heb, ?_, ?_⟩
      · rw [liftPathIn_append p' (eb :: revGerm eb :: q') hp' hrest]
        rfl
      · exact liftPathIn_append p' q' hp' hq' _
    · subst hlEq
      subst hl'Eq
      have hfront : PathIn C (p' ++ (orderCx P).att t) := pathIn_of_append_left hl
      have hp' : PathIn C p' := pathIn_of_append_left hfront
      have hatt : PathIn C ((orderCx P).att t) := pathIn_of_append_right hfront
      have hq' : PathIn C q' := pathIn_of_append_right hl
      have h1 := hatt ((⟨(t.1.1, t.1.2.1), t.2.1⟩ : OrdEdge P), true) (by simp [orderCx])
      have h2 := hatt ((⟨(t.1.2.1, t.1.2.2), t.2.2⟩ : OrdEdge P), true) (by simp [orderCx])
      have hx : C t.1.1 := h1.1
      have hy : C t.1.2.1 := h1.2
      have hz : C t.1.2.2 := h2.2
      refine Or.inr ⟨liftPathIn p' hp', liftPathIn q' hq',
        (⟨(⟨t.1.1, hx⟩, ⟨t.1.2.1, hy⟩, ⟨t.1.2.2, hz⟩), t.2.1, t.2.2⟩ : OrdTri {x : P // C x}),
        ?_, ?_⟩
      · rw [liftPathIn_append (p' ++ (orderCx P).att t) q' hfront hq',
          liftPathIn_append p' ((orderCx P).att t) hp' hatt,
          liftPathIn_att t hx hy hz hatt]
      · exact liftPathIn_append p' q' hp' hq' _
  revert hq
  induction h with
  | refl => intro hq; exact Htpy.refl _
  | @tail u v _ hs ih =>
      intro hq
      have hu : PathIn C u := by
        rcases hs with h' | h'
        · exact h'.2.1
        · exact h'.2.2
      refine (ih hu).trans ?_
      rcases hs with h' | h'
      · exact Htpy.of_step (hstep u v hu hq h')
      · exact (Htpy.of_step (hstep v u hq hu h')).symm

end Lift

end Comb
end FiniteChains
