import RequestProject.Pi2Generation
import RequestProject.HNNEmbedding

/-!
# The two extension steps of rule 1 really do contain the old group

`RequestProject/Pi2Generation.lean` proves the generation statement (3.3) for a
one-generator, one-relator extension from two hypotheses: right-regularity of the Fox
derivative of the new relator, and injectivity of the induced map of fundamental groups.
This file discharges the second hypothesis for the two extensions used in rule 1 of
Section 3.4.

* `FiniteChains.extHom_tietze_injective` — for the defining relator `z = s` the map of
  fundamental groups is injective (it is in fact an isomorphism, with the explicit retraction
  `FiniteChains.tietzeRetract`);
* `FiniteChains.extHom_hnn_injective` — for the stable-letter relator `z u z^{-1} = v` the map
  is injective whenever the images of `u` and `v` have infinite order, because the enlarged
  presentation maps onto the HNN extension identifying the two infinite cyclic subgroups,
  and the base group of an HNN extension embeds into it (Serre's normal form theorem, see
  `RequestProject/HNNEmbedding.lean`).

Consequently the two generation statements
`FiniteChains.extCycle_tietze_span_of` and `FiniteChains.extCycle_hnn_span_of` hold with no
hypothesis on the fundamental groups at all.
-/

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains

open MonoidAlgebra

universe u

variable {α : Type u} [Fintype α] [DecidableEq α] {J : Type u} [Fintype J] [DecidableEq J]
variable (ρ : J → FreeGroup α)

/-- Infinite order is inherited by the image under an injective homomorphism. -/
theorem not_isOfFinOrder_map_of_injective {M N : Type*} [Group M] [Group N] {f : M →* N}
    (hf : Function.Injective f) {x : M} (hx : ¬ IsOfFinOrder x) : ¬ IsOfFinOrder (f x) := by
  intro h
  obtain ⟨n, hn, hxn⟩ := isOfFinOrder_iff_pow_eq_one.1 h
  refine hx (isOfFinOrder_iff_pow_eq_one.2 ⟨n, hn, hf ?_⟩)
  rw [map_pow, hxn, map_one]

/-! ### The Tietze step -/

section Tietze

variable (s : FreeGroup α)

/-- The retraction of free groups sending the new generator to the word `s`. -/
def tietzeLift : FreeGroup (Option α) →* FreeGroup α :=
  FreeGroup.lift (fun o => o.elim s FreeGroup.of)

omit [Fintype α] [DecidableEq α] in
@[simp] theorem tietzeLift_of_none : tietzeLift s (FreeGroup.of none) = s := by
  simp [tietzeLift]

omit [Fintype α] [DecidableEq α] in
@[simp] theorem tietzeLift_map_some (w : FreeGroup α) :
    tietzeLift s (FreeGroup.map Option.some w) = w := by
  have h : (tietzeLift s).comp (FreeGroup.map Option.some) = MonoidHom.id _ :=
    FreeGroup.ext_hom _ _ fun a => by simp [tietzeLift]
  exact congrArg (fun f : FreeGroup α →* FreeGroup α => f w) h

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem tietze_relSub_le :
    relSub (extRel ρ (tietzeWord s)) ≤ (relSub ρ).comap (tietzeLift s) := by
  refine Subgroup.normalClosure_le_normal ?_
  rintro _ ⟨jo, rfl⟩
  refine Subgroup.mem_comap.2 ?_
  cases jo with
  | none =>
      have : tietzeLift s (extRel ρ (tietzeWord s) none) = 1 := by
        show tietzeLift s (tietzeWord s) = 1
        rw [tietzeWord, map_mul, map_inv, tietzeLift_of_none, tietzeLift_map_some, mul_inv_cancel]
      rw [this]
      exact one_mem _
  | some j =>
      have : tietzeLift s (extRel ρ (tietzeWord s) (some j)) = ρ j := by
        show tietzeLift s (FreeGroup.map Option.some (ρ j)) = ρ j
        rw [tietzeLift_map_some]
      rw [this]
      exact Subgroup.subset_normalClosure (Set.mem_range_self j)

/-- The retraction of the enlarged presented group onto the old one. -/
def tietzeRetract : PresGroup (extRel ρ (tietzeWord s)) →* PresGroup ρ :=
  QuotientGroup.map _ _ (tietzeLift s) (tietze_relSub_le ρ s)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
/-- **A Tietze extension does not change the fundamental group.** -/
theorem extHom_tietze_injective : Function.Injective (extHom ρ (tietzeWord s)) := by
  have hcomp : ∀ g : PresGroup ρ, tietzeRetract ρ s (extHom ρ (tietzeWord s) g) = g := by
    intro g
    induction g using QuotientGroup.induction_on with
    | H w =>
        show tietzeRetract ρ s (QuotientGroup.mk (FreeGroup.map Option.some w)) = _
        show (QuotientGroup.mk (tietzeLift s (FreeGroup.map Option.some w)) : PresGroup ρ) = _
        rw [tietzeLift_map_some]
  exact Function.LeftInverse.injective hcomp

end Tietze

/-! ### The stable-letter step -/

section HNN

variable (u v : FreeGroup α)
  (hu : ¬ IsOfFinOrder (QuotientGroup.mk u : PresGroup ρ))
  (hv : ¬ IsOfFinOrder (QuotientGroup.mk v : PresGroup ρ))

/-- The HNN extension of the old presented group identifying the infinite cyclic subgroups
generated by the images of `u` and `v`. -/
abbrev hnnTarget : Type u :=
  HNNExtension (PresGroup ρ) (Subgroup.zpowers (QuotientGroup.mk u : PresGroup ρ))
    (Subgroup.zpowers (QuotientGroup.mk v : PresGroup ρ)) (zpowersEquivZpowers hu hv)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
/-- The isomorphism of the two infinite cyclic subgroups sends the generator to the
generator. -/
theorem zpowersEquivZpowers_gen :
    (zpowersEquivZpowers hu hv)
        ⟨(QuotientGroup.mk u : PresGroup ρ), Subgroup.mem_zpowers _⟩
      = ⟨(QuotientGroup.mk v : PresGroup ρ), Subgroup.mem_zpowers _⟩ := by
  have hsymm : (zpowersEquivInt hu).symm
      ⟨(QuotientGroup.mk u : PresGroup ρ), Subgroup.mem_zpowers _⟩
      = Multiplicative.ofAdd (1 : ℤ) := by
    rw [MulEquiv.symm_apply_eq]
    exact Subtype.ext (by simp [zpowersEquivInt])
  show (zpowersEquivInt hv) ((zpowersEquivInt hu).symm _) = _
  rw [hsymm]
  exact Subtype.ext (by simp [zpowersEquivInt])

/-- The homomorphism of the free group on the enlarged generating set into the HNN
extension: the new generator goes to the stable letter. -/
noncomputable def hnnLift : FreeGroup (Option α) →* hnnTarget ρ u v hu hv :=
  FreeGroup.lift (fun o => o.elim HNNExtension.t
    (fun a => HNNExtension.of (QuotientGroup.mk (FreeGroup.of a))))

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem hnnLift_map_some (w : FreeGroup α) :
    hnnLift ρ u v hu hv (FreeGroup.map Option.some w)
      = HNNExtension.of (QuotientGroup.mk w) := by
  have h : (hnnLift ρ u v hu hv).comp (FreeGroup.map Option.some)
      = (HNNExtension.of (A := Subgroup.zpowers (QuotientGroup.mk u : PresGroup ρ))
          (B := Subgroup.zpowers (QuotientGroup.mk v : PresGroup ρ))
          (φ := zpowersEquivZpowers hu hv)).comp
        (QuotientGroup.mk' (relSub ρ)) :=
    FreeGroup.ext_hom _ _ fun a => by simp [hnnLift]
  exact congrArg (fun f : FreeGroup α →* hnnTarget ρ u v hu hv => f w) h

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem hnnLift_hnnWord : hnnLift ρ u v hu hv (hnnWord u v) = 1 := by
  have hconj := HNNExtension.equiv_eq_conj (φ := zpowersEquivZpowers hu hv)
    ⟨(QuotientGroup.mk u : PresGroup ρ), Subgroup.mem_zpowers _⟩
  rw [zpowersEquivZpowers_gen] at hconj
  have ht : hnnLift ρ u v hu hv (FreeGroup.of none) = HNNExtension.t := by
    simp [hnnLift]
  simp only [hnnWord, map_mul, map_inv, ht, hnnLift_map_some]
  show HNNExtension.t * HNNExtension.of (QuotientGroup.mk u) * HNNExtension.t⁻¹ *
      (HNNExtension.of (QuotientGroup.mk v))⁻¹ = 1
  rw [← hconj]
  simp

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem hnn_relSub_le :
    relSub (extRel ρ (hnnWord u v)) ≤ (hnnLift ρ u v hu hv).ker := by
  refine Subgroup.normalClosure_le_normal ?_
  rintro _ ⟨jo, rfl⟩
  cases jo with
  | none =>
      show hnnLift ρ u v hu hv (hnnWord u v) = 1
      exact hnnLift_hnnWord ρ u v hu hv
  | some j =>
      show hnnLift ρ u v hu hv (FreeGroup.map Option.some (ρ j)) = 1
      rw [hnnLift_map_some]
      have : (QuotientGroup.mk (ρ j) : PresGroup ρ) = 1 :=
        (QuotientGroup.eq_one_iff _).2 (Subgroup.subset_normalClosure (Set.mem_range_self j))
      rw [this, map_one]

/-- The map from the enlarged presented group to the HNN extension. -/
noncomputable def hnnComparison :
    PresGroup (extRel ρ (hnnWord u v)) →* hnnTarget ρ u v hu hv :=
  QuotientGroup.lift _ (hnnLift ρ u v hu hv) (hnn_relSub_le ρ u v hu hv)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
include hu hv in
/-- **The stable-letter extension contains the old group.**  The enlarged presented group
maps to the HNN extension identifying the two infinite cyclic subgroups, compatibly with the
inclusions of the old group, and the base group of an HNN extension embeds into it. -/
theorem extHom_hnn_injective : Function.Injective (extHom ρ (hnnWord u v)) := by
  have hcomp : ∀ g : PresGroup ρ,
      hnnComparison ρ u v hu hv (extHom ρ (hnnWord u v) g) = HNNExtension.of g := by
    intro g
    induction g using QuotientGroup.induction_on with
    | H w =>
        show hnnComparison ρ u v hu hv (QuotientGroup.mk (FreeGroup.map Option.some w)) = _
        show hnnLift ρ u v hu hv (FreeGroup.map Option.some w) = _
        rw [hnnLift_map_some]
  intro a b hab
  refine hnn_infiniteCyclic_of_injective hu hv ?_
  rw [← hcomp a, ← hcomp b, hab]

end HNN

/-! ### The generation statements without hypotheses on the fundamental groups -/

omit [Fintype α] [DecidableEq J] in
/-- **Rule 1, elimination step.**  Adjoining a generator `z` with the defining relator
`z = s` leaves `π₂` generated by the image of the old `π₂`. -/
theorem extCycle_tietze_span_of (s : FreeGroup α)
    {v : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ (tietzeWord s)))}
    (hv : IsFoxCycle (extRel ρ (tietzeWord s)) v) :
    v ∈ Submodule.span (MonoidAlgebra ℤ (PresGroup (extRel ρ (tietzeWord s))))
      {w | ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧
        w = extCycleImage ρ (tietzeWord s) y} :=
  extCycle_tietze_span ρ s (extHom_tietze_injective ρ s) hv

omit [Fintype α] [DecidableEq J] in
/-- **Rule 1, HNN step.**  Adjoining a stable letter `z` with the relator `z u z^{-1} = v`,
where the images of `u` and `v` have infinite order, leaves `π₂` generated by the image of
the old `π₂`. -/
theorem extCycle_hnn_span_of (u v : FreeGroup α)
    (hu : ¬ IsOfFinOrder (QuotientGroup.mk u : PresGroup ρ))
    (hv : ¬ IsOfFinOrder (QuotientGroup.mk v : PresGroup ρ))
    {c : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ (hnnWord u v)))}
    (hc : IsFoxCycle (extRel ρ (hnnWord u v)) c) :
    c ∈ Submodule.span (MonoidAlgebra ℤ (PresGroup (extRel ρ (hnnWord u v))))
      {w | ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧
        w = extCycleImage ρ (hnnWord u v) y} := by
  have hinj := extHom_hnn_injective ρ u v hu hv
  have hord : ¬ IsOfFinOrder (QuotientGroup.mk (FreeGroup.map Option.some v) :
      PresGroup (extRel ρ (hnnWord u v))) := by
    have := not_isOfFinOrder_map_of_injective hinj hv
    simpa using this
  exact extCycle_hnn_span ρ u v hord hinj hc

end FiniteChains
