import RequestProject.CockcroftExtStep

/-!
# Freely adjoining a generator: `π₂` is generated by the old `π₂`

The first move of rule 1 in Section 3.4 is "freely adjoin all `b_z`": a new generator is
added with **no** new relator.  This file treats that move, completing — together with
`RequestProject/Pi2Generation.lean` and `RequestProject/Pi2ExtensionInjective.lean` — the
three moves of rule 1 (free adjunction, stable letter, elimination of the old generator).

* `FiniteChains.extHomFree_injective` — the old fundamental group injects into the enlarged
  one (the obvious retraction sends the new generator to `1`);
* `FiniteChains.freeCycle_mem_span` — every Fox cycle of the enlarged presentation is a
  combination, over the enlarged group ring, of images of Fox cycles of the old one;
* `FiniteChains.isCockcroft_extFree` — the move preserves the Cockcroft property.
-/

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains

open MonoidAlgebra

universe u

variable {α : Type u} [Fintype α] [DecidableEq α] {J : Type u} [Fintype J] [DecidableEq J]
variable (ρ : J → FreeGroup α)

/-- The presentation with one new free generator (the element `none`) and the old relators. -/
def extFree : J → FreeGroup (Option α) := fun j => FreeGroup.map Option.some (ρ j)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem relSub_le_comap_extFree :
    relSub ρ ≤ (relSub (extFree ρ)).comap (FreeGroup.map Option.some) := by
  refine Subgroup.normalClosure_le_normal ?_
  rintro _ ⟨j, rfl⟩
  refine Subgroup.mem_comap.2 ?_
  have : FreeGroup.map Option.some (ρ j) = extFree ρ j := rfl
  rw [this]
  exact Subgroup.subset_normalClosure (Set.mem_range_self j)

/-- The map of fundamental groups induced by adjoining a free generator. -/
def extHomFree : PresGroup ρ →* PresGroup (extFree ρ) :=
  QuotientGroup.map _ _ (FreeGroup.map Option.some) (relSub_le_comap_extFree ρ)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
@[simp] theorem extHomFree_mk (w : FreeGroup α) :
    extHomFree ρ (QuotientGroup.mk w) = QuotientGroup.mk (FreeGroup.map Option.some w) := rfl

/-- The retraction of free groups killing the new generator. -/
def killNew : FreeGroup (Option α) →* FreeGroup α :=
  FreeGroup.lift (fun o => o.elim 1 FreeGroup.of)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
@[simp] theorem killNew_map_some (w : FreeGroup α) :
    killNew (FreeGroup.map Option.some w) = w := by
  have h : (killNew (α := α)).comp (FreeGroup.map Option.some) = MonoidHom.id _ :=
    FreeGroup.ext_hom _ _ fun a => by simp [killNew]
  exact congrArg (fun f : FreeGroup α →* FreeGroup α => f w) h

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem relSub_le_comap_killNew :
    relSub (extFree ρ) ≤ (relSub ρ).comap (killNew (α := α)) := by
  refine Subgroup.normalClosure_le_normal ?_
  rintro _ ⟨j, rfl⟩
  refine Subgroup.mem_comap.2 ?_
  have : killNew (extFree ρ j) = ρ j := killNew_map_some (ρ j)
  rw [this]
  exact Subgroup.subset_normalClosure (Set.mem_range_self j)

/-- The retraction of the enlarged presented group onto the old one. -/
def freeRetract : PresGroup (extFree ρ) →* PresGroup ρ :=
  QuotientGroup.map _ _ (killNew (α := α)) (relSub_le_comap_killNew ρ)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
/-- **Adjoining a free generator does not collapse the old group.** -/
theorem extHomFree_injective : Function.Injective (extHomFree ρ) := by
  refine Function.LeftInverse.injective (g := freeRetract ρ) ?_
  intro g
  induction g using QuotientGroup.induction_on with
  | H w =>
      show freeRetract ρ (QuotientGroup.mk (FreeGroup.map Option.some w)) = _
      show (QuotientGroup.mk (killNew (FreeGroup.map Option.some w)) : PresGroup ρ) = _
      rw [killNew_map_some]

/-- The ring map of group rings induced by adjoining a free generator. -/
noncomputable def extRingHomFree :
    MonoidAlgebra ℤ (PresGroup ρ) →+* MonoidAlgebra ℤ (PresGroup (extFree ρ)) :=
  MonoidAlgebra.mapDomainRingHom ℤ (extHomFree ρ)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem quot_freeRingMap_extFree (x : FreeGroupRing α) :
    quotRingHom ℤ (relSub (extFree ρ)) (freeRingMap Option.some x)
      = extRingHomFree ρ (quotRingHom ℤ (relSub ρ) x) := by
  induction x using MonoidAlgebra.induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, hx, hy]
  | single w m =>
      show quotRingHom ℤ (relSub (extFree ρ))
          (MonoidAlgebra.mapDomain (FreeGroup.map Option.some) (MonoidAlgebra.single w m)) = _
      rw [MonoidAlgebra.mapDomain_single, quotRingHom_single]
      show _ = MonoidAlgebra.mapDomain (extHomFree ρ) (quotRingHom ℤ (relSub ρ) (MonoidAlgebra.single w m))
      rw [quotRingHom_single, MonoidAlgebra.mapDomain_single, extHomFree_mk]

omit [Fintype α] [Fintype J] [DecidableEq J] in
/-- On the old generators the Fox matrix of the enlarged presentation is the image of the old
Fox matrix; the row of the new generator vanishes. -/
theorem foxMatrix_extFree (i : α) (j : J) :
    foxMatrixPres (extFree ρ) (some i) j = extRingHomFree ρ (foxMatrixPres ρ i j) := by
  have hfox : @fox (Option α) _ (some i) (extFree ρ j)
      = freeRingMap Option.some (fox i (ρ j)) :=
    fox_map Option.some (Option.some_injective α) i (ρ j)
  show quotRingHom ℤ (relSub (extFree ρ)) (fox (some i) (extFree ρ j)) = _
  rw [hfox, quot_freeRingMap_extFree]
  rfl

/-- The subgroup of the enlarged group which is the image of the old one. -/
abbrev extRangeFree : Subgroup (PresGroup (extFree ρ)) := (extHomFree ρ).range

/-- The group ring of the old group, mapped isomorphically onto the group ring of the image
subgroup. -/
noncomputable def extRangeFreeRingHom :
    MonoidAlgebra ℤ (PresGroup ρ) →+* MonoidAlgebra ℤ (extRangeFree ρ) :=
  MonoidAlgebra.mapDomainRingHom ℤ (extHomFree ρ).rangeRestrict

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem subRingHom_extRangeFreeRingHom (y : MonoidAlgebra ℤ (PresGroup ρ)) :
    subRingHom (extRangeFree ρ) (extRangeFreeRingHom ρ y) = extRingHomFree ρ y := by
  show MonoidAlgebra.mapDomain (Subtype.val : extRangeFree ρ → _)
      (MonoidAlgebra.mapDomain (extHomFree ρ).rangeRestrict y) = MonoidAlgebra.mapDomain (extHomFree ρ) y
  rw [← MonoidAlgebra.mapDomain_comp]
  rfl

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem extRangeFreeRingHom_surjective : Function.Surjective (extRangeFreeRingHom ρ) :=
  by
    intro y
    obtain ⟨x, hx⟩ := Finsupp.mapDomain_surjective (extHomFree ρ).rangeRestrict_surjective y.coeff
    exact ⟨MonoidAlgebra.ofCoeff x, MonoidAlgebra.coeff_injective hx⟩

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem extRangeFreeRingHom_injective : Function.Injective (extRangeFreeRingHom ρ) := by
  have hr : Function.Injective (extHomFree ρ).rangeRestrict := fun a b hab => extHomFree_injective ρ (congrArg Subtype.val hab)
  intro a b hab
  apply MonoidAlgebra.coeff_injective
  exact Finsupp.mapDomain_injective hr (congrArg MonoidAlgebra.coeff hab)

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
/-- The augmentation of the enlarged group ring restricts to the old augmentation. -/
theorem augPres_extRingHomFree (z : MonoidAlgebra ℤ (PresGroup ρ)) :
    augPres (extFree ρ) (extRingHomFree ρ z) = augPres ρ z :=
  augQ_mapDomain (extHomFree ρ) z

omit [Fintype α] [DecidableEq J] in
/-- **Adjoining a free generator leaves `π₂` generated by the image of the old `π₂`.**  The
Fox matrix does not change (only its coefficient ring grows), so this is exactly the base
change statement of `RequestProject/BaseChangeCycles.lean` applied to the subgroup which is
the image of the old fundamental group. -/
theorem freeCycle_mem_span {v : J → MonoidAlgebra ℤ (PresGroup (extFree ρ))}
    (hv : IsFoxCycle (extFree ρ) v) :
    v ∈ Submodule.span (MonoidAlgebra ℤ (PresGroup (extFree ρ)))
      {w : J → MonoidAlgebra ℤ (PresGroup (extFree ρ)) |
        ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧
          w = fun j => extRingHomFree ρ (y j)} := by
  classical
  set H := extRangeFree ρ with hH
  set A : α → J → MonoidAlgebra ℤ H := fun i j => extRangeFreeRingHom ρ (foxMatrixPres ρ i j)
    with hA
  have hcyc : ∀ i : α, ∑ j : J, v j * subRingHom H (A i j) = 0 := by
    intro i
    rw [← hv (some i)]
    exact Finset.sum_congr rfl fun j _ => by
      rw [hA, subRingHom_extRangeFreeRingHom, foxMatrix_extFree]
  have hspan := cycle_mem_span_subgroup_cycles H A v hcyc
  refine Submodule.span_mono ?_ hspan
  rintro _ ⟨y', hy', rfl⟩
  choose y hy using fun j => extRangeFreeRingHom_surjective ρ (y' j)
  refine ⟨y, ?_, ?_⟩
  · intro i
    refine extRangeFreeRingHom_injective ρ ?_
    rw [map_sum, map_zero, ← hy' i]
    exact Finset.sum_congr rfl fun j _ => by rw [map_mul, hy j]
  · funext j
    rw [← hy j, subRingHom_extRangeFreeRingHom]

omit [Fintype α] [DecidableEq J] in
/-- **Adjoining a free generator preserves the Cockcroft property.** -/
theorem isCockcroft_extFree (hP : IsCockcroft ρ) : IsCockcroft (extFree ρ) := by
  intro v hv
  have hspan := freeCycle_mem_span ρ hv
  set N : Submodule (MonoidAlgebra ℤ (PresGroup (extFree ρ)))
      (J → MonoidAlgebra ℤ (PresGroup (extFree ρ))) :=
    { carrier := {w | ∀ j, augPres (extFree ρ) (w j) = 0}
      add_mem' := by
        intro a b ha hb j
        rw [Pi.add_apply, map_add, ha j, hb j, add_zero]
      zero_mem' := by
        intro j
        simp
      smul_mem' := by
        intro c a ha j
        rw [Pi.smul_apply, smul_eq_mul, map_mul, ha j, mul_zero] } with hN
  have hgen : {w : J → MonoidAlgebra ℤ (PresGroup (extFree ρ)) |
      ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧
        w = fun j => extRingHomFree ρ (y j)} ⊆ (N : Set (J → MonoidAlgebra ℤ
          (PresGroup (extFree ρ)))) := by
    rintro _ ⟨y, hy, rfl⟩ j
    show augPres (extFree ρ) (extRingHomFree ρ (y j)) = 0
    rw [augPres_extRingHomFree ρ (y j), hP y hy j]
  exact Submodule.span_le.2 hgen hspan

end FiniteChains
