import RequestProject.ZeroPi2Descent

/-!
# From generation of `π₂` to the vanishing of the arrows of the descended chain

The last paragraph of the proof of Proposition 3.11 reads: *"For subsequent arrows, the square
formed by `Lᵢ → Lᵢ₊₁` and `Eᵢ → Eᵢ₊₁` commutes.  The upper arrow is zero on `π₂` and its
images generate the lower source by (3.5).  Hence every lower arrow is zero on the whole of
`π₂`."*  This file proves exactly that implication in the combinatorial model, so that the
only thing the paper's geometry still has to supply for those arrows is the generation
statement (3.5) itself.

* `FiniteChains.Comb.shiftHom` — **change of base vertex**: a path `q` from `y₀` to `w₀`
  induces a cellular map `Ũ(X, w₀) → Ũ(X, y₀)` of universal covers over `X`, sending the base
  vertex to the class of `q`.  (For a loop this is the deck transformation of
  `RequestProject/CombUniversalCover.lean`.)
* `FiniteChains.Comb.Pi2FromSub` — the spherical classes of `E` **coming from a subcomplex**
  `ι : L → E`: the images of `π₂(L)` under all lifts of `ι` to the universal covers.  As the
  lifts range over all of them, these are exactly the images of the copies of `L̃` inside
  `Ẽ`, i.e. the translates by the deck group of the image of `π₂(L)`.
* `FiniteChains.Comb.zeroPi2_chain_of_generated` — **the implication**: in a commuting square
  `j ∘ ι = ι' ∘ k` with `k` zero on `π₂`, every class of `π₂(E)` in the span of
  `Pi2FromSub ι` is killed by `j`.
* `FiniteChains.Comb.zeroPi2_of_pi2Generated` — consequently, if `π₂(E)` is generated by the
  classes coming from `L`, then `j` is zero on `π₂`.
-/

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains
namespace Comb

universe u

/-! ### Changing the base vertex of the universal cover -/

section Shift

variable {X : Complex2.{u}} {y₀ w₀ : X.V} {q : List (X.E × Bool)}

/-- Prepending a fixed path to a path issued from its endpoint. -/
def shiftP (hq : IsPath X.src X.tgt q y₀ w₀) (p : PathFrom X w₀) : PathFrom X y₀ :=
  ⟨q ++ p.1, by
    have hend : endpt X y₀ (q ++ p.1) = endpt X w₀ p.1 := by
      rw [endpt_append, endpt_eq_of_isPath hq]
    rw [hend]
    exact isPath_append_iff.mpr ⟨w₀, hq, p.2⟩⟩

theorem endpt_shiftP (hq : IsPath X.src X.tgt q y₀ w₀) (p : PathFrom X w₀) :
    endpt X y₀ (shiftP hq p).1 = endpt X w₀ p.1 := by
  show endpt X y₀ (q ++ p.1) = endpt X w₀ p.1
  rw [endpt_append, endpt_eq_of_isPath hq]

/-- Changing the base vertex of the universal cover, on vertices. -/
def shiftV (hq : IsPath X.src X.tgt q y₀ w₀) (c : UV X w₀) : UV X y₀ :=
  Quotient.map (shiftP hq) (by
    intro p p' hpp
    show Htpy X y₀ (endpt X y₀ (shiftP hq p).1) (shiftP hq p).1 (shiftP hq p').1
    rw [endpt_shiftP]
    exact Htpy.append_congr hq p.2 (Htpy.refl q) hpp) c

@[simp] theorem shiftV_mk (hq : IsPath X.src X.tgt q y₀ w₀) (p : PathFrom X w₀) :
    shiftV hq (UV.mk p) = UV.mk (shiftP hq p) := rfl

@[simp] theorem endV_shiftV (hq : IsPath X.src X.tgt q y₀ w₀) (c : UV X w₀) :
    endV (shiftV hq c) = endV c := by
  induction c using UV.ind with
  | h p => exact endpt_shiftP hq p

theorem shiftV_base (hq : IsPath X.src X.tgt q y₀ w₀) :
    shiftV hq (UV.base X w₀) = UV.mk ⟨q, by rw [endpt_eq_of_isPath hq]; exact hq⟩ := by
  refine congrArg UV.mk (Subtype.ext ?_)
  show q ++ [] = q
  exact List.append_nil q

theorem extend_shiftV (hq : IsPath X.src X.tgt q y₀ w₀) (eb : X.E × Bool) (c : UV X w₀) :
    extend eb (shiftV hq c) = shiftV hq (extend eb c) := by
  induction c using UV.ind with
  | h p =>
      have hl : (extendP eb (shiftP hq p)).1 = (shiftP hq (extendP eb p)).1 := by
        by_cases h : endpt X w₀ p.1 = germSrc X.src X.tgt eb
        · have h' : endpt X y₀ (shiftP hq p).1 = germSrc X.src X.tgt eb := by
            rw [endpt_shiftP]; exact h
          rw [extendP_pos h']
          show (q ++ p.1) ++ [eb] = q ++ (extendP eb p).1
          rw [extendP_pos h]
          simp
        · have h' : ¬ endpt X y₀ (shiftP hq p).1 = germSrc X.src X.tgt eb := by
            rw [endpt_shiftP]; exact h
          rw [extendP_neg h']
          show (shiftP hq p).1 = q ++ (extendP eb p).1
          rw [extendP_neg h]
          rfl
      refine Quotient.sound ?_
      show Htpy X y₀ (endpt X y₀ (extendP eb (shiftP hq p)).1) (extendP eb (shiftP hq p)).1
        (shiftP hq (extendP eb p)).1
      rw [hl]
      exact Htpy.refl _

/-- Changing the base vertex of the universal cover, on edges. -/
def shiftE (hq : IsPath X.src X.tgt q y₀ w₀) (E : UE X w₀) : UE X y₀ :=
  ⟨(shiftV hq E.1.1, E.1.2), by rw [endV_shiftV]; exact E.2⟩

/-- Changing the base vertex of the universal cover, on two-cells. -/
def shiftF (hq : IsPath X.src X.tgt q y₀ w₀) (F : UF X w₀) : UF X y₀ :=
  ⟨(shiftV hq F.1.1, F.1.2), by rw [endV_shiftV]; exact F.2⟩

theorem liftGerm_shiftV (hq : IsPath X.src X.tgt q y₀ w₀) {c : UV X w₀} {eb : X.E × Bool}
    (h : endV c = germSrc X.src X.tgt eb) (h' : endV (shiftV hq c) = germSrc X.src X.tgt eb) :
    liftGerm (shiftV hq c) eb h' = (shiftE hq (liftGerm c eb h).1, (liftGerm c eb h).2) := by
  obtain ⟨e, b⟩ := eb
  cases b with
  | true => rfl
  | false =>
      refine Prod.ext ?_ rfl
      refine Subtype.ext (Prod.ext ?_ rfl)
      exact extend_shiftV hq (e, false) c

theorem uLiftPath_shiftV (hq : IsPath X.src X.tgt q y₀ w₀) :
    ∀ (l : List (X.E × Bool)) (c : UV X w₀) (v : X.V), IsPath X.src X.tgt l (endV c) v →
      uLiftPath l (shiftV hq c) = (uLiftPath l c).map (fun Eb => (shiftE hq Eb.1, Eb.2)) := by
  intro l
  induction l with
  | nil => intro c v _; rfl
  | cons eb t ih =>
      intro c v hl
      have h : endV c = germSrc X.src X.tgt eb := hl.1
      have h' : endV (shiftV hq c) = germSrc X.src X.tgt eb := by rw [endV_shiftV]; exact h
      rw [uLiftPath_cons h', uLiftPath_cons h, List.map_cons, liftGerm_shiftV hq h h',
        extend_shiftV hq eb c, ih (extend eb c) v (by rw [endV_extend h]; exact hl.2)]

/-- **Change of base vertex of the universal cover.**  A path from `y₀` to `w₀` induces a
cellular map `Ũ(X, w₀) → Ũ(X, y₀)` over `X`; it sends the base vertex to the class of the
path.  For a loop this is the deck transformation attached to its class. -/
noncomputable def shiftHom (hq : IsPath X.src X.tgt q y₀ w₀) :
    Hom (uCover X w₀) (uCover X y₀) where
  onV := shiftV hq
  onE := shiftE hq
  onF := shiftF hq
  src_onE := fun _ => rfl
  tgt_onE := fun E => extend_shiftV hq (E.1.2, true) E.1.1
  base_onF := fun _ => rfl
  att_onF := by
    intro F
    have hbase : endV F.1.1 = X.base F.1.2 := F.2
    have hatt : IsPath X.src X.tgt (X.att F.1.2) (endV F.1.1) (X.base F.1.2) := by
      rw [hbase]; exact X.att_isLoop F.1.2
    show uLiftPath (X.att F.1.2) (shiftV hq F.1.1) = _
    exact uLiftPath_shiftV hq (X.att F.1.2) F.1.1 (X.base F.1.2) hatt

@[simp] theorem onE_shiftHom (hq : IsPath X.src X.tgt q y₀ w₀) (E : UE X w₀) :
    ((shiftHom hq).onE E).1.2 = E.1.2 := rfl

@[simp] theorem onF_shiftHom (hq : IsPath X.src X.tgt q y₀ w₀) (F : UF X w₀) :
    ((shiftHom hq).onF F).1.2 = F.1.2 := rfl

end Shift

/-! ### Spherical classes coming from a subcomplex -/

variable {L L' E E' : Complex2.{u}}

/-- The set of spherical classes of `E` **coming from `L`** along `ι : L → E`: the images of
the two-cycles of the universal cover of `L` under all lifts of `ι` to the universal covers.
Letting the lift vary over all lifts (equivalently, over all copies of `L̃` in `Ẽ`) is what
makes the set closed under the deck group of `Ẽ`. -/
def Pi2FromSub (ι : Hom L E) (x₀ : E.V) : Set ((uCover E x₀).F →₀ ℤ) :=
  {d | ∃ (l₀ : L.V) (φ : Hom (uCover L l₀) (uCover E x₀)),
      (∀ v, endV (φ.onV v) = ι.onV (endV v)) ∧
      (∀ e : UE L l₀, ((φ.onE e).1).2 = ι.onE (e.1.2)) ∧
      (∀ f : UF L l₀, ((φ.onF f).1).2 = ι.onF (f.1.2)) ∧
      ∃ z ∈ Pi2 L l₀, d = chain2 φ z}

/-- The canonical lift of a cellular map is one of the lifts used in
`FiniteChains.Comb.Pi2FromSub`. -/
theorem mem_pi2FromSub_univLift (ι : Hom L E) (l₀ : L.V) {z : (uCover L l₀).F →₀ ℤ}
    (hz : z ∈ Pi2 L l₀) :
    chain2 (univLift L ι l₀) z ∈ Pi2FromSub ι (ι.onV l₀) :=
  ⟨l₀, univLift L ι l₀, fun v => endV_univLiftV l₀ ι v, fun _ => rfl, fun _ => rfl, z, hz, rfl⟩

/-- **The last step of the proof of Proposition 3.11.**  Let `j ∘ ι = ι' ∘ k` be a commuting
square of cellular maps in which the upper arrow `k : L → L'` is zero on `π₂`.  Then `j` kills
every spherical class of `E` which lies in the span of the classes coming from `L`. -/
theorem zeroPi2_chain_of_generated (ι : Hom L E) (k : Hom L L') (ι' : Hom L' E') (j : Hom E E')
    (hsq : j.comp ι = ι'.comp k) (hconnE' : IsConnected E') (hzero : ZeroPi2 k) {x₀ : E.V}
    {c : (uCover E x₀).F →₀ ℤ} (hgen : c ∈ Submodule.span ℤ (Pi2FromSub ι x₀)) :
    chain2 (univLift E j x₀) c = 0 := by
  have hsub : Pi2FromSub ι x₀ ≤ (LinearMap.ker (chain2 (univLift E j x₀)) : Submodule ℤ _) := by
    rintro d ⟨l₀, φ, hφV, hφE, hφF, z, hz, rfl⟩
    show chain2 (univLift E j x₀) (chain2 φ z) = 0
    -- the two maps of universal covers to be compared
    set J : Hom (uCover E x₀) (uCover E' (j.onV x₀)) := univLift E j x₀
    set A : Hom (uCover L l₀) (uCover E' (j.onV x₀)) := J.comp φ
    set kappa : Hom (uCover L l₀) (uCover L' (k.onV l₀)) := univLift L k l₀
    -- the base vertex of `A` and a path representing it
    have hbaseV : endV (A.onV (UV.base L l₀)) = ι'.onV (k.onV l₀) := by
      show endV (univLiftV x₀ j (φ.onV (UV.base L l₀))) = ι'.onV (k.onV l₀)
      rw [endV_univLiftV, hφV]
      exact congrArg (fun h : Hom L E' => h.onV l₀) hsq
    obtain ⟨tp, htp⟩ := Quotient.exists_rep (A.onV (UV.base L l₀))
    have hqpath : IsPath E'.src E'.tgt tp.1 (j.onV x₀) (ι'.onV (k.onV l₀)) := by
      have h := tp.2
      have hend : endpt E' (j.onV x₀) tp.1 = ι'.onV (k.onV l₀) := by
        rw [← hbaseV, ← htp]; rfl
      rwa [hend] at h
    -- the second map: the canonical lift of `ι'`, followed by the change of base vertex
    set chi : Hom (uCover L' (k.onV l₀)) (uCover E' (j.onV x₀)) :=
      (shiftHom hqpath).comp (univLift L' ι' (k.onV l₀))
    set B : Hom (uCover L l₀) (uCover E' (j.onV x₀)) := chi.comp kappa
    -- `A` and `B` are lifts of the same map along the universal covering of `E'`
    have hqcov : IsCovering (univProj E' (j.onV x₀)) := isCovering_univProj hconnE'
    have hE : ∀ e, (univProj E' (j.onV x₀)).onE (A.onE e)
        = (univProj E' (j.onV x₀)).onE (B.onE e) := by
      intro e
      show j.onE ((φ.onE e).1).2 = ι'.onE (k.onE (e.1.2))
      rw [hφE e]
      exact congrArg (fun h : Hom L E' => h.onE e.1.2) hsq
    have hF : ∀ f, (univProj E' (j.onV x₀)).onF (A.onF f)
        = (univProj E' (j.onV x₀)).onF (B.onF f) := by
      intro f
      show j.onF ((φ.onF f).1).2 = ι'.onF (k.onF (f.1.2))
      rw [hφF f]
      exact congrArg (fun h : Hom L E' => h.onF f.1.2) hsq
    have hbase : A.onV (UV.base L l₀) = B.onV (UV.base L l₀) := by
      show A.onV (UV.base L l₀) = shiftV hqpath ((univLift L' ι' (k.onV l₀)).onV
        (kappa.onV (UV.base L l₀)))
      have hk : kappa.onV (UV.base L l₀) = UV.base L' (k.onV l₀) := rfl
      have hi : (univLift L' ι' (k.onV l₀)).onV (UV.base L' (k.onV l₀))
          = UV.base E' (ι'.onV (k.onV l₀)) := rfl
      rw [hk, hi, shiftV_base]
      exact htp.symm
    have hV := lift_onV_eq hqcov isConnected_univCover hE hbase
    have hFeq := lift_onF_eq hqcov hF hV
    -- the upper arrow kills `z`
    have hkz : chain2 kappa z = 0 := hzero l₀ z hz
    have hAB : chain2 A z = chain2 B z :=
      congrArg (fun m => Finsupp.mapDomain m z) (funext hFeq)
    have hBz : chain2 B z = chain2 chi (chain2 kappa z) := by
      show Finsupp.mapDomain (chi.onF ∘ kappa.onF) z
        = Finsupp.mapDomain chi.onF (Finsupp.mapDomain kappa.onF z)
      rw [← Finsupp.mapDomain_comp]
    have hAz : chain2 (univLift E j x₀) (chain2 φ z) = chain2 A z := by
      show Finsupp.mapDomain J.onF (Finsupp.mapDomain φ.onF z)
        = Finsupp.mapDomain (J.onF ∘ φ.onF) z
      rw [← Finsupp.mapDomain_comp]
    rw [hAz, hAB, hBz, hkz, map_zero]
  exact Submodule.span_le.2 hsub hgen

/-- **The arrows of the descended chain are zero on `π₂` once `π₂` is generated from
upstairs.**  If every spherical class of `E` is a combination of classes coming from `L`, and
the upper arrow `k : L → L'` is zero on `π₂`, then the lower arrow `j : E → E'` is zero on
`π₂`. -/
theorem zeroPi2_of_pi2Generated (ι : Hom L E) (k : Hom L L') (ι' : Hom L' E') (j : Hom E E')
    (hsq : j.comp ι = ι'.comp k) (hconnE' : IsConnected E') (hzero : ZeroPi2 k)
    (hgen : ∀ (x₀ : E.V), ∀ c ∈ Pi2 E x₀, c ∈ Submodule.span ℤ (Pi2FromSub ι x₀)) :
    ZeroPi2 j :=
  fun x₀ c hc => zeroPi2_chain_of_generated ι k ι' j hsq hconnE' hzero (hgen x₀ c hc)

/-! ### The arrows of the descended chain -/

section Pushout

variable {D K M : Complex2.{u}}

theorem hom_ext {X Y : Complex2.{u}} : ∀ a b : Hom X Y,
    a.onV = b.onV → a.onE = b.onE → a.onF = b.onF → a = b := by
  rintro ⟨a1, a2, a3, p1, p2, p3, p4⟩ ⟨b1, b2, b3, q1, q2, q3, q4⟩ hV hE hF
  cases hV; cases hE; cases hF; rfl

/-- The factorization through the pushout restricts to the given map on the term upstairs. -/
theorem pushoutLift_comp_pushoutMap (p : Hom D K) (i : Hom D L) (hiV : Function.Injective i.onV)
    (hiE : Function.Injective i.onE) (hiF : Function.Injective i.onF) (f : Hom K M) (g : Hom L M)
    (hV : ∀ d, g.onV (i.onV d) = f.onV (p.onV d))
    (hE : ∀ d, g.onE (i.onE d) = f.onE (p.onE d))
    (hF : ∀ d, g.onF (i.onF d) = f.onF (p.onF d)) :
    (pushoutLift p i hiV hiE f g hV hE).comp (pushoutMap p i hiV hiE hiF) = g := by
  refine hom_ext _ _ (funext fun v => ?_) (funext fun e => ?_) (funext fun c => ?_)
  · show Sum.elim f.onV (fun w : OffV i => g.onV w.1) (pushV p i v) = g.onV v
    by_cases h : ∃ d, i.onV d = v
    · obtain ⟨d, rfl⟩ := h
      rw [pushV_of_mem p hiV d]
      exact (hV d).symm
    · rw [pushV_of_off p i ⟨v, fun d hd => h ⟨d, hd⟩⟩]
      rfl
  · show Sum.elim f.onE (fun w : OffE i => g.onE w.1) (pushE p i e) = g.onE e
    by_cases h : ∃ d, i.onE d = e
    · obtain ⟨d, rfl⟩ := h
      rw [pushE_of_mem p hiE d]
      exact (hE d).symm
    · rw [pushE_of_off p i ⟨e, fun d hd => h ⟨d, hd⟩⟩]
      rfl
  · show Sum.elim f.onF (fun w : OffF i => g.onF w.1) (pushF p i c) = g.onF c
    by_cases h : ∃ d, i.onF d = c
    · obtain ⟨d, rfl⟩ := h
      rw [pushF_of_mem p hiF d]
      exact (hF d).symm
    · rw [pushF_of_off p i ⟨c, fun d hd => h ⟨d, hd⟩⟩]
      rfl

/-- **The square of Proposition 3.11 commutes**: the map of pushouts induced by `L ⊆ L'`
restricted to `L` is the composite `L → L' → K ∪_p L'`. -/
theorem pushoutFunctor_comm (p : Hom D K) (j : Hom D L) (j' : Hom D L') (k : Hom L L')
    (hjV : Function.Injective j.onV) (hjE : Function.Injective j.onE)
    (hjF : Function.Injective j.onF) (hj'V : Function.Injective j'.onV)
    (hj'E : Function.Injective j'.onE) (hj'F : Function.Injective j'.onF)
    (hkj : k.comp j = j') :
    (pushoutFunctor p j j' k hjV hjE hj'V hj'E hj'F hkj).comp (pushoutMap p j hjV hjE hjF)
      = (pushoutMap p j' hj'V hj'E hj'F).comp k := by
  have hV : ∀ d, ((pushoutMap p j' hj'V hj'E hj'F).comp k).onV (j.onV d)
      = (pushoutInl p j' hj'V hj'E).onV (p.onV d) := by
    intro d
    show pushV p j' (k.onV (j.onV d)) = Sum.inl (p.onV d)
    rw [show k.onV (j.onV d) = j'.onV d from congrFun (congrArg Hom.onV hkj) d,
      pushV_of_mem p hj'V]
  have hE : ∀ d, ((pushoutMap p j' hj'V hj'E hj'F).comp k).onE (j.onE d)
      = (pushoutInl p j' hj'V hj'E).onE (p.onE d) := by
    intro d
    show pushE p j' (k.onE (j.onE d)) = Sum.inl (p.onE d)
    rw [show k.onE (j.onE d) = j'.onE d from congrFun (congrArg Hom.onE hkj) d,
      pushE_of_mem p hj'E]
  have hF : ∀ d, ((pushoutMap p j' hj'V hj'E hj'F).comp k).onF (j.onF d)
      = (pushoutInl p j' hj'V hj'E).onF (p.onF d) := by
    intro d
    show pushF p j' (k.onF (j.onF d)) = Sum.inl (p.onF d)
    rw [show k.onF (j.onF d) = j'.onF d from congrFun (congrArg Hom.onF hkj) d,
      pushF_of_mem p hj'F]
  exact pushoutLift_comp_pushoutMap p j hjV hjE hjF _ _ hV hE hF

/-- **The arrows of the descended chain are zero on `π₂`, granted the generation statement
(3.5).**  For the cellular pushouts `E = K ∪_p L ⊆ E' = K ∪_p L'` of Proposition 3.11: if the
second homotopy module of `E` is generated by the classes coming from `L`, and `L → L'` is
zero on `π₂`, then so is `E → E'`. -/
theorem zeroPi2_pushoutFunctor (p : Hom D K) (j : Hom D L) (j' : Hom D L') (k : Hom L L')
    (hjV : Function.Injective j.onV) (hjE : Function.Injective j.onE)
    (hjF : Function.Injective j.onF) (hj'V : Function.Injective j'.onV)
    (hj'E : Function.Injective j'.onE) (hj'F : Function.Injective j'.onF)
    (hkj : k.comp j = j') (hconnE' : IsConnected (pushoutComplex p j' hj'V hj'E))
    (hzero : ZeroPi2 k)
    (hgen : ∀ x₀ : (pushoutComplex p j hjV hjE).V,
      ∀ c ∈ Pi2 (pushoutComplex p j hjV hjE) x₀,
        c ∈ Submodule.span ℤ (Pi2FromSub (pushoutMap p j hjV hjE hjF) x₀)) :
    ZeroPi2 (pushoutFunctor p j j' k hjV hjE hj'V hj'E hj'F hkj) :=
  zeroPi2_of_pi2Generated (pushoutMap p j hjV hjE hjF) k (pushoutMap p j' hj'V hj'E hj'F) _
    (pushoutFunctor_comm p j j' k hjV hjE hjF hj'V hj'E hj'F hkj) hconnE' hzero hgen

end Pushout

end Comb
end FiniteChains
