module

public import RequestProject.Pi2Extension
public import RequestProject.BaseChangeCycles

@[expose] public section

/-!
# Generation of `π₂` over the enlarged group ring (equation (3.3) for one extension step)

Lemma 3.9 of the paper rests on the generation statement

  `π₂(T(P)) = ℤ[G(T(P))] · η_{P*} π₂(P)`,                                        (3.3)

and Proposition 3.11 repeats the same argument downstairs.  In the combinatorial model `π₂`
is the module of Fox cycles, and this file proves (3.3) for one step of the construction —
adjoining a single generator together with a single relator — from the two ingredients
established separately:

* `RequestProject/Pi2Extension.lean`: a Fox cycle of the enlarged presentation is zero on the
  new two-cell and is a Fox cycle of the *old* Fox matrix, read in the enlarged group ring;
* `RequestProject/BaseChangeCycles.lean`: cycles of a matrix with entries in the group ring of
  a subgroup are generated, over the big group ring, by cycles over the subgroup ring.

The subgroup in question is the image of the old fundamental group, so the second ingredient
applies as soon as that image is a faithful copy of the old group — exactly the HNN normal
form statement quoted in the paper (`RequestProject/HNNEmbedding.lean`) in the case of the
stable-letter extension, and a triviality for the Tietze step.

The main results are `FiniteChains.extCycle_mem_span` (the general step) and its two
instances `FiniteChains.extCycle_tietze_span`, `FiniteChains.extCycle_hnn_span`.
-/

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains

open MonoidAlgebra

universe u

variable {α : Type u} [Fintype α] [DecidableEq α] {J : Type u} [Fintype J] [DecidableEq J]
variable (ρ : J → FreeGroup α) (w₀ : FreeGroup (Option α))

/-- The image of a Fox cycle of the old presentation among the two-cells of the enlarged
presentation: the structural map `η_P` in coordinates. -/
noncomputable def extCycleImage (y : J → MonoidAlgebra ℤ (PresGroup ρ)) :
    Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ w₀))
  | none => 0
  | some j => extRingHom ρ w₀ (y j)

/-- Padding a vector of coefficients on the old two-cells with `0` on the new two-cell. -/
def padCells (R : Type*) [Ring R] (J : Type*) : (J → R) →ₗ[R] (Option J → R) :=
  LinearMap.pi (fun jo => match jo with | none => 0 | some j => LinearMap.proj j)

@[simp] theorem padCells_none {R : Type*} [Ring R] {J : Type*} (u : J → R) :
    padCells R J u none = 0 := rfl

@[simp] theorem padCells_some {R : Type*} [Ring R] {J : Type*} (u : J → R) (j : J) :
    padCells R J u (some j) = u j := rfl

/-- The subgroup of the enlarged fundamental group generated by the image of the old one. -/
abbrev extRange : Subgroup (PresGroup (extRel ρ w₀)) := (extHom ρ w₀).range

/-- The group ring of the old group, mapped isomorphically onto the group ring of the image
subgroup. -/
noncomputable def extRangeRingHom :
    MonoidAlgebra ℤ (PresGroup ρ) →+* MonoidAlgebra ℤ (extRange ρ w₀) :=
  MonoidAlgebra.mapDomainRingHom ℤ (extHom ρ w₀).rangeRestrict

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem subRingHom_extRangeRingHom (y : MonoidAlgebra ℤ (PresGroup ρ)) :
    subRingHom (extRange ρ w₀) (extRangeRingHom ρ w₀ y) = extRingHom ρ w₀ y := by
  change MonoidAlgebra.mapDomain (Subtype.val : extRange ρ w₀ → _)
      (MonoidAlgebra.mapDomain (extHom ρ w₀).rangeRestrict y) = MonoidAlgebra.mapDomain (extHom ρ w₀) y
  rw [← MonoidAlgebra.mapDomain_comp]
  rfl

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem extRangeRingHom_surjective : Function.Surjective (extRangeRingHom ρ w₀) :=
  by
    intro y
    obtain ⟨x, hx⟩ := Finsupp.mapDomain_surjective (extHom ρ w₀).rangeRestrict_surjective y.coeff
    exact ⟨MonoidAlgebra.ofCoeff x, MonoidAlgebra.coeff_injective hx⟩

omit [Fintype α] [DecidableEq α] [Fintype J] [DecidableEq J] in
theorem extRangeRingHom_injective (hinj : Function.Injective (extHom ρ w₀)) :
    Function.Injective (extRangeRingHom ρ w₀) := by
  have hr : Function.Injective (extHom ρ w₀).rangeRestrict := fun a b hab => hinj (congrArg Subtype.val hab)
  intro a b hab
  apply MonoidAlgebra.coeff_injective
  exact Finsupp.mapDomain_injective hr (congrArg MonoidAlgebra.coeff hab)

omit [Fintype α] [DecidableEq J] in
/-- **Generation of `π₂` after a one-generator, one-relator extension** — equation (3.3) for
one step of the operation `T`.  If the Fox derivative of the new relator with respect to the
new generator is right-regular and the old fundamental group injects into the new one, then
every Fox cycle of the enlarged presentation is a combination, with coefficients in the
enlarged group ring, of images of Fox cycles of the old presentation. -/
theorem extCycle_mem_span
    (hreg : ∀ x : MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)),
      x * foxMatrixPres (extRel ρ w₀) none none = 0 → x = 0)
    (hinj : Function.Injective (extHom ρ w₀))
    {v : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ w₀))}
    (hv : IsFoxCycle (extRel ρ w₀) v) :
    v ∈ Submodule.span (MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)))
      {w : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)) |
        ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧ w = extCycleImage ρ w₀ y} := by
  classical
  obtain ⟨hnone, hold⟩ := extCycle_old ρ w₀ hreg hv
  set H := extRange ρ w₀ with hH
  set A : α → J → MonoidAlgebra ℤ H := fun i j => extRangeRingHom ρ w₀ (foxMatrixPres ρ i j)
    with hA
  set pad := padCells (MonoidAlgebra ℤ (PresGroup (extRel ρ w₀))) J with hpadDef
  -- the restricted vector is a cycle of the old matrix, whose entries lie in `ℤ[H]`
  have hcyc : ∀ i : α, ∑ j : J, v (some j) * subRingHom H (A i j) = 0 := by
    intro i
    rw [← hold i]
    exact Finset.sum_congr rfl fun j _ => by rw [hA, subRingHom_extRangeRingHom]
  have hspan := cycle_mem_span_subgroup_cycles H A (fun j => v (some j)) hcyc
  have hpad : v = pad (fun j => v (some j)) := by
    funext jo
    cases jo with
    | none => simpa [hpadDef] using hnone
    | some j => rfl
  -- every padded cycle over the subgroup ring is the image of a Fox cycle of `ρ`
  have hsubset : pad '' (subgroupCycles H A) ⊆
      {w : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)) |
        ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧ w = extCycleImage ρ w₀ y} := by
    rintro _ ⟨u, ⟨y', hy', rfl⟩, rfl⟩
    choose y hy using fun j => extRangeRingHom_surjective ρ w₀ (y' j)
    refine ⟨y, ?_, ?_⟩
    · intro i
      refine extRangeRingHom_injective ρ w₀ hinj ?_
      rw [map_sum, map_zero, ← hy' i]
      exact Finset.sum_congr rfl fun j _ => by rw [map_mul, hy j]
    · funext jo
      cases jo with
      | none => rfl
      | some j =>
          show subRingHom H (y' j) = extRingHom ρ w₀ (y j)
          rw [← hy j, subRingHom_extRangeRingHom]
  have hmap : pad (fun j => v (some j)) ∈
      Submodule.span (MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)))
        (pad '' (subgroupCycles H A)) := by
    rw [← Submodule.map_span]
    exact Submodule.mem_map_of_mem hspan
  rw [hpad]
  exact Submodule.span_mono hsubset hmap


omit [Fintype α] [DecidableEq J] in
/-- **Generation plus equivariance kills the whole of `π₂`** (the way Lemma 3.9 and
Proposition 3.11 use equation (3.3)).  If an equivariant map defined on the module of chains
of the enlarged presentation vanishes on the image of every Fox cycle of the old
presentation, then it vanishes on every Fox cycle of the enlarged one. -/
theorem extCycle_map_eq_zero {M : Type*} [AddCommGroup M]
    [Module (MonoidAlgebra ℤ (PresGroup (extRel ρ w₀))) M]
    (F : (Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)))
      →ₗ[MonoidAlgebra ℤ (PresGroup (extRel ρ w₀))] M)
    (hreg : ∀ x : MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)),
      x * foxMatrixPres (extRel ρ w₀) none none = 0 → x = 0)
    (hinj : Function.Injective (extHom ρ w₀))
    (h0 : ∀ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y →
      F (extCycleImage ρ w₀ y) = 0)
    {v : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ w₀))}
    (hv : IsFoxCycle (extRel ρ w₀) v) : F v = 0 := by
  have hspan := extCycle_mem_span ρ w₀ hreg hinj hv
  have hle : Submodule.span (MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)))
      {w : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ w₀)) |
        ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧ w = extCycleImage ρ w₀ y}
      ≤ LinearMap.ker F := by
    refine Submodule.span_le.2 ?_
    rintro _ ⟨y, hy, rfl⟩
    exact LinearMap.mem_ker.2 (h0 y hy)
  exact LinearMap.mem_ker.1 (hle hspan)

omit [Fintype α] [DecidableEq J] in
/-- **The Tietze step of rule 1: `π₂` is generated by the image of the old `π₂`.**  Adjoining
a generator `z` together with the defining relator `z = s` does not change the fundamental
group, so the hypothesis of `FiniteChains.extCycle_mem_span` on the fundamental groups is the
injectivity of the resulting isomorphism. -/
theorem extCycle_tietze_span (s : FreeGroup α)
    (hinj : Function.Injective (extHom ρ (tietzeWord s)))
    {v : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ (tietzeWord s)))}
    (hv : IsFoxCycle (extRel ρ (tietzeWord s)) v) :
    v ∈ Submodule.span (MonoidAlgebra ℤ (PresGroup (extRel ρ (tietzeWord s))))
      {w | ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧
        w = extCycleImage ρ (tietzeWord s) y} :=
  extCycle_mem_span ρ _ (fun x hx => by rwa [foxNew_tietze ρ s, mul_one] at hx) hinj hv

omit [Fintype α] [DecidableEq J] in
/-- **The HNN step of rule 1: `π₂` is generated by the image of the old `π₂`.**  The two
hypotheses are exactly the two facts quoted in the paper: the element along which the stable
letter conjugates has infinite order, and the old group embeds in the HNN extension. -/
theorem extCycle_hnn_span (u v : FreeGroup α)
    (hord : ¬ IsOfFinOrder (QuotientGroup.mk (FreeGroup.map Option.some v) :
      PresGroup (extRel ρ (hnnWord u v))))
    (hinj : Function.Injective (extHom ρ (hnnWord u v)))
    {c : Option J → MonoidAlgebra ℤ (PresGroup (extRel ρ (hnnWord u v)))}
    (hc : IsFoxCycle (extRel ρ (hnnWord u v)) c) :
    c ∈ Submodule.span (MonoidAlgebra ℤ (PresGroup (extRel ρ (hnnWord u v))))
      {w | ∃ y : J → MonoidAlgebra ℤ (PresGroup ρ), IsFoxCycle ρ y ∧
        w = extCycleImage ρ (hnnWord u v) y} :=
  extCycle_mem_span ρ _
    (fun x hx => mul_one_sub_single_eq_zero hord x (by rwa [foxNew_hnn ρ u v] at hx)) hinj hc

end FiniteChains
