module

public import RequestProject.SquareComplexWallSpace

@[expose] public section

/-!
# Walls of a simply connected square complex need not separate its vertices

`RequestProject/SquareComplexWalls.lean` proves, for a connected simply connected square complex,
the *two-sidedness* of walls and the existence of halfspace (Roller) coordinates, and
`RequestProject/SquareComplexWallSpace.lean` turns those coordinates into a wall space — but only
after assuming the remaining **separation** property (`hsep`: distinct vertices are separated by
some wall), which was recorded in `VERIFICATION.md` as the single remaining combinatorial gap of
Sageev's theorem in this branch.

This file shows that the gap cannot be closed as stated: separation is *not* a consequence of
connectedness, simple connectivity and the existence of a wall system.  The counterexample is the
smallest square-complex sphere: the complete bipartite graph `K_{2,3}` with all its three
four-cycles glued in (`FiniteChains.sphereCx`).  It is a two-sphere, hence simply connected, but its
links are triangles, so Gromov's link condition (nonpositive curvature) fails — and with it
separation:

* `FiniteChains.sphereCx_simplyConnected` — every closed walk contracts by elementary moves;
* `FiniteChains.sphereCx_connected` — the complex is connected;
* `FiniteChains.sphereWallSystem` — it carries a wall system (here a single wall containing all six
  edges, which is also the parallelism class generated by the squares);
* `FiniteChains.sphere_wall_side_eq` — for **every** wall label and every two-sided splitting of it,
  the two distinct vertices `a` and `b` lie on the same side;
* `FiniteChains.sphere_wallSystem_not_separating` — hence no wall system separates them;
* `FiniteChains.simplyConnected_not_separating` — therefore the hypothesis `hsep` of
  `FiniteChains.SquareComplex.wallSpaceOf` does not follow from the other hypotheses.

The reason is recorded too: the link of a vertex is a triangle
(`FiniteChains.sphere_link_triangle`), so the complex is not nonpositively curved; the same three
vertices `x, y, z` have two distinct medians `a` and `b` in the one-skeleton
(`FiniteChains.sphere_two_medians`), so the one-skeleton is not a median graph.  A correct version
of the missing step must therefore carry the link condition as a hypothesis.
-/

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

namespace FiniteChains

/-- The five vertices of the smallest square-complex sphere: the complete bipartite graph
`K_{2,3}` with its three four-cycles glued in. -/
inductive SphereV
  | a | b | x | y | z
  deriving DecidableEq, Fintype, Repr

namespace SphereV

/-- The bipartition of `K_{2,3}`: `a, b` on one side, `x, y, z` on the other. -/
def side : SphereV → Bool
  | a => true
  | b => true
  | _ => false

end SphereV

/-- Adjacency of `K_{2,3}`: two vertices are adjacent when they lie on opposite sides of the
bipartition. -/
def sphereAdj (u v : SphereV) : Prop := u.side ≠ v.side

instance : DecidableRel sphereAdj := fun _ _ => inferInstanceAs (Decidable (_ ≠ _))

/-- The two-cells: every four-cycle of `K_{2,3}` is glued in.  There are exactly three of them,
namely `a x b y`, `a y b z` and `a z b x`, read from any vertex and in either orientation. -/
def sphereSq (p q r s : SphereV) : Prop :=
  sphereAdj p q ∧ sphereAdj q r ∧ sphereAdj r s ∧ sphereAdj s p ∧ p ≠ r ∧ q ≠ s

instance : ∀ p q r s, Decidable (sphereSq p q r s) := fun _ _ _ _ =>
  inferInstanceAs (Decidable (_ ∧ _))

theorem sphereAdj_symm : ∀ u v : SphereV, sphereAdj u v → sphereAdj v u := by decide

theorem sphereAdj_irrefl : ∀ u : SphereV, ¬ sphereAdj u u := by decide

theorem sphereSq_adj : ∀ p q r s : SphereV, sphereSq p q r s →
    sphereAdj p q ∧ sphereAdj q r ∧ sphereAdj r s ∧ sphereAdj s p := by decide

theorem sphereSq_rotate : ∀ p q r s : SphereV, sphereSq p q r s → sphereSq q r s p := by decide

theorem sphereSq_reverse : ∀ p q r s : SphereV, sphereSq p q r s → sphereSq s r q p := by decide

/-- **The square-complex sphere**: `K_{2,3}` with its three four-cycles glued in.  Its geometric
realisation is a two-sphere built from three squares. -/
def sphereCx : SquareComplex SphereV where
  adj := sphereAdj
  adj_symm := fun {u v} h => sphereAdj_symm u v h
  adj_irrefl := sphereAdj_irrefl
  sq := sphereSq
  sq_adj := fun {p q r s} h => sphereSq_adj p q r s h
  sq_rotate := fun {p q r s} h => sphereSq_rotate p q r s h
  sq_reverse := fun {p q r s} h => sphereSq_reverse p q r s h

instance : DecidableRel sphereCx.adj := fun u v => inferInstanceAs (Decidable (sphereAdj u v))

instance : ∀ p q r s, Decidable (sphereCx.sq p q r s) := fun p q r s =>
  inferInstanceAs (Decidable (sphereSq p q r s))

/-- The three two-cells of the sphere. -/
theorem sphere_squares :
    sphereCx.sq .a .x .b .y ∧ sphereCx.sq .a .y .b .z ∧ sphereCx.sq .a .z .b .x := by
  refine ⟨?_, ?_, ?_⟩ <;> decide

/-- A chain for the adjacency relation is a walk of the complex. -/
theorem sphere_isWalk {l : List SphereV} (h : List.IsChain sphereAdj l) : sphereCx.IsWalk l := h

/-- Any three consecutive edges without a backtrack span a two-cell: this is where all three
squares are used, and it is what makes the sphere simply connected. -/
theorem sphere_three_span : ∀ p q r u : SphereV, sphereAdj p q → sphereAdj q r → sphereAdj r u →
    r ≠ p → u ≠ q → sphereSq p q r u := by decide

/-- **The sphere is simply connected**: every closed walk contracts to its base point by
elementary moves. -/
theorem sphereCx_simplyConnected : sphereCx.SimplyConnected := by
  have key : ∀ (n : ℕ) (w : SphereV) (l : List SphereV), l.length ≤ n →
      sphereCx.IsClosedWalk w l → sphereCx.Homotopic l [w] := by
    intro n
    induction n with
    | zero =>
        intro w l hlen hcw
        have : l = [] := List.eq_nil_of_length_eq_zero (Nat.le_zero.mp hlen)
        rw [this] at hcw
        exact absurd hcw.2.1 (by simp)
    | succ n ih =>
        intro w l hlen hcw
        match l with
        | [] => exact absurd hcw.2.1 (by simp)
        | [p] =>
            have hpw : p = w := by simpa using hcw.2.1
            rw [hpw]
            exact SquareComplex.Homotopic.refl _
        | [p, q] =>
            exfalso
            have hpw : p = w := by simpa using hcw.2.1
            have hqw : q = w := by simpa using hcw.2.2
            have hpq : sphereCx.adj p q := (List.isChain_cons_cons.mp hcw.1).1
            rw [hpw, hqw] at hpq
            exact sphereCx.adj_irrefl w hpq
        | p :: q :: r :: t =>
            have hchain := hcw.1
            have hpq : sphereCx.adj p q := (List.isChain_cons_cons.mp hchain).1
            have hqr : sphereCx.adj q r :=
              (List.isChain_cons_cons.mp (List.isChain_cons_cons.mp hchain).2).1
            by_cases hrp : r = p
            · subst hrp
              have hmove : sphereCx.Move (r :: q :: r :: t) (r :: t) :=
                SquareComplex.Move.backtrack r q t
              refine SquareComplex.Homotopic.head_move hmove (ih w (r :: t) ?_ ?_)
              · simp only [List.length_cons] at hlen ⊢; omega
              · exact SquareComplex.IsClosedWalk.of_move hmove hcw
            · match t with
              | [] =>
                  exfalso
                  have hpw : p = w := by simpa using hcw.2.1
                  have hrw : r = w := by simpa using hcw.2.2
                  exact hrp (by rw [hpw, hrw])
              | u :: t' =>
                  have hru : sphereCx.adj r u :=
                    (List.isChain_cons_cons.mp (List.isChain_cons_cons.mp
                      (List.isChain_cons_cons.mp hchain).2).2).1
                  by_cases huq : u = q
                  · subst huq
                    have hmove : sphereCx.Move (p :: u :: r :: u :: t') (p :: u :: t') :=
                      SquareComplex.Move.cons p (SquareComplex.Move.backtrack u r t')
                    refine SquareComplex.Homotopic.head_move hmove (ih w (p :: u :: t') ?_ ?_)
                    · simp only [List.length_cons] at hlen ⊢; omega
                    · exact SquareComplex.IsClosedWalk.of_move hmove hcw
                  · have hsq : sphereCx.sq p q r u :=
                      sphere_three_span p q r u hpq hqr hru hrp huq
                    have hmove1 :
                        sphereCx.Move (p :: q :: r :: u :: t') (p :: u :: r :: u :: t') :=
                      SquareComplex.Move.square hsq (u :: t')
                    have hmove2 : sphereCx.Move (p :: u :: r :: u :: t') (p :: u :: t') :=
                      SquareComplex.Move.cons p (SquareComplex.Move.backtrack u r t')
                    refine SquareComplex.Homotopic.head_move hmove1
                      (SquareComplex.Homotopic.head_move hmove2 (ih w (p :: u :: t') ?_ ?_))
                    · simp only [List.length_cons] at hlen ⊢; omega
                    · exact SquareComplex.IsClosedWalk.of_move hmove2
                        (SquareComplex.IsClosedWalk.of_move hmove1 hcw)
  intro w l hl
  exact key l.length w l le_rfl hl

/-- The sphere is connected. -/
theorem sphereCx_connected : ∀ v : SphereV, ∃ l, sphereCx.IsWalkFrom .a v l := by
  intro v
  cases v
  · exact ⟨[.a], List.isChain_singleton .., rfl, rfl⟩
  · exact ⟨[.a, .x, .b], sphere_isWalk (by decide), rfl, rfl⟩
  · exact ⟨[.a, .x], sphere_isWalk (by decide), rfl, rfl⟩
  · exact ⟨[.a, .y], sphere_isWalk (by decide), rfl, rfl⟩
  · exact ⟨[.a, .z], sphere_isWalk (by decide), rfl, rfl⟩

/-! ### Every wall of the sphere fails to separate `a` from `b` -/

/-- All six edges of the sphere are parallel: every square-closed label takes the same value on
`{a,x}` and on `{b,x}`.  (Chasing the three squares identifies all six edges, so the whole
one-skeleton is a single parallelism class — a self-intersecting "hyperplane".) -/
theorem sphere_wall_ax_eq_bx {χ : SphereV → SphereV → ZMod 2} (hχ : sphereCx.IsWallLabel χ) :
    χ .a .x = χ .b .x := by
  obtain ⟨sq₁, sq₂, sq₃⟩ := sphere_squares
  -- `sq a x b y` gives `χ x b = χ y a`
  have h₁ : χ .x .b = χ .y .a := hχ.square (sphereCx.sq_rotate sq₁)
  -- `sq a y b z` gives `χ a y = χ b z`
  have h₂ : χ .a .y = χ .b .z := hχ.square sq₂
  -- `sq a z b x` gives `χ z b = χ x a`
  have h₃ : χ .z .b = χ .x .a := hχ.square (sphereCx.sq_rotate sq₃)
  calc χ .a .x = χ .x .a := hχ.symm _ _
    _ = χ .z .b := h₃.symm
    _ = χ .b .z := hχ.symm _ _
    _ = χ .a .y := h₂.symm
    _ = χ .y .a := hχ.symm _ _
    _ = χ .x .b := h₁.symm
    _ = χ .b .x := hχ.symm _ _

/-- **The two vertices `a` and `b` lie on the same side of every wall.**  Here `χ` is an arbitrary
square-closed edge label and `σ` an arbitrary two-sided splitting of it, as produced by
`FiniteChains.SquareComplex.exists_side`. -/
theorem sphere_wall_side_eq {χ : SphereV → SphereV → ZMod 2} (hχ : sphereCx.IsWallLabel χ)
    {σ : SphereV → ZMod 2} (hσ : ∀ u v : SphereV, sphereCx.adj u v → σ u + σ v = χ u v) :
    σ .a = σ .b := by
  have hax : σ .a + σ .x = χ .a .x := hσ _ _ (by decide)
  have hbx : σ .b + σ .x = χ .b .x := hσ _ _ (by decide)
  have h := sphere_wall_ax_eq_bx hχ
  have : σ .a + σ .x = σ .b + σ .x := by rw [hax, hbx, h]
  exact add_right_cancel this

/-- The two vertices `a` and `b` are distinct. -/
theorem sphere_a_ne_b : (SphereV.a) ≠ (SphereV.b) := by decide

/-- The single wall of the sphere: all six edges.  (By `sphere_wall_ax_eq_bx` this is forced — the
squares identify all edges — so this is *the* wall system of the complex.) -/
def sphereWall (u v : SphereV) : ZMod 2 := if sphereAdj u v then 1 else 0

theorem sphereWall_isWallLabel : sphereCx.IsWallLabel sphereWall where
  symm := by decide
  square := by
    intro p q r s h
    have h' : sphereSq p q r s := h
    have hpq : sphereAdj p q := h'.1
    have hrs : sphereAdj r s := h'.2.2.1
    simp [sphereWall, hpq, hrs]

/-- The sphere carries a wall system: a single wall, crossed by every edge exactly once. -/
def sphereWallSystem : sphereCx.WallSystem Unit where
  χ := fun _ => sphereWall
  isWall := fun _ => sphereWall_isWallLabel
  edge_unique := by
    intro u v huv
    refine ⟨(), ?_, ?_⟩
    · have h : sphereAdj u v := huv
      simp [sphereWall, h]
    · intro j _
      rfl

/-- **No wall system of the sphere separates `a` from `b`.**  This refutes the separation
hypothesis `hsep` of `FiniteChains.SquareComplex.wallSpaceOf` for general connected simply
connected square complexes. -/
theorem sphere_wallSystem_not_separating {ι : Type*} (W : sphereCx.WallSystem ι)
    (σ : ι → SphereV → ZMod 2)
    (hσ : ∀ (i : ι) (u v : SphereV), sphereCx.adj u v → σ i u + σ i v = W.χ i u v) :
    ∀ i : ι, σ i .a = σ i .b :=
  fun i => sphere_wall_side_eq (W.isWall i) (hσ i)

/-- **Simple connectivity does not imply separation.**  There is a connected, simply connected
square complex with two distinct vertices lying on the same side of every wall.  Consequently the
hypothesis `hsep` of `FiniteChains.SquareComplex.wallSpaceOf` — the remaining step of Sageev's
theorem in this branch — does not follow from the hypotheses proved in
`RequestProject/SquareComplexWalls.lean`; a correct statement has to assume nonpositive curvature
(the link condition), which fails here by `FiniteChains.sphere_link_triangle`. -/
theorem simplyConnected_not_separating :
    ∃ (V : Type) (S : SquareComplex V) (x₀ : V),
      S.SimplyConnected ∧ (∀ v : V, ∃ l, S.IsWalkFrom x₀ v l) ∧
        ∃ u v : V, u ≠ v ∧ ∀ χ : V → V → ZMod 2, S.IsWallLabel χ →
          ∀ σ : V → ZMod 2, (∀ p q : V, S.adj p q → σ p + σ q = χ p q) → σ u = σ v := by
  refine ⟨SphereV, sphereCx, .a, sphereCx_simplyConnected, sphereCx_connected,
    .a, .b, sphere_a_ne_b, ?_⟩
  intro χ hχ σ hσ
  exact sphere_wall_side_eq hχ hσ

/-! ### Why it fails: the link condition and medianness -/

/-- Two vertices are adjacent in the link of `w` when they are the two neighbours of `w` in some
two-cell of the complex. -/
def sphereLinkAdj (w p q : SphereV) : Prop := ∃ m : SphereV, sphereCx.sq p w q m

/-- **The link of the vertex `a` is a triangle**: its three vertices `x, y, z` are pairwise joined
by link edges, so the link has a cycle of length three.  Gromov's link condition (links are flag,
in particular have no cycles of length three) therefore fails, and the complex is not nonpositively
curved — as it must not be, being a two-sphere. -/
theorem sphere_link_triangle :
    sphereLinkAdj .a .x .y ∧ sphereLinkAdj .a .y .z ∧ sphereLinkAdj .a .z .x :=
  ⟨⟨.b, by decide⟩, ⟨.b, by decide⟩, ⟨.b, by decide⟩⟩

/-- The link vertices `x, y, z` are pairwise non-adjacent in the one-skeleton, so the triangle of
`sphere_link_triangle` is a genuine cycle of the link and not a degenerate one. -/
theorem sphere_link_vertices_not_adj :
    ¬ sphereCx.adj .x .y ∧ ¬ sphereCx.adj .y .z ∧ ¬ sphereCx.adj .z .x := by
  refine ⟨?_, ?_, ?_⟩ <;> decide

/-- **The one-skeleton is not a median graph**: the three vertices `x, y, z` have two distinct
medians, `a` and `b`, both adjacent to all three.  This is the failure, for the sphere, of the
conclusion of Chepoi's theorem — one more reason why the link condition cannot be dropped. -/
theorem sphere_two_medians :
    (SphereV.a) ≠ (SphereV.b) ∧
      (∀ p : SphereV, p ≠ .a → p ≠ .b → sphereCx.adj .a p ∧ sphereCx.adj .b p) := by
  refine ⟨sphere_a_ne_b, ?_⟩
  decide

end FiniteChains
