import RequestProject.SquareComplexWalls

/-!
# Homotopy through walks

The elementary moves of `FiniteChains.SquareComplex.Move` may be applied to an arbitrary list of
vertices; in particular `Move.backtrack x y q` inserts the detour `x, y, x` even when `x` and `y`
are *not* joined by an edge.  For all the invariants studied in
`RequestProject/SquareComplexWalls.lean` (crossing numbers modulo two) this is harmless, and it
makes the hypothesis `SimplyConnected` weaker, hence the theorems using it stronger.

For lifting homotopies to a covering, however, such detours are genuinely inconvenient: an edge of
the base lifts to an edge of the covering, but a non-edge lifts to nothing.  This file therefore
introduces the homotopy relation in which every intermediate stage is a walk:

* `FiniteChains.SquareComplex.WalkMove` — an elementary move, in either direction, between two
  walks;
* `FiniteChains.SquareComplex.WalkHomotopic` — the equivalence relation it generates;
* `FiniteChains.SquareComplex.SimplyConnectedW` — every closed walk contracts to its base point
  through walks.

The two notions are compared: `WalkHomotopic.homotopic` and `SimplyConnectedW.simplyConnected`
show that the new relation is finer, so every result proved for `SimplyConnected` complexes
applies to `SimplyConnectedW` ones.
-/

namespace FiniteChains

namespace SquareComplex

universe u

variable {Vx : Type u} {S : SquareComplex Vx}

/-- An elementary move, in either direction, whose source *and* target are walks.  Recording the
walk on the side the move starts from is enough: elementary moves take walks to walks. -/
def WalkMove (S : SquareComplex Vx) (l l' : List Vx) : Prop :=
  (S.Move l l' ∧ S.IsWalk l) ∨ (S.Move l' l ∧ S.IsWalk l')

theorem WalkMove.symm {l l' : List Vx} (h : S.WalkMove l l') : S.WalkMove l' l := Or.symm h

theorem WalkMove.isWalk_left {l l' : List Vx} (h : S.WalkMove l l') : S.IsWalk l := by
  rcases h with ⟨hm, hw⟩ | ⟨hm, hw⟩
  · exact hw
  · exact hm.isWalk hw

theorem WalkMove.isWalk_right {l l' : List Vx} (h : S.WalkMove l l') : S.IsWalk l' :=
  h.symm.isWalk_left

/-- Homotopy of walks through walks: the equivalence relation generated by `WalkMove`. -/
def WalkHomotopic (S : SquareComplex Vx) (l l' : List Vx) : Prop :=
  Relation.ReflTransGen (S.WalkMove) l l'

theorem WalkHomotopic.refl (l : List Vx) : S.WalkHomotopic l l := Relation.ReflTransGen.refl

theorem WalkHomotopic.trans {l l' l'' : List Vx} (h : S.WalkHomotopic l l')
    (h' : S.WalkHomotopic l' l'') : S.WalkHomotopic l l'' := Relation.ReflTransGen.trans h h'

theorem WalkHomotopic.of_walkMove {l l' : List Vx} (h : S.WalkMove l l') : S.WalkHomotopic l l' :=
  Relation.ReflTransGen.single h

theorem WalkHomotopic.head_walkMove {l l' l'' : List Vx} (h : S.WalkMove l l')
    (h' : S.WalkHomotopic l' l'') : S.WalkHomotopic l l'' := Relation.ReflTransGen.head h h'

theorem WalkHomotopic.symm {l l' : List Vx} (h : S.WalkHomotopic l l') : S.WalkHomotopic l' l := by
  induction h with
  | refl => exact WalkHomotopic.refl _
  | tail _ hstep ih => exact (WalkHomotopic.of_walkMove hstep.symm).trans ih

/-- A homotopy through walks is in particular a homotopy. -/
theorem WalkHomotopic.homotopic {l l' : List Vx} (h : S.WalkHomotopic l l') : S.Homotopic l l' := by
  induction h with
  | refl => exact Homotopic.refl _
  | tail _ hstep ih =>
      refine ih.trans (Relation.ReflTransGen.single ?_)
      rcases hstep with ⟨hm, _⟩ | ⟨hm, _⟩
      · exact Or.inl hm
      · exact Or.inr hm

theorem WalkHomotopic.head?_eq {l l' : List Vx} (h : S.WalkHomotopic l l') :
    l.head? = l'.head? := h.homotopic.head?_eq

theorem WalkHomotopic.getLast?_eq {l l' : List Vx} (h : S.WalkHomotopic l l') :
    l.getLast? = l'.getLast? := h.homotopic.getLast?_eq

/-- Every stage of a homotopy through walks is a walk. -/
theorem WalkHomotopic.isWalk {l l' : List Vx} (h : S.WalkHomotopic l l') (hl : S.IsWalk l) :
    S.IsWalk l' := by
  induction h with
  | refl => exact hl
  | tail _ hstep ih => exact hstep.isWalk_right

/-- Elementary moves may be performed after a common initial vertex. -/
theorem WalkMove.cons {x : Vx} {l l' : List Vx} (hx : ∀ y, l.head? = some y → S.adj x y)
    (h : S.WalkMove l l') : S.WalkMove (x :: l) (x :: l') := by
  have hhead : l.head? = l'.head? := by
    rcases h with ⟨hm, _⟩ | ⟨hm, _⟩
    · exact hm.head?_eq
    · exact hm.head?_eq.symm
  have hcons : ∀ (m : List Vx), S.IsWalk m → l.head? = m.head? → S.IsWalk (x :: m) := by
    intro m hm hmh
    cases m with
    | nil => simp [IsWalk]
    | cons b t =>
        rw [IsWalk, List.isChain_cons_cons]
        exact ⟨hx b (by rw [hmh]; rfl), hm⟩
  rcases h with ⟨hm, hw⟩ | ⟨hm, hw⟩
  · exact Or.inl ⟨Move.cons x hm, hcons l hw rfl⟩
  · exact Or.inr ⟨Move.cons x hm, hcons l' hw hhead⟩

/-- Homotopies through walks may be performed after a common initial vertex. -/
theorem WalkHomotopic.cons {x : Vx} {l l' : List Vx}
    (hx : ∀ y, l.head? = some y → S.adj x y) (h : S.WalkHomotopic l l') :
    S.WalkHomotopic (x :: l) (x :: l') := by
  induction h with
  | refl => exact WalkHomotopic.refl _
  | @tail b c hlb hstep ih =>
      have hhb : l.head? = b.head? := (show S.WalkHomotopic l b from hlb).head?_eq
      refine (ih).trans (WalkHomotopic.of_walkMove (WalkMove.cons ?_ hstep))
      intro y hy
      exact hx y (by rw [hhb]; exact hy)

/-- A square complex is **simply connected through walks** when every closed walk can be contracted
to its base point by elementary moves all of whose stages are walks. -/
def SimplyConnectedW (S : SquareComplex Vx) : Prop :=
  ∀ (x : Vx) (l : List Vx), S.IsClosedWalk x l → S.WalkHomotopic l [x]

theorem SimplyConnectedW.simplyConnected (h : S.SimplyConnectedW) : S.SimplyConnected :=
  fun x l hl => (h x l hl).homotopic

end SquareComplex

end FiniteChains
