module

public import RequestProject.SquareComplexWalkHomotopy

@[expose] public section

/-!
# Combinatorial covering theory of square complexes

This file develops, from scratch, the covering theory of square complexes in the combinatorial
category: walks are lists of vertices, homotopy is generated by the elementary moves of
`RequestProject/SquareComplexWalls.lean`, and a covering is a map of complexes with unique edge
lifting and square lifting.

* `FiniteChains.SquareComplex.IsCovering` — the definition;
* `FiniteChains.SquareComplex.IsCovering.exists_lift`,
  `FiniteChains.SquareComplex.IsCovering.lift_unique` — **unique walk lifting**;
* `FiniteChains.SquareComplex.IsCovering.lift_walkHomotopic` — **homotopy lifting**: homotopic
  walks of the base with a common initial point have homotopic lifts, in particular lifts with a
  common terminal point (`FiniteChains.SquareComplex.IsCovering.getLast_lift_eq`);
* `FiniteChains.SquareComplex.IsCovering.injective_of_simplyConnectedW`,
  `FiniteChains.SquareComplex.IsCovering.surjective_of_walkConnected`,
  `FiniteChains.SquareComplex.IsCovering.bijective_of_simplyConnectedW` — a covering of a
  connected, simply connected base by a connected complex is a bijection, and it reflects edges
  and squares (`FiniteChains.SquareComplex.IsCovering.adj_of_map_adj`,
  `FiniteChains.SquareComplex.IsCovering.sq_of_map_sq`), hence is an isomorphism.

The lifting criterion and the uniqueness of the universal cover are in
`RequestProject/SquareComplexUniversalCover.lean`.

Throughout, simple connectivity is taken in the form `SimplyConnectedW` of
`RequestProject/SquareComplexWalkHomotopy.lean` (contraction through walks), which is what a
covering can lift: an edge of the base lifts to an edge of the covering, whereas the detours
`x, y, x` allowed by the coarser relation `Homotopic` need not even be edges.
-/

namespace FiniteChains

namespace SquareComplex

universe u v w

variable {Vx : Type u}

/-- Prefixing a walk with a vertex adjacent to its initial vertex gives a walk. -/
theorem isWalk_cons {S : SquareComplex Vx} {x : Vx} {l : List Vx} (hl : S.IsWalk l)
    (h : ∀ y, l.head? = some y → S.adj x y) : S.IsWalk (x :: l) := by
  cases l with
  | nil => simp [IsWalk]
  | cons b t =>
      rw [IsWalk, List.isChain_cons_cons]
      exact ⟨h b rfl, hl⟩


/-! ### Connectivity -/

/-- `S.ReachableFrom x y` : some walk joins `x` to `y`. -/
def ReachableFrom (S : SquareComplex Vx) (x y : Vx) : Prop := ∃ l, S.IsWalkFrom x y l

/-- A square complex is **connected** when any two vertices are joined by a walk. -/
def WalkConnected (S : SquareComplex Vx) : Prop := ∀ x y : Vx, S.ReachableFrom x y

variable {S : SquareComplex Vx}

theorem isWalkFrom_reverse {x y : Vx} {l : List Vx} (h : S.IsWalkFrom x y l) :
    S.IsWalkFrom y x l.reverse :=
  ⟨isWalk_reverse h.1, by simpa using h.2.2, by simpa using h.2.1⟩

/-- Walks compose: glueing `m` to `l` at their common endpoint gives a walk. -/
theorem isWalkFrom_append {x y z : Vx} {l m : List Vx} (hl : S.IsWalkFrom x y l)
    (hm : S.IsWalkFrom y z m) : S.IsWalkFrom x z (l ++ m.tail) := by
  obtain ⟨hlw, hlh, hll⟩ := hl
  obtain ⟨hmw, hmh, hml⟩ := hm
  obtain ⟨b, r, rfl⟩ : ∃ b r, m = b :: r := by
    cases m with
    | nil => simp at hmh
    | cons b r => exact ⟨b, r, rfl⟩
  have hby : b = y := by simpa using hmh
  subst hby
  have hlne : l ≠ [] := by intro h; rw [h] at hlh; simp at hlh
  refine ⟨?_, ?_, ?_⟩
  · rw [IsWalk, List.isChain_append]
    refine ⟨hlw, hmw.tail, ?_⟩
    intro a ha c hc
    rw [hll] at ha
    simp only [Option.mem_def, Option.some.injEq] at ha
    subst ha
    simp only [List.tail_cons] at hc
    exact isWalk_junction hmw hc
  · rw [List.head?_append_of_ne_nil l hlne]
    exact hlh
  · simp only [List.tail_cons]
    cases hr : r with
    | nil =>
        rw [hr] at hml
        simp only [List.getLast?_singleton, Option.some.injEq] at hml
        subst hml
        simpa using hll
    | cons c r' =>
        rw [List.getLast?_append_of_ne_nil l (by simp)]
        rw [hr] at hml
        simpa using hml

theorem ReachableFrom.trans {x y z : Vx} (h : S.ReachableFrom x y) (h' : S.ReachableFrom y z) :
    S.ReachableFrom x z := by
  obtain ⟨l, hl⟩ := h
  obtain ⟨m, hm⟩ := h'
  exact ⟨l ++ m.tail, isWalkFrom_append hl hm⟩

theorem ReachableFrom.symm {x y : Vx} (h : S.ReachableFrom x y) : S.ReachableFrom y x := by
  obtain ⟨l, hl⟩ := h
  exact ⟨l.reverse, isWalkFrom_reverse hl⟩

theorem ReachableFrom.refl (x : Vx) : S.ReachableFrom x x :=
  ⟨[x], by simp [IsWalk], rfl, rfl⟩

/-- The support of a walk of a simple graph is a walk of any square complex whose one-skeleton
contains that graph. -/
theorem isWalkFrom_support {G : SimpleGraph Vx} (hadj : ∀ u v : Vx, G.Adj u v → S.adj u v) :
    ∀ {x y : Vx} (w : G.Walk x y), S.IsWalkFrom x y w.support := by
  intro x y w
  induction w with
  | nil => exact ⟨by simp [IsWalk], rfl, rfl⟩
  | @cons a b c hab q ih =>
      obtain ⟨hq, hqh, hql⟩ := ih
      obtain ⟨z, r, hzr⟩ : ∃ z r, q.support = z :: r := by
        cases hc : q.support with
        | nil => rw [hc] at hqh; simp at hqh
        | cons z r => exact ⟨z, r, rfl⟩
      refine ⟨isWalk_cons hq ?_, by simp, ?_⟩
      · intro y' hy'
        rw [hqh] at hy'
        cases hy'
        exact hadj _ _ hab
      · rw [SimpleGraph.Walk.support_cons, hzr]
        rw [hzr] at hql
        simpa using hql

/-- A square complex whose one-skeleton contains a connected graph is connected. -/
theorem walkConnected_of_connected {G : SimpleGraph Vx} (hadj : ∀ u v : Vx, G.Adj u v → S.adj u v)
    (hG : G.Connected) : S.WalkConnected :=
  fun x y => ⟨(hG x y).some.support, isWalkFrom_support hadj (hG x y).some⟩

theorem ReachableFrom.of_adj {x y : Vx} (h : S.adj x y) : S.ReachableFrom x y := by
  refine ⟨[x, y], ?_, rfl, rfl⟩
  rw [IsWalk, List.isChain_cons_cons]
  exact ⟨h, by simp⟩

variable {Vt : Type u} {Vb : Type v} {Vs : Type w}
variable {T : SquareComplex Vt} {B : SquareComplex Vb} {p : Vt → Vb}

/-- A **combinatorial covering** `p : T → B` of square complexes: `p` preserves edges and squares,
every edge of the base issuing from `p x` has a unique lift issuing from `x`, and every square of
the base having `p a` as a vertex is the image of a square having `a` as the corresponding
vertex. -/
structure IsCovering (T : SquareComplex Vt) (B : SquareComplex Vb) (p : Vt → Vb) : Prop where
  /-- `p` is a map of one-skeleta. -/
  map_adj : ∀ {x y : Vt}, T.adj x y → B.adj (p x) (p y)
  /-- `p` maps squares to squares. -/
  map_sq : ∀ {a b c d : Vt}, T.sq a b c d → B.sq (p a) (p b) (p c) (p d)
  /-- Unique edge lifting. -/
  lift_adj : ∀ (x : Vt) {w : Vb}, B.adj (p x) w → ∃! y : Vt, T.adj x y ∧ p y = w
  /-- Square lifting. -/
  lift_sq : ∀ (a : Vt) {b c d : Vb}, B.sq (p a) b c d →
    ∃ b' c' d' : Vt, T.sq a b' c' d' ∧ p b' = b ∧ p c' = c ∧ p d' = d

namespace IsCovering

variable (hp : IsCovering T B p)
include hp

/-- Two edges issuing from the same vertex with the same image agree. -/
theorem edge_unique {x y y' : Vt} (h : T.adj x y) (h' : T.adj x y') (he : p y = p y') : y = y' := by
  obtain ⟨z, -, hz⟩ := hp.lift_adj x (hp.map_adj h)
  rw [hz y ⟨h, rfl⟩, hz y' ⟨h', he.symm⟩]

/-- A covering has no loops in its fibres: an edge of `T` never maps to a single vertex. -/
theorem ne_of_adj {x y : Vt} (h : T.adj x y) : p x ≠ p y := by
  intro he
  have hadj : B.adj (p x) (p y) := hp.map_adj h
  rw [← he] at hadj
  exact B.adj_irrefl (p x) hadj

/-- The image of a walk is a walk. -/
theorem map_isWalk : ∀ {lt : List Vt}, T.IsWalk lt → B.IsWalk (lt.map p) := by
  intro lt
  induction lt with
  | nil => intro _; simp [IsWalk]
  | cons a t ih =>
      cases t with
      | nil => intro _; simp [IsWalk]
      | cons b s =>
          intro h
          rw [IsWalk, List.isChain_cons_cons] at h
          simp only [List.map_cons]
          rw [IsWalk, List.isChain_cons_cons]
          exact ⟨hp.map_adj h.1, ih h.2⟩

/-- **Uniqueness of lifts**: two walks of `T` with the same initial vertex and the same image
coincide. -/
theorem lift_unique : ∀ {lt lt' : List Vt}, T.IsWalk lt → T.IsWalk lt' →
    lt.head? = lt'.head? → lt.map p = lt'.map p → lt = lt' := by
  intro lt
  induction lt with
  | nil =>
      intro lt' _ _ hh _
      cases lt' with
      | nil => rfl
      | cons a t => simp at hh
  | cons a t ih =>
      intro lt' hw hw' hh hm
      cases lt' with
      | nil => simp at hh
      | cons a' t' =>
          simp only [List.head?_cons, Option.some.injEq] at hh
          subst hh
          cases t with
          | nil =>
              cases t' with
              | nil => rfl
              | cons b' s' => simp at hm
          | cons b s =>
              cases t' with
              | nil => simp at hm
              | cons b' s' =>
                  rw [IsWalk, List.isChain_cons_cons] at hw hw'
                  simp only [List.map_cons, List.cons.injEq] at hm
                  have hbb : b = b' := hp.edge_unique hw.1 hw'.1 hm.2.1
                  subst hbb
                  have := ih hw.2 hw'.2 rfl (by simpa using hm.2.2)
                  rw [this]

/-- **Existence of lifts**: a walk of the base issuing from `p x` is the image of a (unique) walk
of `T` issuing from `x`. -/
theorem exists_lift : ∀ (l : List Vb) (x : Vt), B.IsWalk l → l.head? = some (p x) →
    ∃ lt : List Vt, T.IsWalk lt ∧ lt.head? = some x ∧ lt.map p = l := by
  intro l
  induction l with
  | nil => intro x _ hh; simp at hh
  | cons a t ih =>
      intro x hw hh
      simp only [List.head?_cons, Option.some.injEq] at hh
      subst hh
      cases t with
      | nil => exact ⟨[x], by simp [IsWalk], by simp, by simp⟩
      | cons b s =>
          rw [IsWalk, List.isChain_cons_cons] at hw
          obtain ⟨y, hxy, hpy⟩ := (hp.lift_adj x hw.1).exists
          obtain ⟨lt, hlt, hhlt, hmap⟩ := ih y hw.2 (by rw [hpy]; rfl)
          refine ⟨x :: lt, isWalk_cons hlt ?_, by simp, by simp [hmap]⟩
          intro y' hy'
          rw [hhlt] at hy'
          cases hy'
          exact hxy

/-- **Lifting an elementary move**: if the walk `lt` of `T` lies over `l` and `l` moves to `l'`,
then `lt` is homotopic, through walks, to a walk lying over `l'` with the same initial vertex. -/
theorem lift_move {l l' : List Vb} (hm : B.Move l l') :
    ∀ {lt : List Vt}, T.IsWalk lt → lt.map p = l →
      ∃ lt' : List Vt, T.IsWalk lt' ∧ lt'.head? = lt.head? ∧ lt'.map p = l' ∧
        T.WalkHomotopic lt lt' := by
  induction hm with
  | backtrack x₀ y q =>
      rintro (_ | ⟨a, _ | ⟨b, _ | ⟨c, qt⟩⟩⟩) hlt hmap
      · simp at hmap
      · simp at hmap
      · simp at hmap
      obtain ⟨hpa, hpb, hpc, hmq⟩ : p a = x₀ ∧ p b = y ∧ p c = x₀ ∧ qt.map p = q := by
        simpa [and_assoc] using hmap
      rw [IsWalk, List.isChain_cons_cons, List.isChain_cons_cons] at hlt
      obtain ⟨hab, hbc, hqt⟩ := hlt
      have hca : c = a := hp.edge_unique hbc (T.adj_symm hab) (by rw [hpc, hpa])
      subst hca
      have hmove : T.Move (c :: b :: c :: qt) (c :: qt) := Move.backtrack c b qt
      refine ⟨c :: qt, hmove.isWalk ?_, by simp, by simp [hpa, hmq], ?_⟩
      · rw [IsWalk, List.isChain_cons_cons, List.isChain_cons_cons]
        exact ⟨hab, hbc, hqt⟩
      · refine WalkHomotopic.of_walkMove (Or.inl ⟨hmove, ?_⟩)
        rw [IsWalk, List.isChain_cons_cons, List.isChain_cons_cons]
        exact ⟨hab, hbc, hqt⟩
  | @square a b c d hsq q =>
      rintro (_ | ⟨a', _ | ⟨b', _ | ⟨c', qt⟩⟩⟩) hlt hmap
      · simp at hmap
      · simp at hmap
      · simp at hmap
      obtain ⟨hpa, hpb, hpc, hmq⟩ : p a' = a ∧ p b' = b ∧ p c' = c ∧ qt.map p = q := by
        simpa [and_assoc] using hmap
      rw [IsWalk, List.isChain_cons_cons, List.isChain_cons_cons] at hlt
      obtain ⟨hab, hbc, hqt⟩ := hlt
      obtain ⟨b₂, c₂, d₂, hsq₂, hpb₂, hpc₂, hpd₂⟩ := hp.lift_sq a' (by rw [hpa]; exact hsq)
      obtain ⟨hab₂, hbc₂, hcd₂, hda₂⟩ := T.sq_adj hsq₂
      have hb : b₂ = b' := hp.edge_unique hab₂ hab (by rw [hpb₂, hpb])
      subst hb
      have hc : c₂ = c' := hp.edge_unique hbc₂ hbc (by rw [hpc₂, hpc])
      subst hc
      have hmove : T.Move (a' :: b₂ :: c₂ :: qt) (a' :: d₂ :: c₂ :: qt) := Move.square hsq₂ qt
      have hwalk : T.IsWalk (a' :: b₂ :: c₂ :: qt) := by
        rw [IsWalk, List.isChain_cons_cons, List.isChain_cons_cons]
        exact ⟨hab, hbc, hqt⟩
      exact ⟨a' :: d₂ :: c₂ :: qt, hmove.isWalk hwalk, by simp,
        by simp [hpa, hpc₂, hpd₂, hmq], WalkHomotopic.of_walkMove (Or.inl ⟨hmove, hwalk⟩)⟩
  | @cons x₀ l₀ l₀' hm ih =>
      rintro (_ | ⟨a, t⟩) hlt hmap
      · simp at hmap
      obtain ⟨hpa, hmt⟩ : p a = x₀ ∧ t.map p = l₀ := by simpa using hmap
      have hwt : T.IsWalk t := by
        cases t with
        | nil => simp [IsWalk]
        | cons b s => exact (List.isChain_cons_cons.mp hlt).2
      obtain ⟨t', hwt', hht', hmt', hhom⟩ := ih hwt hmt
      have hadj : ∀ y, t.head? = some y → T.adj a y := by
        intro y hy
        cases t with
        | nil => simp at hy
        | cons b s =>
            simp only [List.head?_cons, Option.some.injEq] at hy
            subst hy
            exact (List.isChain_cons_cons.mp hlt).1
      refine ⟨a :: t', isWalk_cons hwt' ?_, by simp, by simp [hpa, hmt'], ?_⟩
      · intro y hy
        exact hadj y (by rw [← hht']; exact hy)
      · exact WalkHomotopic.cons hadj hhom

/-- **Lifting a homotopy through walks**. -/
theorem lift_walkHomotopic {l l' : List Vb} (hh : B.WalkHomotopic l l') :
    ∀ {lt : List Vt}, T.IsWalk lt → lt.map p = l →
      ∃ lt' : List Vt, T.IsWalk lt' ∧ lt'.head? = lt.head? ∧ lt'.map p = l' ∧
        T.WalkHomotopic lt lt' := by
  induction hh with
  | refl => exact fun hlt hmap => ⟨_, hlt, rfl, hmap, WalkHomotopic.refl _⟩
  | @tail m m' _ hstep ih =>
      intro lt hlt hmap
      obtain ⟨mt, hwmt, hhmt, hmmt, hhom⟩ := ih hlt hmap
      rcases hstep with ⟨hmove, -⟩ | ⟨hmove, hwm'⟩
      · obtain ⟨mt', hwmt', hhmt', hmmt', hhom'⟩ := hp.lift_move hmove hwmt hmmt
        exact ⟨mt', hwmt', hhmt'.trans hhmt, hmmt', hhom.trans hhom'⟩
      · -- the move goes the other way: lift `m'` and use uniqueness of lifts
        obtain ⟨x, hx⟩ : ∃ x, mt.head? = some x := by
          cases mt with
          | nil =>
              rw [List.map_nil] at hmmt
              exact absurd hmmt.symm hmove.ne_nil.2
          | cons a s => exact ⟨a, rfl⟩
        have hmh : m.head? = some (p x) := by
          rw [← hmmt, List.head?_map, hx]; rfl
        have hpx : m'.head? = some (p x) := by rw [hmove.head?_eq, hmh]
        obtain ⟨nt, hwnt, hhnt, hmnt⟩ := hp.exists_lift m' x hwm' hpx
        obtain ⟨mt₂, hwmt₂, hhmt₂, hmmt₂, hhom₂⟩ := hp.lift_move hmove hwnt hmnt
        have hmt₂ : mt₂ = mt := hp.lift_unique hwmt₂ hwmt (by rw [hhmt₂, hhnt, hx]) (by
          rw [hmmt₂, hmmt])
        subst hmt₂
        refine ⟨nt, hwnt, ?_, hmnt, hhom.trans hhom₂.symm⟩
        rw [hhnt, ← hx, hhmt]

/-! ### Coverings of a simply connected base -/

/-- **The lift of a closed walk of a simply connected base is closed.** -/
theorem lift_closed (hSC : B.SimplyConnectedW) {x : Vt} {lt : List Vt} (hlt : T.IsWalk lt)
    (hh : lt.head? = some x) (hlast : (lt.map p).getLast? = some (p x)) :
    lt.getLast? = some x := by
  have hhead : (lt.map p).head? = some (p x) := by rw [List.head?_map, hh]; rfl
  have hcw : B.IsClosedWalk (p x) (lt.map p) := ⟨hp.map_isWalk hlt, hhead, hlast⟩
  obtain ⟨lt', hw', hh', hm', hhom⟩ := hp.lift_walkHomotopic (hSC (p x) _ hcw) hlt rfl
  obtain ⟨z, r, rfl⟩ : ∃ z r, lt' = z :: r := by
    cases lt' with
    | nil => rw [List.map_nil] at hm'; exact absurd hm' (by simp)
    | cons z r => exact ⟨z, r, rfl⟩
  simp only [List.map_cons, List.cons.injEq] at hm'
  have hr : r = [] := by simpa using hm'.2
  subst hr
  have hzx : z = x := by rw [hh] at hh'; simpa using hh'
  subst hzx
  rw [hhom.getLast?_eq]
  simp

/-- **A covering of a simply connected base is injective on each connected piece.** -/
theorem injOn_reachable (hSC : B.SimplyConnectedW) {x₀ x y : Vt} (hx : T.ReachableFrom x₀ x)
    (hy : T.ReachableFrom x₀ y) (hxy : p x = p y) : x = y := by
  obtain ⟨l, hl⟩ := hx.symm
  obtain ⟨m, hm⟩ := hy
  have hw : T.IsWalkFrom x y (l ++ m.tail) := isWalkFrom_append hl hm
  have hlast : ((l ++ m.tail).map p).getLast? = some (p x) := by
    rw [List.getLast?_map, hw.2.2]
    simp [hxy]
  have hend := hp.lift_closed hSC hw.1 hw.2.1 hlast
  have : some y = some x := hw.2.2.symm.trans hend
  simpa using this.symm

/-- A covering of a simply connected base by a connected complex is injective. -/
theorem injective_of_simplyConnectedW (hSC : B.SimplyConnectedW) (hT : T.WalkConnected) :
    Function.Injective p :=
  fun x y h => hp.injOn_reachable hSC (ReachableFrom.refl x) (hT x y) h

/-- Every vertex of the base reachable from `p x₀` is the image of a vertex reachable from
`x₀`. -/
theorem exists_reachable_over {x₀ : Vt} {b : Vb} (h : B.ReachableFrom (p x₀) b) :
    ∃ x : Vt, T.ReachableFrom x₀ x ∧ p x = b := by
  obtain ⟨l, hl⟩ := h
  obtain ⟨lt, hwt, hht, hmt⟩ := hp.exists_lift l x₀ hl.1 hl.2.1
  have hmap : (lt.map p).getLast? = some b := by rw [hmt]; exact hl.2.2
  rw [List.getLast?_map] at hmap
  obtain ⟨z, hz⟩ : ∃ z, lt.getLast? = some z := by
    cases hc : lt.getLast? with
    | none => rw [hc] at hmap; simp at hmap
    | some z => exact ⟨z, rfl⟩
  rw [hz] at hmap
  exact ⟨z, ⟨lt, hwt, hht, hz⟩, by simpa using hmap⟩

/-- A covering of a connected base is surjective. -/
theorem surjective_of_walkConnected (hB : B.WalkConnected) (x₀ : Vt) : Function.Surjective p := by
  intro b
  obtain ⟨l, hl⟩ := hB (p x₀) b
  obtain ⟨lt, hwt, hht, hmt⟩ := hp.exists_lift l x₀ hl.1 hl.2.1
  have hmap : (lt.map p).getLast? = some b := by rw [hmt]; exact hl.2.2
  rw [List.getLast?_map] at hmap
  obtain ⟨z, hz⟩ : ∃ z, lt.getLast? = some z := by
    cases h : lt.getLast? with
    | none => rw [h] at hmap; simp at hmap
    | some z => exact ⟨z, rfl⟩
  rw [hz] at hmap
  exact ⟨z, by simpa using hmap⟩

/-- An injective covering reflects edges. -/
theorem adj_of_map_adj (hinj : Function.Injective p) {x y : Vt} (h : B.adj (p x) (p y)) :
    T.adj x y := by
  obtain ⟨z, hxz, hpz⟩ := (hp.lift_adj x h).exists
  rwa [hinj hpz] at hxz

/-- An injective covering reflects squares. -/
theorem sq_of_map_sq (hinj : Function.Injective p) {a b c d : Vt}
    (h : B.sq (p a) (p b) (p c) (p d)) : T.sq a b c d := by
  obtain ⟨b', c', d', hsq, hb, hc, hd⟩ := hp.lift_sq a h
  rw [hinj hb, hinj hc, hinj hd] at hsq
  exact hsq

/-- **A covering of a connected, simply connected base by a connected complex is an
isomorphism.** -/
theorem bijective_of_simplyConnectedW (hSC : B.SimplyConnectedW) (hT : T.WalkConnected)
    (hB : B.WalkConnected) (x₀ : Vt) : Function.Bijective p :=
  ⟨hp.injective_of_simplyConnectedW hSC hT, hp.surjective_of_walkConnected hB x₀⟩

end IsCovering

end SquareComplex

end FiniteChains
