import RequestProject.SquareComplexWallsSeparation

/-!
# Hyperplanes of a square complex

A *wall system* (`FiniteChains.SquareComplex.WallSystem`) was so far always supplied by hand: for
the square complex of a median graph it came from the walls of the graph, for the complexes
`C(L)` from the generators of the right-angled Coxeter group.  This file constructs the wall
system that exists on **every** square complex, namely the system of its hyperplanes.

Two edges are *elementarily parallel* when they are opposite sides of a two-cell; a **hyperplane**
is a class of edges for the equivalence relation this generates (`FiniteChains.SquareComplex.Hyp`).
The characteristic function of a hyperplane is a square-closed edge label
(`FiniteChains.SquareComplex.hypLabel_isWallLabel`), and every edge lies on exactly one hyperplane,
so the hyperplanes form a wall system (`FiniteChains.SquareComplex.hypWallSystem`).

Consequences, for a connected and simply connected complex:

* every hyperplane is **two-sided** and separates the complex into two halfspaces
  (`hyp_exists_side`, `exists_hypCoordinates`);
* the two endpoints of an edge are separated by exactly one hyperplane, its own
  (`hypCoord_edge`);
* the number of hyperplanes separating two vertices is at most their distance
  (`sepHyp_card_le_length`);
* the remaining content of Gromov's criterion is isolated: *if* shortest walks cross every
  hyperplane at most once, then distinct vertices are separated by a hyperplane and the vertex set
  is a wall space (`hyp_separation_of_geodesic_crossings`, `hypWallSpace_of_geodesic_crossings`).

Nothing here uses any curvature hypothesis: hyperplanes exist in every square complex, and they
are two-sided as soon as the complex is simply connected.
-/

namespace FiniteChains

namespace SquareComplex

open Classical

universe u

variable {Vx : Type u} {S : SquareComplex Vx}

/-! ### Parallelism of edges -/

/-- The elementary parallelism step on *oriented* edges: reversing the orientation, or passing to
the opposite side of a two-cell. -/
def parStep (S : SquareComplex Vx) (p q : Vx × Vx) : Prop :=
  q = (p.2, p.1) ∨ S.sq p.1 p.2 q.1 q.2

/-- A **hyperplane** of a square complex: a class of oriented edges for the equivalence relation
generated by `FiniteChains.SquareComplex.parStep`.  (Non-edges also give classes; they are never
used, since the label of a hyperplane is supported on edges.) -/
def Hyp (S : SquareComplex Vx) : Type u := Quot (parStep S)

/-- The hyperplane carrying an oriented edge. -/
def hypOf (S : SquareComplex Vx) (a b : Vx) : S.Hyp := Quot.mk (parStep S) (a, b)

theorem hypOf_symm (S : SquareComplex Vx) (a b : Vx) : S.hypOf a b = S.hypOf b a :=
  Quot.sound (Or.inl rfl)

theorem hypOf_sq {a b c d : Vx} (h : S.sq a b c d) : S.hypOf a b = S.hypOf c d :=
  Quot.sound (Or.inr h)

/-- The characteristic function of a hyperplane: an edge carries the label `1` exactly when it
lies on that hyperplane. -/
noncomputable def hypLabel (S : SquareComplex Vx) (H : S.Hyp) (a b : Vx) : ZMod 2 :=
  if S.adj a b ∧ S.hypOf a b = H then 1 else 0

theorem hypLabel_self {a b : Vx} (hab : S.adj a b) : S.hypLabel (S.hypOf a b) a b = 1 := by
  simp [hypLabel, hab]

theorem hypLabel_eq_one_iff {H : S.Hyp} {a b : Vx} :
    S.hypLabel H a b = 1 ↔ S.adj a b ∧ S.hypOf a b = H := by
  unfold hypLabel
  constructor
  · intro hc
    by_contra h
    rw [if_neg h] at hc
    exact absurd hc (by decide)
  · intro h
    rw [if_pos h]

/-- Each hyperplane label is a wall label: it is symmetric and takes the same value on opposite
sides of every two-cell. -/
theorem hypLabel_isWallLabel (H : S.Hyp) : S.IsWallLabel (S.hypLabel H) := by
  constructor
  · intro a b
    unfold hypLabel
    by_cases hab : S.adj a b
    · simp [hab, S.adj_symm hab, S.hypOf_symm a b]
    · have hba : ¬ S.adj b a := fun h => hab (S.adj_symm h)
      simp [hab, hba]
  · intro a b c d hsq
    obtain ⟨hab, -, hcd, -⟩ := S.sq_adj hsq
    unfold hypLabel
    simp [hab, hcd, hypOf_sq hsq]

/-- **The hyperplanes form a wall system.**  Every edge lies on exactly one hyperplane, so the
characteristic functions of the hyperplanes are a family of square-closed labels crossed exactly
once by each edge. -/
noncomputable def hypWallSystem (S : SquareComplex Vx) : S.WallSystem S.Hyp where
  χ := S.hypLabel
  isWall := hypLabel_isWallLabel
  edge_unique := by
    intro u v huv
    refine ⟨S.hypOf u v, hypLabel_self huv, ?_⟩
    intro H hH
    exact (hypLabel_eq_one_iff.mp hH).2.symm

@[simp] theorem hypWallSystem_χ (S : SquareComplex Vx) : (S.hypWallSystem).χ = S.hypLabel := rfl

/-! ### Two-sidedness in a simply connected complex -/

/-- **Hyperplanes of a simply connected complex are two-sided.**  Sageev's hyperplane theorem, in
its combinatorial form: the edges of a hyperplane join the two classes of a two-colouring of the
vertices. -/
theorem hyp_exists_side (hSC : S.SimplyConnected) {x₀ : Vx}
    (hconn : ∀ v : Vx, ∃ l, S.IsWalkFrom x₀ v l) (H : S.Hyp) :
    ∃ σ : Vx → ZMod 2, σ x₀ = 0 ∧ ∀ u v : Vx, S.adj u v → σ u + σ v = S.hypLabel H u v :=
  exists_side hSC hconn (hypLabel_isWallLabel H)

/-- **Halfspace coordinates from hyperplanes.**  In a connected, simply connected square complex
every vertex acquires the set of hyperplanes separating it from the base vertex; the set is finite,
empty at the base vertex, and along an edge it changes by exactly one hyperplane. -/
theorem exists_hypCoordinates (hSC : S.SimplyConnected) {x₀ : Vx}
    (hconn : ∀ v : Vx, ∃ l, S.IsWalkFrom x₀ v l) :
    ∃ σ : S.Hyp → Vx → ZMod 2,
      (∀ H, σ H x₀ = 0) ∧
      (∀ (H : S.Hyp) (u v : Vx), S.adj u v → σ H u + σ H v = S.hypLabel H u v) ∧
      (∀ v : Vx, {H : S.Hyp | σ H v ≠ σ H x₀}.Finite) ∧
      (∀ u v : Vx, S.adj u v → ∃ K : S.Hyp, {H : S.Hyp | σ H u ≠ σ H v} = {K}) :=
  exists_rollerCoordinates hSC hconn S.hypWallSystem

/-- The endpoints of an edge are separated by exactly one hyperplane: the hyperplane of that
edge. -/
theorem hypCoord_edge {σ : S.Hyp → Vx → ZMod 2}
    (hσ : ∀ (H : S.Hyp) (u v : Vx), S.adj u v → σ H u + σ H v = S.hypLabel H u v)
    {u v : Vx} (huv : S.adj u v) : {H : S.Hyp | σ H u ≠ σ H v} = {S.hypOf u v} := by
  ext H
  simp only [Set.mem_setOf_eq, Set.mem_singleton_iff]
  have h := hσ H u v huv
  constructor
  · intro hne
    have h2 : ∀ c d : ZMod 2, c ≠ d → c + d = 1 := by decide
    have : S.hypLabel H u v = 1 := by rw [← h]; exact h2 _ _ hne
    exact (hypLabel_eq_one_iff.mp this).2.symm
  · intro hH
    subst hH
    rw [hypLabel_self huv] at h
    intro hcon
    rw [hcon] at h
    have h2 : ∀ c : ZMod 2, c + c ≠ 1 := by decide
    exact h2 _ h

/-! ### The distance bound, and what is left of Gromov's criterion -/

/-- **Hyperplanes bound the distance.**  The number of hyperplanes separating two vertices is at
most the length of any walk joining them. -/
theorem sepHyp_card_le_length {σ : S.Hyp → Vx → ZMod 2}
    (hσ : ∀ (H : S.Hyp) (u v : Vx), S.adj u v → σ H u + σ H v = S.hypLabel H u v)
    {u v : Vx} {l : List Vx} (hl : S.IsWalkFrom u v l) (T : Finset S.Hyp)
    (hT : ∀ H : S.Hyp, H ∈ T ↔ σ H u ≠ σ H v) :
    T.card + 1 ≤ l.length := by
  classical
  exact (sepWalls_card_le_length S.hypWallSystem hσ l u v hl T hT).1

/-- **Separation from the crossing criterion.**  If shortest walks cross every hyperplane at most
once — the one remaining geometric input of Gromov's criterion — then distinct vertices of a
connected, simply connected square complex are separated by a hyperplane. -/
theorem hyp_separation_of_geodesic_crossings {σ : S.Hyp → Vx → ZMod 2}
    (hσ : ∀ (H : S.Hyp) (u v : Vx), S.adj u v → σ H u + σ H v = S.hypLabel H u v)
    (hgeo : ∀ (u v : Vx) (l : List Vx), S.IsGeodesic u v l →
      ∀ H : S.Hyp, crossCount (S.hypLabel H) l ≤ 1)
    (hconn : ∀ u v : Vx, ∃ l, S.IsWalkFrom u v l) {u v : Vx} (huv : u ≠ v) :
    ∃ H : S.Hyp, σ H u ≠ σ H v :=
  separation_of_geodesic_crossings S.hypWallSystem hσ hconn hgeo u v huv

end SquareComplex

end FiniteChains
